import type { Place } from '@/types';

import { placeFactory, tier } from './helpers';

const city = placeFactory('cities');
const easy = tier('easy');
const intermediate = tier('intermediate');
const hard = tier('hard');
const master = tier('master');

export const CITIES: Place[] = [
  ...easy([
    city(
      'Paris',
      'France',
      'FR',
      48.8566,
      2.3522,
      'Capitale de la France depuis le Xe siècle, bâtie autour de la Seine. Sa tour Eiffel, achevée en 1889 pour l’Exposition universelle, était à l’origine une construction temporaire.',
    ),
    city(
      'Londres',
      'Royaume-Uni',
      'GB',
      51.5074,
      -0.1278,
      'Frappée en 1952 par le « Great Smog », un brouillard toxique qui a tué entre 4 000 et 12 000 personnes en quelques jours, la ville a depuis largement assaini son air.',
    ),
    city(
      'Berlin',
      'Allemagne',
      'DE',
      52.52,
      13.405,
      'Fondée en 1237 par la fusion de deux bourgs marchands, Berlin et Cölln, installés de part et d’autre de la Spree.',
    ),
    city(
      'Madrid',
      'Espagne',
      'ES',
      40.4168,
      -3.7038,
      'Simple bourgade jusqu’à ce que Philippe II y installe sa cour en 1561, faisant d’elle la capitale de l’Espagne.',
    ),
    city(
      'Barcelone',
      'Espagne',
      'ES',
      41.3851,
      2.1734,
      'Hôte des Jeux olympiques d’été de 1992, qui ont profondément transformé son front de mer et sa réputation touristique.',
    ),
    city(
      'Rome',
      'Italie',
      'IT',
      41.9028,
      12.4964,
      'Selon la légende, fondée par Romulus le 21 avril 753 av. J.-C. ; les fouilles archéologiques montrent en réalité une agglomération progressive de villages sur les collines dès le VIIIe siècle av. J.-C.',
    ),
    city(
      'Milan',
      'Italie',
      'IT',
      45.4642,
      9.19,
      'C’est à Milan que l’empereur Constantin proclame en 313 l’édit de tolérance religieuse qui autorise le culte chrétien dans tout l’Empire romain.',
    ),
    city(
      'Amsterdam',
      'Pays-Bas',
      'NL',
      52.3676,
      4.9041,
      'Sa Bourse, fondée en 1602 par la Compagnie néerlandaise des Indes orientales, est considérée comme la première bourse de valeurs moderne au monde.',
    ),
    city(
      'Bruxelles',
      'Belgique',
      'BE',
      50.8503,
      4.3517,
      'En 1695, l’armée de Louis XIV bombarde le centre de Bruxelles pendant la guerre de la Ligue d’Augsbourg, obligeant à reconstruire une grande partie de la vieille ville.',
    ),
    city(
      'Vienne',
      'Autriche',
      'AT',
      48.2082,
      16.3738,
      'En 1910, avec plus de deux millions d’habitants, Vienne était la troisième ville d’Europe après Londres et Paris.',
    ),
    city(
      'Prague',
      'Tchéquie',
      'CZ',
      50.0755,
      14.4378,
      'Son université, fondée par Charles IV en 1348, est la plus ancienne d’Europe centrale.',
    ),
    city(
      'Athènes',
      'Grèce',
      'GR',
      37.9838,
      23.7275,
      'En 1896, la ville a accueilli les premiers Jeux olympiques modernes, faisant renaître une tradition sportive antique interrompue depuis près de 1 500 ans.',
    ),
    city(
      'Moscou',
      'Russie',
      'RU',
      55.7558,
      37.6173,
      'Mentionnée pour la première fois dans les chroniques en 1147, lors d’une rencontre entre princes russes sur ce territoire.',
    ),
    city(
      'Istanbul',
      'Turquie',
      'TR',
      41.0082,
      28.9784,
      'Appelée Constantinople pendant plus de 1 500 ans, la ville n’a officiellement pris le nom d’Istanbul qu’en 1930, dans le cadre des réformes d’Atatürk.',
    ),
    city(
      'Le Caire',
      'Égypte',
      'EG',
      30.0444,
      31.2357,
      'Fondée en 969 par les califes fatimides, qui bâtirent en quatre ans une nouvelle ville fortifiée au nord de l’antique Fustat.',
    ),
    city(
      'Tokyo',
      'Japon',
      'JP',
      35.6762,
      139.6503,
      'Le grand séisme du Kantō, le 1er septembre 1923, a fait environ 105 000 morts et détruit une grande partie de la ville, reconstruite ensuite selon des normes antisismiques.',
    ),
    city(
      'Pékin',
      'Chine',
      'CN',
      39.9042,
      116.4074,
      'Devenue capitale de la dynastie Ming en 1420, année d’achèvement de la Cité interdite voulue par l’empereur Yongle.',
    ),
    city(
      'Shanghai',
      'Chine',
      'CN',
      31.2304,
      121.4737,
      'Le Parti communiste chinois y a été fondé en juillet 1921, dans le quartier de la Concession française.',
    ),
    city(
      'Hong Kong',
      'Chine',
      'HK',
      22.3193,
      114.1694,
      'Rétrocédée par le Royaume-Uni à la Chine à minuit le 1er juillet 1997, après 156 ans de domination britannique.',
    ),
    city(
      'Bangkok',
      'Thaïlande',
      'TH',
      13.7563,
      100.5018,
      'Fondée en 1782 quand le roi Rama Ier y transfère la capitale depuis Thonburi, sur l’autre rive du fleuve, fondant la dynastie Chakri toujours régnante.',
    ),
    city(
      'Singapour',
      'Singapour',
      'SG',
      1.3521,
      103.8198,
      'Devenue république indépendante le 9 août 1965, après sa séparation de la Fédération de Malaisie.',
    ),
    city(
      'Dubaï',
      'Émirats arabes unis',
      'AE',
      25.2048,
      55.2708,
      'Sa tour Burj Khalifa, achevée en 2010, culmine à 828 mètres et reste le plus haut gratte-ciel du monde.',
    ),
    city(
      'New Delhi',
      'Inde',
      'IN',
      28.6139,
      77.209,
      'Inaugurée officiellement comme capitale des Indes britanniques le 13 février 1931, après plus de vingt ans de construction.',
    ),
    city(
      'Mumbai',
      'Inde',
      'IN',
      19.076,
      72.8777,
      'La première ligne ferroviaire d’Inde y a été inaugurée le 16 avril 1853, entre Bombay et Thane.',
    ),
    city(
      'New York',
      'États-Unis',
      'US',
      40.7128,
      -74.006,
      'Manhattan a été achetée aux Lenapes en 1626 par le colon hollandais Peter Minuit pour l’équivalent de 60 florins.',
    ),
    city(
      'Los Angeles',
      'États-Unis',
      'US',
      34.0522,
      -118.2437,
      'Fondée le 4 septembre 1781 par 44 colons espagnols sous le nom de « El Pueblo de Nuestra Señora la Reina de los Ángeles ».',
    ),
    city(
      'San Francisco',
      'États-Unis',
      'US',
      37.7749,
      -122.4194,
      'Le séisme du 18 avril 1906 a détruit une grande partie de la ville, notamment par les incendies qui ont suivi la secousse.',
    ),
    city(
      'Chicago',
      'États-Unis',
      'US',
      41.8781,
      -87.6298,
      'Le grand incendie de 1871 a détruit environ 17 500 bâtiments et laissé un tiers de la population sans abri, avant une reconstruction qui en a fait un laboratoire du gratte-ciel.',
    ),
    city(
      'Miami',
      'États-Unis',
      'US',
      25.7617,
      -80.1918,
      'Constituée en municipalité le 28 juillet 1896 grâce à Julia Tuttle, propriétaire terrienne surnommée la « mère de Miami ».',
    ),
    city(
      'Montréal',
      'Canada',
      'CA',
      45.5017,
      -73.5673,
      'Seule ville canadienne à avoir accueilli des Jeux olympiques d’été, en 1976.',
    ),
    city(
      'Toronto',
      'Canada',
      'CA',
      43.6532,
      -79.3832,
      'La bourgade d’York, fondée en 1793, a été rebaptisée Toronto lors de son incorporation comme ville en 1834.',
    ),
    city(
      'Mexico',
      'Mexique',
      'MX',
      19.4326,
      -99.1332,
      'Les codex aztèques situent la fondation de Mexico-Tenochtitlan, sur une île du lac Texcoco, à l’année symbolique de 1325.',
    ),
    city(
      'Buenos Aires',
      'Argentine',
      'AR',
      -34.6037,
      -58.3816,
      'Fondée une première fois en 1536 par Pedro de Mendoza, la ville est abandonnée après des attaques amérindiennes avant d’être refondée durablement en 1580 par Juan de Garay.',
    ),
    city(
      'Rio de Janeiro',
      'Brésil',
      'BR',
      -22.9068,
      -43.1729,
      'Fondée le 1er mars 1565 par le Portugais Estácio de Sá sous le nom de São Sebastião do Rio de Janeiro, en l’honneur du roi Sébastien Ier.',
    ),
    city(
      'São Paulo',
      'Brésil',
      'BR',
      -23.5505,
      -46.6333,
      'Fondée le 25 janvier 1554 par des jésuites qui y établissent un collège, un jour choisi pour coïncider avec la fête de la conversion de saint Paul.',
    ),
    city(
      'Sydney',
      'Australie',
      'AU',
      -33.8688,
      151.2093,
      'Fondée en 1788 par le capitaine Arthur Phillip comme colonie pénitentiaire de la baie de Sydney Cove.',
    ),
    city(
      'Auckland',
      'Nouvelle-Zélande',
      'NZ',
      -36.8485,
      174.7633,
      'Le navire de Greenpeace Rainbow Warrior y a été coulé par les services secrets français le 10 juillet 1985, provoquant une crise diplomatique avec la France.',
    ),
  ]),

  ...intermediate([
    // France
    city(
      'Marseille',
      'France',
      'FR',
      43.2965,
      5.3698,
      'Fondée vers 600 av. J.-C. par des marins grecs venus de Phocée sous le nom de Massalia, c’est la plus ancienne ville de France.',
    ),
    city(
      'Lyon',
      'France',
      'FR',
      45.764,
      4.8357,
      'Capitale de la Gaule romaine sous le nom de Lugdunum, elle était surnommée « Caput Galliae », la capitale des Gaules.',
    ),
    city(
      'Toulouse',
      'France',
      'FR',
      43.6047,
      1.4442,
      'Le canal du Midi, qui la relie à la Méditerranée, est inscrit au patrimoine mondial de l’UNESCO depuis 1996.',
    ),
    city(
      'Nice',
      'France',
      'FR',
      43.7102,
      7.262,
      'Rattachée à la France en 1860 par le traité de Turin, en échange du soutien de Napoléon III à l’unité italienne.',
    ),
    city(
      'Nantes',
      'France',
      'FR',
      47.2184,
      -1.5536,
      'Sacrée capitale verte de l’Europe en 2013, distinction attribuée par la Commission européenne.',
    ),
    city(
      'Strasbourg',
      'France',
      'FR',
      48.5734,
      7.7521,
      'Sa Grande Île, cœur historique de la ville, est inscrite au patrimoine mondial de l’UNESCO depuis 1988.',
    ),
    city(
      'Bordeaux',
      'France',
      'FR',
      44.8378,
      -0.5792,
      'Son « Port de la Lune », vaste ensemble urbain du XVIIIe siècle, a été inscrit au patrimoine mondial de l’UNESCO en 2007.',
    ),
    city(
      'Lille',
      'France',
      'FR',
      50.6292,
      3.0573,
      'Le VAL, mis en service le 25 avril 1983, y a été le tout premier métro automatique léger du monde.',
    ),
    city(
      'Rennes',
      'France',
      'FR',
      48.1173,
      -1.6778,
      'Ravagé par un incendie en 1720, son centre médiéval à pans de bois a été en partie reconstruit en pierre.',
    ),
    city(
      'Montpellier',
      'France',
      'FR',
      43.6108,
      3.8767,
      'Depuis les années 1990, elle connaît l’une des croissances démographiques les plus fortes de France.',
    ),

    // Europe
    city(
      'Lisbonne',
      'Portugal',
      'PT',
      38.7223,
      -9.1393,
      'Un séisme dévastateur, le 1er novembre 1755, a détruit environ 85 % de la ville et inspiré la réflexion philosophique de Voltaire.',
    ),
    city(
      'Zurich',
      'Suisse',
      'CH',
      47.3769,
      8.5417,
      'Devenue le 1er mai 1351 le cinquième membre de la Confédération suisse.',
    ),
    city(
      'Varsovie',
      'Pologne',
      'PL',
      52.2297,
      21.0122,
      'Détruite à environ 85 % pendant la Seconde Guerre mondiale, la ville a été intégralement reconstruite après 1945, dont sa vieille ville restituée à l’identique.',
    ),
    city(
      'Budapest',
      'Hongrie',
      'HU',
      47.4979,
      19.0402,
      'Créée le 17 novembre 1873 par la fusion de Buda, Óbuda et Pest, de part et d’autre du Danube.',
    ),
    city(
      'Bucarest',
      'Roumanie',
      'RO',
      44.4268,
      26.1025,
      'Mentionnée pour la première fois en 1459 comme cité fortifiée, elle fut alors la résidence de Vlad l’Empaleur.',
    ),
    city(
      'Copenhague',
      'Danemark',
      'DK',
      55.6761,
      12.5683,
      'Son université, fondée en 1479, est la plus ancienne du Danemark.',
    ),
    city(
      'Stockholm',
      'Suède',
      'SE',
      59.3293,
      18.0686,
      'Mentionnée pour la première fois en 1252, elle aurait été fondée par le régent Birger Jarl sur l’île de Gamla Stan.',
    ),
    city(
      'Oslo',
      'Norvège',
      'NO',
      59.9139,
      10.7522,
      'Rebaptisée Oslo le 1er janvier 1925, après avoir porté le nom de Christiania pendant près de trois siècles.',
    ),
    city(
      'Helsinki',
      'Finlande',
      'FI',
      60.1699,
      24.9384,
      'Fondée en 1550 par le roi de Suède Gustave Vasa sous le nom d’Helsingfors, pour concurrencer la ville hanséatique de Tallinn.',
    ),
    city(
      'Reykjavik',
      'Islande',
      'IS',
      64.1466,
      -21.9426,
      'A accueilli en 1972 le championnat du monde d’échecs, l’un des matchs les plus médiatisés de la Guerre froide.',
    ),
    city(
      'Dublin',
      'Irlande',
      'IE',
      53.3498,
      -6.2603,
      'Le Trinity College, fondé en 1592 par la reine Élisabeth Ire, en est la plus ancienne université.',
    ),
    city(
      'Kiev',
      'Ukraine',
      'UA',
      50.4501,
      30.5234,
      'Selon la chronique des temps passés, la ville fut conquise en 882 par le prince varègue Oleg, qui en fit la capitale de la Rous’ de Kiev.',
    ),
    city(
      'Édimbourg',
      'Royaume-Uni',
      'GB',
      55.9533,
      -3.1883,
      'Sa vieille ville et sa ville nouvelle géorgienne sont inscrites ensemble au patrimoine mondial de l’UNESCO depuis 1995.',
    ),
    city(
      'Séville',
      'Espagne',
      'ES',
      37.3891,
      -5.9845,
      'La couronne espagnole y installe en 1503 la Casa de Contratación, qui fait de la ville le port du commerce avec les Amériques.',
    ),
    city(
      'Munich',
      'Allemagne',
      'DE',
      48.1351,
      11.582,
      'Sa fondation officielle remonte au 14 juin 1158, date de l’accord d’Augsbourg entre Henri le Lion et l’évêque de Freising.',
    ),

    // Afrique
    city(
      'Casablanca',
      'Maroc',
      'MA',
      33.5731,
      -7.5898,
      'Roosevelt et Churchill y ont tenu la conférence de Casablanca en janvier 1943, où les Alliés ont adopté la doctrine de la capitulation sans conditions.',
    ),
    city(
      'Alger',
      'Algérie',
      'DZ',
      36.7538,
      3.0588,
      'Reconstruite au milieu du Xe siècle sur les ruines de l’antique Icosium, elle est baptisée « Djezaïr Beni Mezghenna » vers 960.',
    ),
    city(
      'Tunis',
      'Tunisie',
      'TN',
      36.8065,
      10.1815,
      'Fondée en 698 autour du noyau initial de la mosquée Zitouna.',
    ),
    city(
      'Dakar',
      'Sénégal',
      'SN',
      14.7167,
      -17.4677,
      'Son Monument de la Renaissance africaine, haut de 52 m et inauguré en 2010, est considéré comme la plus haute statue d’Afrique.',
    ),
    city(
      'Lagos',
      'Nigeria',
      'NG',
      6.5244,
      3.3792,
      'Capitale du Nigeria de 1914 à 1991, avant le transfert des institutions vers Abuja.',
    ),
    city(
      'Johannesburg',
      'Afrique du Sud',
      'ZA',
      -26.2041,
      28.0473,
      'Née en 1886 de la découverte d’or dans le Witwatersrand, elle comptait déjà 100 000 habitants une décennie plus tard.',
    ),
    city(
      'Le Cap',
      'Afrique du Sud',
      'ZA',
      -33.9249,
      18.4241,
      'Jan van Riebeeck y a fondé le 6 avril 1652 une escale de ravitaillement pour la Compagnie néerlandaise des Indes orientales.',
    ),
    city(
      'Nairobi',
      'Kenya',
      'KE',
      -1.2921,
      36.8219,
      'Fondée en 1899 comme dépôt ferroviaire de la ligne Kenya-Ouganda, choisie pour son climat tempéré et son altitude.',
    ),

    // Asie
    city(
      'Séoul',
      'Corée du Sud',
      'KR',
      37.5665,
      126.978,
      'A accueilli les Jeux olympiques d’été de 1988, symbole de l’essor économique sud-coréen.',
    ),
    city(
      'Taipei',
      'Taïwan',
      'TW',
      25.033,
      121.5654,
      'Sa tour Taipei 101, achevée en 2004, a été le plus haut gratte-ciel du monde jusqu’à l’ouverture du Burj Khalifa en 2010.',
    ),
    city(
      'Hanoï',
      'Viêt Nam',
      'VN',
      21.0278,
      105.8342,
      'Fondée en 1010 par l’empereur Lý Thái Tổ sous le nom de Thăng Long, « le dragon prenant son envol ».',
    ),
    city(
      'Kuala Lumpur',
      'Malaisie',
      'MY',
      3.139,
      101.6869,
      'Née vers 1857 d’un campement de mineurs d’étain envoyés par le Raja Abdullah, à la confluence boueuse qui lui donne son nom.',
    ),
    city(
      'Jakarta',
      'Indonésie',
      'ID',
      -6.2088,
      106.8456,
      'Fondée en 1527 sous le nom de Jayakarta, elle devient Batavia sous les Hollandais en 1619, avant de devenir la capitale de l’Indonésie indépendante en 1945.',
    ),
    city(
      'Manille',
      'Philippines',
      'PH',
      14.5995,
      120.9842,
      'Fondée en 1571 par le conquistador espagnol Miguel López de Legazpi, qui en fait la capitale des Philippines espagnoles.',
    ),
    city(
      'Katmandou',
      'Népal',
      'NP',
      27.7172,
      85.324,
      'Son nom vient du Kasthamandap, un pavillon reconstruit en 1596, entièrement en bois et sans le moindre clou de fer.',
    ),
    city(
      'Téhéran',
      'Iran',
      'IR',
      35.6892,
      51.389,
      'Choisie comme capitale en 1786 par Agha Mohammad Khan Qajar, fondateur de la dynastie qadjare.',
    ),
    city(
      'Riyad',
      'Arabie saoudite',
      'SA',
      24.7136,
      46.6753,
      'La prise du fort de Masmak en 1902 par Ibn Saoud y marque le point de départ de la reconquête qui fondera l’Arabie saoudite moderne.',
    ),
    city(
      'Beyrouth',
      'Liban',
      'LB',
      33.8938,
      35.5018,
      'Le 4 août 2020, l’explosion de nitrate d’ammonium stocké dans son port a fait plus de 200 morts.',
    ),

    // Amériques
    city(
      'Vancouver',
      'Canada',
      'CA',
      49.2827,
      -123.1207,
      'Incorporée en avril 1886, la ville a été presque entièrement détruite deux mois plus tard par un incendie, avant d’être aussitôt reconstruite.',
    ),
    city(
      'La Havane',
      'Cuba',
      'CU',
      23.1136,
      -82.3666,
      'Avec le premier tronçon ferroviaire de 1837 reliant La Havane à Bejucal, Cuba devient le cinquième pays au monde, et le premier hispanophone, à posséder un chemin de fer.',
    ),
    city(
      'Bogota',
      'Colombie',
      'CO',
      4.711,
      -74.0721,
      'Fondée le 6 août 1538 par le conquistador Gonzalo Jiménez de Quesada, elle est perchée à 2 640 m d’altitude.',
    ),
    city(
      'Caracas',
      'Venezuela',
      'VE',
      10.4806,
      -66.9036,
      'Fondée en 1567 par Diego de Losada sous le nom de Santiago de León de Caracas.',
    ),
    city(
      'Lima',
      'Pérou',
      'PE',
      -12.0464,
      -77.0428,
      'Fondée le 18 janvier 1535 par Francisco Pizarro sous le nom de Cité des Rois, en référence à l’Épiphanie.',
    ),
    city(
      'Santiago',
      'Chili',
      'CL',
      -33.4489,
      -70.6693,
      'Fondée le 12 février 1541 par le conquistador Pedro de Valdivia, en l’honneur de l’apôtre saint Jacques.',
    ),
    city(
      'Anchorage',
      'États-Unis',
      'US',
      61.2181,
      -149.9003,
      'Frappée le 27 mars 1964 par un séisme de magnitude 9,2, l’un des plus puissants jamais enregistrés.',
    ),
    city(
      'Honolulu',
      'États-Unis',
      'US',
      21.3069,
      -157.8583,
      'La base voisine de Pearl Harbor y a subi l’attaque japonaise du 7 décembre 1941, qui a précipité l’entrée des États-Unis dans la Seconde Guerre mondiale.',
    ),
    city(
      'Panama',
      'Panama',
      'PA',
      8.9824,
      -79.5199,
      'Fondée le 15 août 1519 par Pedro Arias Dávila, c’est la première ville européenne établie sur la côte Pacifique des Amériques.',
    ),
    city(
      'Quito',
      'Équateur',
      'EC',
      -0.1807,
      -78.4678,
      'Avec Cracovie, elle fut en 1978 l’un des tout premiers sites inscrits au patrimoine mondial de l’UNESCO.',
    ),
    city(
      'La Paz',
      'Bolivie',
      'BO',
      -16.5,
      -68.15,
      'Fondée le 20 octobre 1548, elle est à environ 3 650 m d’altitude la capitale administrative la plus haute du monde.',
    ),

    // Océanie
    city(
      'Melbourne',
      'Australie',
      'AU',
      -37.8136,
      144.9631,
      'Baptisée en 1837 en l’honneur du Premier ministre britannique William Lamb, second vicomte Melbourne.',
    ),
    city(
      'Perth',
      'Australie',
      'AU',
      -31.9505,
      115.8605,
      'En 1962, ses habitants ont illuminé la ville pour saluer l’astronaute John Glenn en orbite, lui valant le surnom de « ville lumière ».',
    ),
    city(
      'Wellington',
      'Nouvelle-Zélande',
      'NZ',
      -41.2866,
      174.7756,
      'Devenue capitale de la Nouvelle-Zélande en 1865, en remplacement d’Auckland.',
    ),
    city(
      'Nouméa',
      'Nouvelle-Calédonie',
      'NC',
      -22.2558,
      166.4505,
      'D’abord nommée Port-de-France, la ville prend son nom actuel en 1866.',
    ),
    city(
      'Papeete',
      'Polynésie française',
      'PF',
      -17.5516,
      -149.5585,
      'Bombardée le 22 septembre 1914 par les croiseurs allemands Scharnhorst et Gneisenau, lors d’un épisode de la Première Guerre mondiale.',
    ),

    // Plus
    city('Jeddah', 'Arabie saoudite', 'SA', 21.5433, 39.1728, 'Principal port de la mer Rouge et porte d’entrée historique des pèlerins se rendant à La Mecque.'),
    city('Abu Dhabi', 'Émirats arabes unis', 'AE', 24.4539, 54.3773, 'Capitale politique des Émirats arabes unis, bâtie sur une île reliée au continent par plusieurs ponts.'),
    city('Bangalore', 'Inde', 'IN', 12.9716, 77.5946, 'Surnommée la « Silicon Valley indienne » pour la concentration d’entreprises informatiques qui s’y sont installées depuis les années 1980.'),
    city('Chennai', 'Inde', 'IN', 13.0827, 80.2707, 'Fondée en 1639 par la Compagnie britannique des Indes orientales autour du fort St George.'),
    city('Kolkata', 'Inde', 'IN', 22.5726, 88.3639, 'Capitale de l’Inde britannique jusqu’en 1911, avant le transfert des institutions vers New Delhi.'),
    city('Hyderabad', 'Inde', 'IN', 17.385, 78.4867, 'Fondée en 1591 par le sultan Muhammad Quli Qutb Shah, elle est réputée pour son commerce historique de perles.'),
    city('Ahmedabad', 'Inde', 'IN', 23.0225, 72.5714, 'Fondée en 1411 par le sultan Ahmed Shah sur les rives de la rivière Sabarmati.'),
    city('Guadalajara', 'Mexique', 'MX', 20.6597, -103.3496, 'Deuxième ville du Mexique par la population, berceau revendiqué du mariachi.'),
    city('Monterrey', 'Mexique', 'MX', 25.6866, -100.3161, 'Grand centre industriel du nord du Mexique, surnommé la « Sultane du Nord ».'),
    city('Córdoba', 'Argentine', 'AR', -31.4201, -64.1888, 'Sa cathédrale et ses édifices jésuites du XVIIe siècle forment un ensemble classé au patrimoine mondial de l’UNESCO.'),
    city('Rosario', 'Argentine', 'AR', -32.9468, -60.6393, 'Ville natale du Che Guevara, né en 1928, et de Lionel Messi, né en 1987.'),
    city('Curitiba', 'Brésil', 'BR', -25.4284, -49.2733, 'Pionnière dès les années 1970 de l’urbanisme écologique, avec un réseau de bus rapide qui a inspiré de nombreuses villes.'),
    city('Recife', 'Brésil', 'BR', -8.0476, -34.877, 'Traversée par de nombreux canaux et ponts, elle est surnommée la « Venise brésilienne ».'),
    city('Fortaleza', 'Brésil', 'BR', -3.7319, -38.5267, 'Fondée autour d’un fort portugais du XVIIe siècle dont elle tire son nom, qui signifie « forteresse ».'),
    city('Cali', 'Colombie', 'CO', 3.4516, -76.532, 'Considérée comme la capitale mondiale de la salsa, avec un festival annuel dédié à cette danse.'),
    city('Cartagena', 'Colombie', 'CO', 10.391, -75.4794, 'Ses fortifications du XVIe siècle, bâties pour protéger le port des attaques de pirates, sont classées au patrimoine mondial de l’UNESCO.'),
    city('Arequipa', 'Pérou', 'PE', -16.409, -71.5375, 'Construite en grande partie en pierre volcanique blanche, elle est surnommée la « Ville blanche ».'),
    city('Valparaíso', 'Chili', 'CL', -33.0472, -71.6127, 'Son centre historique aux maisons colorées accrochées aux collines est inscrit au patrimoine mondial de l’UNESCO depuis 2003.'),
    city('Durban', 'Afrique du Sud', 'ZA', -29.8587, 31.0218, 'Abrite le plus grand port d’Afrique subsaharienne, sur une vaste baie naturelle.'),
    city('Pretoria', 'Afrique du Sud', 'ZA', -25.7461, 28.1881, 'Capitale administrative de l’Afrique du Sud, connue pour ses avenues bordées de jacarandas qui fleurissent en violet chaque printemps austral.'),
    city('Rangoun', 'Myanmar', 'MM', 16.8661, 96.1951, 'Capitale du Myanmar jusqu’en 2006, date du transfert des institutions vers Naypyidaw.'),
    city('Surabaya', 'Indonésie', 'ID', -7.2575, 112.7521, 'Deuxième ville d’Indonésie par la population, son nom évoquerait un combat légendaire entre un requin et un crocodile.'),
    city('Bandung', 'Indonésie', 'ID', -6.9175, 107.6191, 'A accueilli en 1955 la conférence de Bandung, qui réunit pour la première fois des pays d’Asie et d’Afrique nouvellement indépendants.'),
    city('Cebu', 'Philippines', 'PH', 10.3157, 123.8854, 'Premier point d’ancrage de Magellan aux Philippines en 1521, où l’explorateur trouva la mort lors d’un affrontement avec le chef local Lapu-Lapu.'),
    city('Ürümqi', 'Chine', 'CN', 43.8256, 87.6168, 'Ville chinoise la plus éloignée de tout océan, à plus de 2 000 km de la mer la plus proche.'),
    city('Harbin', 'Chine', 'CN', 45.8038, 126.5349, 'Célèbre pour son festival international de sculptures sur glace et neige, organisé chaque hiver depuis 1985.'),
    city('Nankin', 'Chine', 'CN', 32.0603, 118.7969, 'Capitale de plusieurs dynasties chinoises, elle porte un nom qui signifie littéralement « capitale du Sud ».'),
    city('Portland', 'États-Unis', 'US', 45.5152, -122.6784, 'Doit son nom à un tirage à pile ou face entre ses deux fondateurs en 1845, l’un voulant l’appeler Boston.'),
    city('Minneapolis', 'États-Unis', 'US', 44.9778, -93.265, 'Son nom mêle le mot dakota « minne », qui signifie eau, et le grec « polis », la ville, en référence à ses nombreux lacs.'),
    city('La Nouvelle-Orléans', 'États-Unis', 'US', 29.9511, -90.0715, 'Fondée en 1718 par des colons français, elle a été dévastée par l’ouragan Katrina en août 2005.'),
    city('San Diego', 'États-Unis', 'US', 32.7157, -117.1611, 'Premier point du littoral californien exploré par les Européens, avec l’arrivée du navigateur Juan Rodríguez Cabrillo en 1542.'),
    city('San Antonio', 'États-Unis', 'US', 29.4241, -98.4936, 'Sa mission Alamo, fondée en 1718, fut le théâtre en 1836 d’une bataille devenue un symbole de l’indépendance texane.'),
    city('Austin', 'États-Unis', 'US', 30.2672, -97.7431, 'Devenue capitale du Texas en 1839, elle doit son nom à Stephen F. Austin, considéré comme le père fondateur de l’État.'),
  ]),

  ...hard([
    // France
    city('Reims', 'France', 'FR', 49.2583, 4.0317, 'Sa cathédrale accueillit le sacre de la plupart des rois de France, dont celui de Charles VII en 1429 en présence de Jeanne d’Arc.'),
    city('Le Havre', 'France', 'FR', 49.4944, 0.1079, 'Fondée en 1517 par François Ier, détruite à plus de 80 % en 1944, elle a été reconstruite selon les plans d’Auguste Perret, inscrits au patrimoine mondial de l’UNESCO.'),
    city('Grenoble', 'France', 'FR', 45.1885, 5.7245, 'A accueilli les Jeux olympiques d’hiver de 1968.'),
    city('Dijon', 'France', 'FR', 47.322, 5.0415, 'Capitale historique des ducs de Bourgogne, elle a donné son nom à la moutarde qui s’y fabrique depuis le Moyen Âge.'),
    city('Brest', 'France', 'FR', 48.3904, -4.4861, 'Sa rade, l’une des plus grandes d’Europe, abrite depuis Louis XIV un port militaire majeur de la Marine nationale.'),
    city('Clermont-Ferrand', 'France', 'FR', 45.7772, 3.087, 'Née en 1731 de la fusion de Clermont et Montferrand, elle est le berceau du fabricant de pneus Michelin, fondé en 1889.'),
    city('Limoges', 'France', 'FR', 45.8336, 1.2611, 'Réputée depuis le XVIIIe siècle pour sa porcelaine, grâce à la découverte de kaolin dans la région en 1768.'),
    city('Tours', 'France', 'FR', 47.3941, 0.6848, 'La bataille de 732, livrée non loin de la ville, aurait stoppé l’avancée d’une armée omeyyade en Europe occidentale.'),
    city('Perpignan', 'France', 'FR', 42.6887, 2.8948, 'Capitale du royaume de Majorque de 1276 à 1344, avant son rattachement à la couronne d’Aragon.'),
    city('Metz', 'France', 'FR', 49.1193, 6.1757, 'Rattachée à l’Empire allemand de 1871 à 1918, après la défaite française de la guerre de 1870.'),
    city('Rouen', 'France', 'FR', 49.4432, 1.0993, 'Jeanne d’Arc y fut brûlée vive le 30 mai 1431, sur la place du Vieux-Marché.'),
    city('Nancy', 'France', 'FR', 48.6921, 6.1844, 'Sa place Stanislas, aménagée au XVIIIe siècle par l’ex-roi de Pologne Stanislas Leszczyński, est inscrite au patrimoine mondial de l’UNESCO.'),
    city('Caen', 'France', 'FR', 49.1829, -0.3707, 'Largement détruite lors de la bataille de Normandie de l’été 1944, elle a été reconstruite après la guerre.'),
    city('Avignon', 'France', 'FR', 43.9493, 4.8055, 'Résidence des papes de 1309 à 1377, période durant laquelle sept souverains pontifes s’y sont succédé.'),
    city('Ajaccio', 'France', 'FR', 41.9192, 8.7386, 'Ville natale de Napoléon Bonaparte, né le 15 août 1769.'),
    city('Bastia', 'France', 'FR', 42.6977, 9.4503, 'Ancienne capitale de la Corse sous domination génoise, elle doit son nom à la « bastiglia », une forteresse édifiée en 1380.'),
    city('Biarritz', 'France', 'FR', 43.4832, -1.5586, 'Simple village de pêcheurs avant que l’impératrice Eugénie n’y fasse construire une villa en 1854, lançant sa vogue balnéaire.'),
    city('Annecy', 'France', 'FR', 45.8992, 6.1294, 'Son lac, réputé pour sa pureté, est alimenté et vidé par la même rivière, le Thiou.'),
    city('La Rochelle', 'France', 'FR', 46.1591, -1.152, 'Son port fut le théâtre d’un siège de plus d’un an mené par Richelieu contre les protestants, achevé en 1628.'),
    city('Amiens', 'France', 'FR', 49.8941, 2.2958, 'Sa cathédrale gothique, achevée au XIIIe siècle, est la plus vaste de France par le volume intérieur.'),
    city('Orléans', 'France', 'FR', 47.9029, 1.9093, 'Jeanne d’Arc y leva le siège anglais le 8 mai 1429, un événement toujours célébré chaque année dans la ville.'),
    city('Le Mans', 'France', 'FR', 48.0061, 0.1996, 'Ses 24 Heures automobiles, disputées pour la première fois en 1923, en font la doyenne des courses d’endurance.'),
    city('Saint-Étienne', 'France', 'FR', 45.4397, 4.3872, 'Ancien bassin houiller et centre historique de l’armement et du cycle, elle a été désignée ville UNESCO de design en 2010.'),
    city('Toulon', 'France', 'FR', 43.1242, 5.928, 'Sa rade abrite depuis le XVIIe siècle le plus grand port militaire de France en Méditerranée.'),
    city('Nîmes', 'France', 'FR', 43.8367, 4.3601, 'Ses arènes romaines, construites à la fin du Ier siècle, accueillent encore aujourd’hui spectacles et corridas.'),
    city('Angers', 'France', 'FR', 47.4784, -0.5632, 'Son château médiéval abrite la tapisserie de l’Apocalypse, tissée à la fin du XIVe siècle et considérée comme la plus grande tapisserie médiévale connue.'),
    city('Poitiers', 'France', 'FR', 46.5802, 0.3404, 'Charles Martel y aurait stoppé en 732 une armée omeyyade, lors d’une bataille dont l’emplacement exact reste débattu par les historiens.'),
    city('Cherbourg', 'France', 'FR', 49.6337, -1.6221, 'Sa rade artificielle, achevée au XIXe siècle, compte parmi les plus vastes au monde construites par l’homme.'),
    city('Chamonix', 'France', 'FR', 45.9237, 6.8694, 'A accueilli en 1924 les tout premiers Jeux olympiques d’hiver.'),
    city('Carcassonne', 'France', 'FR', 43.213, 2.3491, 'Sa cité médiévale fortifiée, restaurée au XIXe siècle par Viollet-le-Duc, est inscrite au patrimoine mondial de l’UNESCO depuis 1997.'),
    city('Besançon', 'France', 'FR', 47.2378, 6.0241, 'Ville natale de Victor Hugo, né le 26 février 1802.'),
    city('Cannes', 'France', 'FR', 43.5528, 7.0174, 'Son festival international du film, créé en 1946, en a fait un rendez-vous mondial du cinéma.'),
    city('Saint-Malo', 'France', 'FR', 48.6493, -2.0257, 'Fief historique des corsaires, dont le plus célèbre, Robert Surcouf, y est né en 1773.'),
    city('Pau', 'France', 'FR', 43.2951, -0.3708, 'Ville natale du roi Henri IV, né en 1553 dans le château qui domine encore la ville.'),
    city('Colmar', 'France', 'FR', 48.0794, 7.3585, 'Ville natale du sculpteur Auguste Bartholdi, né en 1834, qui conçut la statue de la Liberté.'),
    city('Quimper', 'France', 'FR', 47.996, -4.1024, 'Réputée depuis le XVIIe siècle pour ses faïences peintes à la main.'),
    city('Chambéry', 'France', 'FR', 45.5646, 5.9178, 'Capitale historique du duché de Savoie avant le rattachement de la Savoie à la France en 1860.'),
    city('Calais', 'France', 'FR', 50.9513, 1.8587, 'Située face à l’Angleterre au point le plus étroit de la Manche, elle possède l’un des ports transmanche les plus fréquentés d’Europe.'),
    city('Bourges', 'France', 'FR', 47.081, 2.398, 'Sa cathédrale Saint-Étienne, achevée au XIIIe siècle, est inscrite au patrimoine mondial de l’UNESCO depuis 1992.'),
    city('Mulhouse', 'France', 'FR', 47.7508, 7.3359, 'Cité textile prospère dès le XVIIIe siècle, elle ne fut rattachée à la France qu’en 1798, après avoir longtemps été une république alliée des cantons suisses.'),
    city('Béziers', 'France', 'FR', 43.3442, 3.2158, 'Théâtre en 1209 d’un massacre de masse lors de la croisade contre les Albigeois, qui fit plusieurs milliers de victimes.'),
    city('Troyes', 'France', 'FR', 48.2973, 4.0744, 'Capitale historique de la Champagne, ses halles accueillaient au Moyen Âge de grandes foires commerciales internationales.'),
    city('Valence', 'France', 'FR', 44.9334, 4.8924, 'Porte d’entrée traditionnelle du Midi, elle marque une frontière climatique souvent citée entre le nord et le sud de la France.'),
    city('Vannes', 'France', 'FR', 47.6582, -2.7608, 'Capitale historique du peuple gaulois des Vénètes, vaincus par Jules César lors d’une bataille navale en 56 av. J.-C.'),
    city('Lorient', 'France', 'FR', 47.7482, -3.366, 'Fondée au XVIIe siècle par la Compagnie française des Indes orientales, dont elle tire son nom.'),
    city('Deauville', 'France', 'FR', 49.3591, 0.0757, 'Créée à partir de 1860 par le duc de Morny, demi-frère de Napoléon III, comme station balnéaire chic.'),
    city('Arcachon', 'France', 'FR', 44.6586, -1.1689, 'Toute proche, sa dune du Pilat, la plus haute dune de sable d’Europe, culmine à plus de 100 mètres.'),
    city('Albi', 'France', 'FR', 43.9298, 2.148, 'Sa cathédrale Sainte-Cécile, bâtie en brique après la croisade contre les cathares, compte parmi les plus grandes cathédrales de brique au monde.'),
    city('Angoulême', 'France', 'FR', 45.6486, 0.156, 'Surnommée capitale de la bande dessinée, elle accueille chaque année depuis 1974 un festival international qui lui est dédié.'),
    city('Bayonne', 'France', 'FR', 43.4933, -1.4748, 'Réputée pour son jambon et son chocolat, introduit dès le XVIe siècle par des juifs séfarades chassés d’Espagne et du Portugal.'),
    city('Saint-Tropez', 'France', 'FR', 43.2727, 6.6407, 'Simple village de pêcheurs avant que le film « Et Dieu... créa la femme », avec Brigitte Bardot en 1956, n’en fasse une destination à la mode.'),
    city('Auxerre', 'France', 'FR', 47.7975, 3.5731, 'Sa cathédrale et son abbaye Saint-Germain dominent les vignobles de Chablis, tout proches.'),

    // Europe
    city('Genève', 'Suisse', 'CH', 46.2044, 6.1432, 'Siège européen de l’ONU et de nombreuses organisations internationales, elle abrite aussi le CERN, où le World Wide Web a été inventé en 1989.'),
    city('Bâle', 'Suisse', 'CH', 47.5596, 7.5886, 'Y siège depuis 1930 la Banque des règlements internationaux, doyenne des institutions financières internationales.'),
    city('Lausanne', 'Suisse', 'CH', 46.5197, 6.6323, 'Siège du Comité international olympique depuis 1915, elle est surnommée la capitale olympique.'),
    city('Naples', 'Italie', 'IT', 40.8518, 14.2681, 'Sa pizza, née dans les échoppes populaires des XVIIIe et XIXe siècles, est inscrite au patrimoine culturel immatériel de l’UNESCO depuis 2017.'),
    city('Turin', 'Italie', 'IT', 45.0703, 7.6869, 'Première capitale de l’Italie unifiée, de 1861 à 1865, avant le transfert vers Florence puis Rome.'),
    city('Venise', 'Italie', 'IT', 45.4408, 12.3155, 'Bâtie sur plus d’une centaine d’îlots reliés par des centaines de ponts, elle n’a jamais eu de rues carrossables.'),
    city('Florence', 'Italie', 'IT', 43.7696, 11.2558, 'Berceau de la Renaissance italienne au XVe siècle, sous le mécénat de la famille Médicis.'),
    city('Bologne', 'Italie', 'IT', 44.4949, 11.3426, 'Son université, fondée en 1088, est considérée comme la plus ancienne université du monde occidental encore en activité.'),
    city('Palerme', 'Italie', 'IT', 38.1157, 13.3615, 'Sa cathédrale et ses monuments arabo-normands témoignent d’un brassage des cultures byzantine, islamique et normande au XIIe siècle.'),
    city('Porto', 'Portugal', 'PT', 41.1579, -8.6291, 'A donné son nom au Portugal et au vin qui y vieillit dans ses caves, exporté depuis des siècles vers l’Angleterre.'),
    city('Salzbourg', 'Autriche', 'AT', 47.8095, 13.055, 'Ville natale de Wolfgang Amadeus Mozart, né en 1756.'),
    city('Cracovie', 'Pologne', 'PL', 50.0647, 19.945, 'Capitale de la Pologne jusqu’en 1596, avant le transfert de la cour royale vers Varsovie.'),
    city('Bratislava', 'Slovaquie', 'SK', 48.1486, 17.1077, 'Capitale du royaume de Hongrie de 1536 à 1783, période durant laquelle une dizaine de rois y furent couronnés.'),
    city('Ljubljana', 'Slovénie', 'SI', 46.0569, 14.5058, 'Un dragon, lié à une légende locale, figure sur ses armoiries et sur son pont le plus célèbre.'),
    city('Zagreb', 'Croatie', 'HR', 45.815, 15.9819, 'Née au XIXe siècle de la fusion de deux collines rivales, Kaptol et Gradec.'),
    city('Belgrade', 'Serbie', 'RS', 44.7866, 20.4489, 'Son nom signifie « ville blanche » en serbe ; elle aurait été détruite et reconstruite à de nombreuses reprises au fil de son histoire.'),
    city('Sofia', 'Bulgarie', 'BG', 42.6977, 23.3219, 'L’une des plus anciennes villes d’Europe, occupée en continu depuis plusieurs millénaires selon les fouilles archéologiques.'),
    city('Thessalonique', 'Grèce', 'GR', 40.6401, 22.9444, 'Fondée vers 315 av. J.-C. par le roi macédonien Cassandre, qui la nomma en l’honneur de son épouse, demi-sœur d’Alexandre le Grand.'),
    city('Vilnius', 'Lituanie', 'LT', 54.6872, 25.2797, 'Sa vieille ville, l’une des plus vastes d’Europe orientale, est inscrite au patrimoine mondial de l’UNESCO depuis 1994.'),
    city('Riga', 'Lettonie', 'LV', 56.9496, 24.1052, 'Fondée en 1201 par l’évêque allemand Albert de Buxhoeveden, elle devint un comptoir majeur de la ligue hanséatique.'),
    city('Tallinn', 'Estonie', 'EE', 59.437, 24.7536, 'Sa vieille ville médiévale, l’une des mieux conservées d’Europe du Nord, est inscrite au patrimoine mondial de l’UNESCO depuis 1997.'),
    city('Bergen', 'Norvège', 'NO', 60.3913, 5.3221, 'Ancienne capitale de la Norvège au Moyen Âge, elle fut aussi un comptoir majeur de la ligue hanséatique.'),
    city('Gênes', 'Italie', 'IT', 44.4056, 8.9463, 'Ville natale, selon la tradition, de Christophe Colomb, elle fut longtemps une puissante République maritime rivale de Venise.'),
    city('Innsbruck', 'Autriche', 'AT', 47.2692, 11.4041, 'A accueilli deux fois les Jeux olympiques d’hiver, en 1964 et en 1976.'),
    city('Graz', 'Autriche', 'AT', 47.0707, 15.4395, 'Sa vieille ville, mêlant influences germaniques et méditerranéennes, est inscrite au patrimoine mondial de l’UNESCO depuis 1999.'),
    city('Gdańsk', 'Pologne', 'PL', 54.352, 18.6466, 'C’est dans ses chantiers navals qu’est né en 1980 le syndicat Solidarność, mené par Lech Wałęsa.'),
    city('Wrocław', 'Pologne', 'PL', 51.1079, 17.0385, 'Surnommée la ville aux cent ponts, elle est redevenue polonaise en 1945 après des siècles sous domination germanique.'),
    city('Brno', 'Tchéquie', 'CZ', 49.1951, 16.6068, 'Deuxième ville de République tchèque, son circuit automobile accueille depuis 1965 un grand prix moto.'),
    city('Sarajevo', 'Bosnie-Herzégovine', 'BA', 43.8563, 18.4131, 'L’assassinat de l’archiduc François-Ferdinand, le 28 juin 1914, y déclencha la Première Guerre mondiale.'),
    city('Skopje', 'Macédoine du Nord', 'MK', 41.9981, 21.4254, 'Ville natale de Mère Teresa, née en 1910.'),
    city('Tirana', 'Albanie', 'AL', 41.3275, 19.8187, 'Choisie comme capitale de l’Albanie en 1920, après l’indépendance du pays proclamée en 1912.'),
    city('Faro', 'Portugal', 'PT', 37.0194, -7.9304, 'Sa vieille ville fortifiée porte encore les traces de son passé sous domination maure, avant la reconquête chrétienne du XIIIe siècle.'),
    city('Palma de Majorque', 'Espagne', 'ES', 39.5696, 2.6502, 'Sa cathédrale gothique, dite « La Seu », domine la baie depuis le XIIIe siècle.'),
    city('Bilbao', 'Espagne', 'ES', 43.263, -2.935, 'Sa reconversion urbaine, engagée dans les années 1990 avec l’ouverture du musée Guggenheim en 1997, est devenue un modèle souvent cité de renouveau industriel.'),
    city('San Sebastián', 'Espagne', 'ES', 43.3183, -1.9812, 'Sa baie en forme de coquillage, la Concha, est considérée comme l’une des plus belles baies urbaines d’Europe.'),
    city('Valence (Espagne)', 'Espagne', 'ES', 39.4699, -0.3763, 'Berceau revendiqué de la paella, plat traditionnel né dans les rizières qui l’entourent.'),

    // Afrique
    city('Abidjan', "Côte d'Ivoire", 'CI', 5.36, -4.0083, 'Ancienne capitale de la Côte d’Ivoire jusqu’en 1983, elle reste le centre économique du pays malgré le transfert officiel des institutions vers Yamoussoukro.'),
    city('Kinshasa', 'RD Congo', 'CD', -4.4419, 15.2663, 'Séparée de Brazzaville par le seul fleuve Congo, elle forme avec sa voisine l’une des paires de capitales les plus rapprochées au monde.'),
    city('Addis-Abeba', 'Éthiopie', 'ET', 9.03, 38.74, 'Siège de l’Union africaine depuis sa fondation en 1963, elle est surnommée la capitale diplomatique de l’Afrique.'),
    city('Antananarivo', 'Madagascar', 'MG', -18.8792, 47.5079, 'Fondée au XVIIe siècle sur des collines fortifiées, son nom signifierait « la ville des mille » en malgache.'),
    city('Rabat', 'Maroc', 'MA', 34.0209, -6.8416, 'Capitale du Maroc depuis 1912, sa kasbah des Oudayas domine l’embouchure du fleuve Bouregreg.'),
    city('Marrakech', 'Maroc', 'MA', 31.6295, -7.9811, 'Fondée en 1070 par les Almoravides, elle a donné son nom au Maroc dans plusieurs langues.'),
    city('Fès', 'Maroc', 'MA', 34.0331, -5.0003, 'Sa médina, l’une des plus grandes zones piétonnes urbaines du monde, est inscrite au patrimoine mondial de l’UNESCO.'),
    city('Tripoli', 'Libye', 'LY', 32.8872, 13.1913, 'Fondée par les Phéniciens, elle tire son nom du grec signifiant « trois villes ».'),
    city('Khartoum', 'Soudan', 'SD', 15.5007, 32.5599, 'Située au confluent du Nil Blanc et du Nil Bleu, une position qui lui vaudrait son nom, évoquant la forme d’une trompe d’éléphant.'),
    city('Accra', 'Ghana', 'GH', 5.6037, -0.187, 'Devenue capitale du Ghana en 1957, lors de l’indépendance du premier pays d’Afrique subsaharienne à s’affranchir de la tutelle coloniale.'),
    city('Abuja', 'Nigeria', 'NG', 9.0765, 7.3986, 'Devenue capitale du Nigeria en 1991, choisie pour sa position centrale en remplacement de Lagos.'),
    city('Kano', 'Nigeria', 'NG', 12.0022, 8.592, 'L’une des plus anciennes villes d’Afrique de l’Ouest, ancien carrefour caravanier du commerce transsaharien.'),
    city('Kampala', 'Ouganda', 'UG', 0.3476, 32.5825, 'Bâtie à l’origine sur sept collines, comme Rome, elle en compte aujourd’hui bien davantage avec son extension urbaine.'),
    city('Kigali', 'Rwanda', 'RW', -1.9441, 30.0619, 'Réputée pour sa propreté, elle interdit les sacs plastiques à usage unique depuis 2008.'),
    city('Bujumbura', 'Burundi', 'BI', -3.3822, 29.3644, 'Capitale du Burundi jusqu’en 2018, avant le transfert des institutions politiques vers Gitega.'),
    city('Dar es Salaam', 'Tanzanie', 'TZ', -6.7924, 39.2083, 'Son nom signifie « le havre de paix » en arabe ; elle fut fondée en 1862 par le sultan de Zanzibar.'),
    city('Lusaka', 'Zambie', 'ZM', -15.3875, 28.3228, 'Devenue capitale de la Rhodésie du Nord en 1935, avant de devenir celle de la Zambie indépendante en 1964.'),
    city('Harare', 'Zimbabwe', 'ZW', -17.8252, 31.0335, 'Fondée en 1890 sous le nom de Fort Salisbury par les colons britanniques de la British South Africa Company.'),
    city('Gaborone', 'Botswana', 'BW', -24.6282, 25.9231, 'Bâtie quasiment de toutes pièces pour devenir la capitale du Botswana à son indépendance, en 1966.'),
    city('Windhoek', 'Namibie', 'NA', -22.5609, 17.0658, 'Placée entre deux chaînes de montagnes, son urbanisme garde encore des traces de l’ancienne colonisation allemande.'),
    city('Maputo', 'Mozambique', 'MZ', -25.9692, 32.5732, 'Rebaptisée en 1976, deux ans après l’indépendance du Mozambique, elle portait auparavant le nom de Lourenço Marques.'),
    city('Luanda', 'Angola', 'AO', -8.839, 13.2894, 'Fondée en 1576 par les Portugais, c’est l’une des plus anciennes villes d’origine européenne d’Afrique subsaharienne.'),
    city('Brazzaville', 'Congo', 'CG', -4.2634, 15.2429, 'Fondée en 1880 par l’explorateur Pierre Savorgnan de Brazza, dont elle porte le nom.'),
    city('Libreville', 'Gabon', 'GA', 0.4162, 9.4673, 'Fondée en 1849 par des esclaves libérés d’un navire négrier intercepté par la marine française, d’où son nom.'),
    city('Yaoundé', 'Cameroun', 'CM', 3.848, 11.5021, 'Fondée en 1888 par des commerçants allemands sur des hauteurs qui lui valent le surnom de ville aux sept collines.'),
    city('Douala', 'Cameroun', 'CM', 4.0511, 9.7679, 'Principal port et poumon économique du Cameroun, bien qu’elle n’en soit pas la capitale politique.'),
    city('Bamako', 'Mali', 'ML', 12.6392, -8.0029, 'Sur les rives du Niger, elle doit son essor moderne à l’arrivée du chemin de fer Dakar-Niger au début du XXe siècle.'),
    city('Ouagadougou', 'Burkina Faso', 'BF', 12.3714, -1.5197, 'Ancienne capitale de l’Empire mossi fondée au XVe siècle, avant de devenir celle du Burkina Faso.'),
    city('Niamey', 'Niger', 'NE', 13.5127, 2.1128, 'Sur les rives du fleuve Niger, elle devient capitale du Niger colonial français en 1926.'),
    city('Ibadan', 'Nigeria', 'NG', 7.3775, 3.947, 'Fut la plus grande ville d’Afrique subsaharienne au moment de l’indépendance du Nigeria en 1960.'),
    city('Port Harcourt', 'Nigeria', 'NG', 4.8156, 7.0498, 'Fondée en 1912 par les Britanniques pour l’exportation du charbon, elle doit son nom au ministre des Colonies Lewis Harcourt.'),
    city('Mombasa', 'Kenya', 'KE', -4.0435, 39.6682, 'Vieux port swahili de l’océan Indien, disputé pendant des siècles entre Portugais, Omanais et Britanniques.'),
    city('Bulawayo', 'Zimbabwe', 'ZW', -20.15, 28.5833, 'Son nom signifierait « le lieu du massacre » en ndébélé, en référence à une lutte de succession du XIXe siècle.'),
    city('Port Elizabeth', 'Afrique du Sud', 'ZA', -33.9608, 25.6022, 'Fondée en 1820 par des colons britanniques, elle a été renommée Gqeberha en 2021.'),
    city('Pointe-Noire', 'Congo', 'CG', -4.7761, 11.8636, 'Devenue capitale économique du Congo grâce à son port en eau profonde, le seul du pays ouvert sur l’Atlantique.'),
    city('Lubumbashi', 'RD Congo', 'CD', -11.6609, 27.4794, 'Fondée en 1910 sous le nom d’Élisabethville, elle doit son essor aux mines de cuivre du Katanga voisin.'),
    city('Nouakchott', 'Mauritanie', 'MR', 18.0858, -15.9785, 'Simple village de quelques centaines d’habitants avant d’être choisie comme capitale de la Mauritanie indépendante en 1960.'),

    // Asie
    city('Vladivostok', 'Russie', 'RU', 43.1332, 131.9113, 'Terminus oriental du Transsibérien, la plus longue ligne ferroviaire du monde, achevée en 1916.'),
    city('Novossibirsk', 'Russie', 'RU', 55.0084, 82.9357, 'Fondée en 1893 lors de la construction du Transsibérien, elle est devenue la plus grande ville de Sibérie.'),
    city('Osaka', 'Japon', 'JP', 34.6937, 135.5023, 'Son château, achevé en 1583 sous le seigneur Toyotomi Hideyoshi, fut l’un des symboles de l’unification du Japon.'),
    city('Kyoto', 'Japon', 'JP', 35.0116, 135.7681, 'Capitale impériale du Japon pendant plus d’un millénaire, de 794 à 1868, avant le transfert vers Tokyo.'),
    city('Nagoya', 'Japon', 'JP', 35.1815, 136.9066, 'Son château, achevé en 1612, était surmonté de dauphins dorés emblématiques, détruits puis reconstruits après la Seconde Guerre mondiale.'),
    city('Sapporo', 'Japon', 'JP', 43.0618, 141.3545, 'A accueilli en 1972 les premiers Jeux olympiques d’hiver organisés en Asie.'),
    city('Fukuoka', 'Japon', 'JP', 33.5904, 130.4017, 'Point d’arrivée traditionnel des influences venues de Chine et de Corée, elle fut aussi la cible de tentatives d’invasion mongole au XIIIe siècle.'),
    city('Busan', 'Corée du Sud', 'KR', 35.1796, 129.0756, 'Deuxième ville de Corée du Sud, son port fut l’un des derniers bastions tenus lors de la guerre de Corée au début des années 1950.'),
    city('Pyongyang', 'Corée du Nord', 'KP', 39.0392, 125.7625, 'Capitale de la Corée du Nord, largement reconstruite après avoir été détruite par les bombardements de la guerre de Corée.'),
    city('Guangzhou', 'Chine', 'CN', 23.1291, 113.2644, 'Ancien comptoir de la route maritime de la soie, elle fut pendant des siècles l’un des principaux points de contact commercial entre la Chine et l’Occident.'),
    city('Shenzhen', 'Chine', 'CN', 22.5431, 114.0579, 'Simple village de pêcheurs avant sa désignation en 1980 comme première zone économique spéciale de Chine, à l’origine de son essor fulgurant.'),
    city('Chengdu', 'Chine', 'CN', 30.5728, 104.0668, 'Abrite l’un des plus grands centres de recherche et d’élevage de pandas géants au monde.'),
    city('Xi’an', 'Chine', 'CN', 34.3416, 108.9398, 'Ancienne capitale impériale sous le nom de Chang’an, elle est le point de départ historique de la route de la soie et abrite l’armée de terre cuite, découverte en 1974.'),
    city('Wuhan', 'Chine', 'CN', 30.5928, 114.3055, 'Née de la fusion de trois villes situées au confluent du Yangtsé et de la rivière Han.'),
    city('Chongqing', 'Chine', 'CN', 29.4316, 106.9123, 'L’une des municipalités les plus peuplées de Chine, bâtie sur des collines escarpées au confluent du Yangtsé et de la rivière Jialing.'),
    city('Hô-Chi-Minh-Ville', 'Viêt Nam', 'VN', 10.8231, 106.6297, 'Rebaptisée en 1976 en l’honneur du dirigeant communiste, elle s’appelait auparavant Saïgon.'),
    city('Vientiane', 'Laos', 'LA', 17.9757, 102.6331, 'Devenue capitale du Laos au XVIe siècle sous le roi Setthathirath, qui y fit ériger le stupa doré du Pha That Luang.'),
    city('Phnom Penh', 'Cambodge', 'KH', 11.5564, 104.9282, 'Selon la légende, fondée par une femme nommée Penh qui aurait découvert des statues de Bouddha échouées sur les rives du Mékong.'),
    city('Naypyidaw', 'Myanmar', 'MM', 19.7633, 96.0785, 'Devenue capitale du Myanmar en 2005, en remplacement de Rangoun, dans le cadre d’un transfert des institutions tenu secret jusqu’à sa mise en œuvre.'),
    city('Colombo', 'Sri Lanka', 'LK', 6.9271, 79.8612, 'Ancien comptoir commercial disputé entre Portugais, Hollandais puis Britanniques, avant l’indépendance du Sri Lanka en 1948.'),
    city('Dacca', 'Bangladesh', 'BD', 23.8103, 90.4125, 'Surnommée la ville des mosquées, elle en compterait plusieurs centaines.'),
    city('Islamabad', 'Pakistan', 'PK', 33.6844, 73.0479, 'Bâtie de toutes pièces à partir des années 1960 pour devenir la capitale du Pakistan, en remplacement de Karachi.'),
    city('Karachi', 'Pakistan', 'PK', 24.8607, 67.0011, 'Ancienne capitale du Pakistan jusqu’en 1959, elle en reste le principal port et centre économique.'),
    city('Lahore', 'Pakistan', 'PK', 31.5497, 74.3436, 'Son fort et ses jardins de Shalimar, aménagés sous l’empire moghol au XVIIe siècle, sont inscrits au patrimoine mondial de l’UNESCO.'),
    city('Kaboul', 'Afghanistan', 'AF', 34.5553, 69.2075, 'Située à plus de 1 800 mètres d’altitude, elle fut une étape majeure sur les routes commerciales reliant l’Asie centrale au sous-continent indien.'),
    city('Douchanbé', 'Tadjikistan', 'TJ', 38.5598, 68.787, 'Son nom signifie « lundi » en tadjik, en référence au grand marché hebdomadaire qui s’y tenait ce jour-là.'),
    city('Bichkek', 'Kirghizistan', 'KG', 42.8746, 74.5698, 'Fondée en 1825 comme forteresse par le khanat de Kokand, avant de devenir capitale du Kirghizistan indépendant en 1991.'),
    city('Almaty', 'Kazakhstan', 'KZ', 43.222, 76.8512, 'Capitale du Kazakhstan jusqu’en 1997, avant le transfert des institutions vers Astana.'),
    city('Astana', 'Kazakhstan', 'KZ', 51.1605, 71.4704, 'Devenue capitale du Kazakhstan en 1997, elle fut brièvement renommée Noursoultan entre 2019 et 2022.'),
    city('Achgabat', 'Turkménistan', 'TM', 37.9601, 58.3261, 'Presque entièrement reconstruite après un séisme dévastateur en 1948, elle est réputée pour la densité de ses édifices en marbre blanc.'),
    city('Bagdad', 'Irak', 'IQ', 33.3152, 44.3661, 'Fondée en 762 par le calife abbasside Al-Mansour, elle fut pendant des siècles l’un des plus grands centres intellectuels du monde musulman.'),
    city('Amman', 'Jordanie', 'JO', 31.9454, 35.9284, 'Bâtie sur plusieurs collines, elle fut dans l’Antiquité une cité gréco-romaine du nom de Philadelphie.'),
    city('Damas', 'Syrie', 'SY', 33.5138, 36.2765, 'Souvent présentée comme l’une des plus anciennes villes continuellement habitées au monde.'),
    city('Jérusalem', 'Israël', 'IL', 31.7683, 35.2137, 'Ville sainte des trois grandes religions monothéistes, son statut international fait l’objet de contentieux persistants.'),
    city('Tel Aviv-Jaffa', 'Israël', 'IL', 32.0853, 34.7818, 'Fondée en 1909 par des familles juives sur des dunes au nord du port antique de Jaffa, avec lequel elle a fusionné en 1950.'),
    city('Koweït', 'Koweït', 'KW', 29.3759, 47.9774, 'Fondée au XVIIIe siècle autour d’un fort qui lui donne son nom, signifiant « petite forteresse » en arabe.'),
    city('Doha', 'Qatar', 'QA', 25.2854, 51.531, 'Petit port de pêche aux perles avant que l’exploitation de vastes gisements de gaz naturel ne transforme son économie.'),
    city('Manama', 'Bahreïn', 'BH', 26.2285, 50.586, 'Capitale du Bahreïn, elle est mentionnée dans des sources historiques dès le XIVe siècle comme port marchand.'),
    city('Mascate', 'Oman', 'OM', 23.588, 58.3829, 'Capitale d’Oman, sa baie est encadrée de forts portugais du XVIe siècle toujours visibles aujourd’hui.'),
    city('Sanaa', 'Yémen', 'YE', 15.3694, 44.191, 'L’une des plus hautes capitales du monde, à plus de 2 000 mètres d’altitude, avec une vieille ville aux immeubles de terre ornés inscrite au patrimoine mondial de l’UNESCO.'),
    city('Peshawar', 'Pakistan', 'PK', 34.0151, 71.5249, 'L’une des plus anciennes villes d’Asie du Sud, ancienne étape sur la route de la soie au pied de la passe de Khyber.'),
    city('Multan', 'Pakistan', 'PK', 30.1575, 71.5249, 'Surnommée la ville des saints pour ses nombreux mausolées soufis.'),
    city('Jaipur', 'Inde', 'IN', 26.9124, 75.7873, 'Surnommée la « ville rose » pour la couleur de ses bâtiments historiques, peints ainsi en 1876 pour accueillir le prince de Galles.'),
    city('Pune', 'Inde', 'IN', 18.5204, 73.8567, 'Ancien bastion de l’empire marathe, elle fut la capitale de facto des Peshwas au XVIIIe siècle.'),
    city('Surat', 'Inde', 'IN', 21.1702, 72.8311, 'Important comptoir commercial dès le XVIe siècle, elle vit s’installer en 1608 le premier établissement de la Compagnie britannique des Indes orientales.'),
    city('Chittagong', 'Bangladesh', 'BD', 22.3569, 91.7832, 'Principal port du Bangladesh, mentionné par des marchands arabes dès le Moyen Âge.'),
    city('Malé', 'Maldives', 'MV', 4.1755, 73.5093, 'L’une des capitales les plus densément peuplées au monde, occupant la quasi-totalité de sa petite île corallienne.'),
    city('Thimphou', 'Bhoutan', 'BT', 27.4728, 89.639, 'Longtemps présentée comme la seule capitale mondiale sans feu de circulation, la régulation y étant assurée par un policier.'),
    city('Ulsan', 'Corée du Sud', 'KR', 35.5384, 129.3114, 'Plus grand centre industriel automobile et naval de Corée du Sud.'),
    city('Incheon', 'Corée du Sud', 'KR', 37.4563, 126.7052, 'Son aéroport international, ouvert en 2001, figure régulièrement parmi les mieux classés au monde.'),
    city('Daegu', 'Corée du Sud', 'KR', 35.8714, 128.6014, 'Quatrième ville de Corée du Sud, ancien grand centre textile du pays.'),
    city('Kaohsiung', 'Taïwan', 'TW', 22.6273, 120.3014, 'Deuxième ville de Taïwan, son port, l’un des plus actifs d’Asie, a porté son développement industriel.'),
    city('Macao', 'Chine', 'CN', 22.1987, 113.5439, 'Ancien comptoir portugais rétrocédé à la Chine le 20 décembre 1999, elle est devenue le plus grand centre mondial de jeux d’argent, devant Las Vegas.'),
    city('Lhassa', 'Chine', 'CN', 29.65, 91.1, 'Son palais du Potala, ancienne résidence des dalaï-lamas culminant à plus de 3 700 mètres d’altitude, est inscrit au patrimoine mondial de l’UNESCO.'),
    city('Tianjin', 'Chine', 'CN', 39.3434, 117.3616, 'Ouverte au commerce international après les guerres de l’opium, elle conserve des quartiers bâtis par d’anciennes concessions étrangères.'),
    city('Qingdao', 'Chine', 'CN', 36.0671, 120.3826, 'Ancienne concession allemande à partir de 1898, elle produit toujours la bière Tsingtao, brassée depuis 1903.'),
    city('Xiamen', 'Chine', 'CN', 24.4798, 118.0894, 'Ancien comptoir connu des Occidentaux sous le nom d’Amoy, ouvert au commerce international après la première guerre de l’opium.'),
    city('Kunming', 'Chine', 'CN', 25.0389, 102.7183, 'Surnommée la « ville du printemps éternel » pour la douceur de son climat toute l’année.'),
    city('Medan', 'Indonésie', 'ID', 3.5952, 98.6722, 'Plus grande ville de l’île de Sumatra, née de l’essor des plantations de tabac à la fin du XIXe siècle.'),
    city('Makassar', 'Indonésie', 'ID', -5.1477, 119.4327, 'Ancien grand carrefour commercial d’Asie du Sud-Est, disputé entre marchands locaux, portugais puis hollandais.'),
    city('Denpasar', 'Indonésie', 'ID', -8.65, 115.2167, 'Chef-lieu de l’île de Bali, dont elle est devenue la principale porte d’entrée touristique.'),
    city('Davao', 'Philippines', 'PH', 7.0731, 125.6128, 'Plus grande ville des Philippines par la superficie, réputée pour ses vergers de durian.'),
    city('Da Nang', 'Viêt Nam', 'VN', 16.0544, 108.2022, 'Premier point de débarquement des troupes françaises en 1858 lors de la conquête coloniale du Viêt Nam.'),
    city('Médine', 'Arabie saoudite', 'SA', 24.5247, 39.5692, 'Deuxième ville sainte de l’islam, où le prophète Mahomet trouva refuge en 622 lors de l’épisode fondateur de l’Hégire.'),
    city('Aden', 'Yémen', 'YE', 12.7855, 45.0187, 'Son port, l’un des plus fréquentés du monde antique, servait d’escale sur la route commerciale entre la Méditerranée et l’Inde.'),
    city('Erbil', 'Irak', 'IQ', 36.191, 44.009, 'Sa citadelle, occupée en continu depuis des millénaires, compte parmi les plus anciens sites habités au monde.'),
    city('Alep', 'Syrie', 'SY', 36.2021, 37.1343, 'L’une des plus anciennes villes continuellement habitées au monde, son immense souk médiéval a été gravement endommagé pendant la guerre civile syrienne.'),
    city('Homs', 'Syrie', 'SY', 34.7324, 36.7137, 'Troisième ville de Syrie, elle a subi d’importantes destructions durant la guerre civile qui a débuté en 2011.'),

    // Amériques
    city('Seattle', 'États-Unis', 'US', 47.6062, -122.3321, 'Berceau de Microsoft, Amazon et Starbucks, tous fondés ou installés dans son agglomération.'),
    city('Dallas', 'États-Unis', 'US', 32.7767, -96.797, 'Le président John F. Kennedy y fut assassiné le 22 novembre 1963.'),
    city('Houston', 'États-Unis', 'US', 29.7604, -95.3698, 'Le centre de contrôle des missions spatiales de la NASA y est installé depuis les années 1960, d’où le mot « Houston » prononcé par Neil Armstrong lors du premier pas sur la Lune.'),
    city('Atlanta', 'États-Unis', 'US', 33.749, -84.388, 'Largement incendiée en 1864 par les troupes du général Sherman pendant la guerre de Sécession.'),
    city('Boston', 'États-Unis', 'US', 42.3601, -71.0589, 'Sa « Tea Party » de 1773, où des colons jetèrent des caisses de thé britannique à la mer, fut l’un des événements déclencheurs de la Révolution américaine.'),
    city('Washington', 'États-Unis', 'US', 38.9072, -77.0369, 'Bâtie sur un site choisi par George Washington lui-même, elle devient capitale fédérale des États-Unis en 1800.'),
    city('Las Vegas', 'États-Unis', 'US', 36.1699, -115.1398, 'Simple bourgade ferroviaire avant que la légalisation des jeux d’argent au Nevada, en 1931, n’en fasse une capitale mondiale du divertissement.'),
    city('Denver', 'États-Unis', 'US', 39.7392, -104.9903, 'Surnommée la « Mile High City » car son capitole se situe exactement à un mile, soit 1 609 mètres, d’altitude.'),
    city('Phoenix', 'États-Unis', 'US', 33.4484, -112.074, 'Bâtie sur d’anciens canaux d’irrigation hohokams, elle doit son nom à sa renaissance sur un site occupé des siècles auparavant.'),
    city('Detroit', 'États-Unis', 'US', 42.3314, -83.0458, 'Ancienne capitale mondiale de l’automobile, surnommée Motor City, où Henry Ford lança la production de masse au début du XXe siècle.'),
    city('Philadelphie', 'États-Unis', 'US', 39.9526, -75.1652, 'La déclaration d’indépendance des États-Unis y fut signée le 4 juillet 1776.'),
    city('Ottawa', 'Canada', 'CA', 45.4215, -75.6972, 'Choisie comme capitale du Canada en 1857 par la reine Victoria, en partie pour sa position entre les populations francophone et anglophone.'),
    city('Calgary', 'Canada', 'CA', 51.0447, -114.0719, 'A accueilli les Jeux olympiques d’hiver de 1988.'),
    city('Edmonton', 'Canada', 'CA', 53.5461, -113.4938, 'Son West Edmonton Mall, ouvert en 1981, fut longtemps le plus grand centre commercial du monde.'),
    city('Québec', 'Canada', 'CA', 46.8139, -71.208, 'Fondée en 1608 par Samuel de Champlain, son centre historique fortifié est le seul en Amérique du Nord au nord du Mexique à avoir conservé ses remparts.'),
    city('Guatemala', 'Guatemala', 'GT', 14.6349, -90.5069, 'Devenue capitale du Guatemala en 1776, après la destruction de l’ancienne capitale Antigua par des séismes.'),
    city('San Salvador', 'Salvador', 'SV', 13.6929, -89.2182, 'Reconstruite à plusieurs reprises après des séismes et éruptions volcaniques dévastateurs, dont celui de 2001.'),
    city('Tegucigalpa', 'Honduras', 'HN', 14.0723, -87.1921, 'Fondée en 1578 autour de mines d’argent, son nom viendrait d’un mot indigène signifiant « colline d’argent ».'),
    city('Managua', 'Nicaragua', 'NI', 12.1364, -86.2514, 'Devenue capitale du Nicaragua en 1852, en remplacement de León, pour apaiser une rivalité de longue date avec Grenade.'),
    city('San José', 'Costa Rica', 'CR', 9.9281, -84.0907, 'Devenue capitale du Costa Rica en 1823, à l’issue d’une brève guerre civile qui l’opposa à Cartago.'),
    city('Saint-Domingue', 'République dominicaine', 'DO', 18.4861, -69.9312, 'Fondée en 1496 par Barthélemy Colomb, frère de Christophe Colomb, c’est la plus ancienne ville fondée par des Européens dans les Amériques.'),
    city('Port-au-Prince', 'Haïti', 'HT', 18.5944, -72.3074, 'Fondée en 1749 par des colons français, elle est la capitale d’Haïti, première République noire indépendante, proclamée en 1804.'),
    city('Kingston', 'Jamaïque', 'JM', 17.9712, -76.7936, 'Fondée en 1692, après la destruction de Port Royal, ancien repaire de pirates, par un séisme.'),
    city('San Juan', 'Porto Rico', 'PR', 18.4655, -66.1057, 'Fondée en 1521, c’est l’une des plus anciennes villes des Amériques établies par les Européens.'),
    city('Guayaquil', 'Équateur', 'EC', -2.1894, -79.889, 'Principal port et plus grande ville de l’Équateur, bien que ce ne soit pas la capitale politique du pays.'),
    city('Medellín', 'Colombie', 'CO', 6.2442, -75.5812, 'Autrefois associée au narcotrafic dans les années 1980-1990, elle est aujourd’hui souvent citée en exemple pour sa transformation urbaine.'),
    city('Montevideo', 'Uruguay', 'UY', -34.9011, -56.1645, 'Fondée par les Espagnols au XVIIIe siècle pour contrer l’expansion portugaise depuis le Brésil voisin.'),
    city('Asunción', 'Paraguay', 'PY', -25.2637, -57.5759, 'Fondée en 1537, c’est l’une des plus anciennes villes d’Amérique du Sud et l’ancienne capitale de la province espagnole du Río de la Plata.'),
    city('Brasília', 'Brésil', 'BR', -15.7939, -47.8828, 'Bâtie de toutes pièces à partir de 1956 et inaugurée en 1960, son plan urbain en forme d’avion est inscrit au patrimoine mondial de l’UNESCO.'),
    city('Salvador de Bahia', 'Brésil', 'BR', -12.9714, -38.5014, 'Première capitale du Brésil colonial, de 1549 à 1763, avant le transfert vers Rio de Janeiro.'),
    city('Puebla', 'Mexique', 'MX', 19.0414, -98.2063, 'Sa bataille du 5 mai 1862 contre les troupes françaises est commémorée chaque année sous le nom de Cinco de Mayo.'),
    city('Tijuana', 'Mexique', 'MX', 32.5149, -117.0382, 'Ville frontalière parmi les plus fréquentées au monde, au contact direct de San Diego.'),
    city('Mendoza', 'Argentine', 'AR', -32.8895, -68.8458, 'Cœur du vignoble argentin, elle a été reconstruite après un séisme dévastateur en 1861.'),
    city('Belém', 'Brésil', 'BR', -1.4558, -48.4902, 'Fondée en 1616 à l’embouchure de l’Amazone, elle fut la porte d’entrée du commerce du caoutchouc à la fin du XIXe siècle.'),
    city('Manaus', 'Brésil', 'BR', -3.119, -60.0217, 'Prospéra grâce au boom du caoutchouc à la fin du XIXe siècle, période durant laquelle fut construit son opulent opéra, le Teatro Amazonas, inauguré en 1896.'),
    city('Barranquilla', 'Colombie', 'CO', 10.9639, -74.7964, 'Principal port fluvial de Colombie sur le fleuve Magdalena, réputée pour son carnaval inscrit au patrimoine immatériel de l’UNESCO.'),
    city('Maracaibo', 'Venezuela', 'VE', 10.6427, -71.6125, 'Sur les rives du lac du même nom, elle est au cœur de la principale région pétrolière du Venezuela.'),
    city('Cusco', 'Pérou', 'PE', -13.5319, -71.9675, 'Ancienne capitale de l’empire inca, son centre historique est inscrit au patrimoine mondial de l’UNESCO depuis 1983.'),
    city('Trujillo', 'Pérou', 'PE', -8.1116, -79.0288, 'Fondée en 1534 par Francisco Pizarro, qui lui donna le nom de sa ville natale espagnole.'),
    city('Concepción', 'Chili', 'CL', -36.8269, -73.0503, 'Fondée en 1550, elle a été détruite et reconstruite à plusieurs reprises à cause de séismes et de tsunamis, dont celui de 2010.'),
    city('Santa Cruz de la Sierra', 'Bolivie', 'BO', -17.7833, -63.1821, 'Fondée en 1561, elle est devenue la ville la plus peuplée de Bolivie, dépassant la capitale administrative La Paz.'),
    city('Winnipeg', 'Canada', 'CA', 49.8951, -97.1384, 'Située au confluent des rivières Rouge et Assiniboine, un site fréquenté par les peuples autochtones bien avant la colonisation.'),
    city('Halifax', 'Canada', 'CA', 44.6488, -63.5752, 'Son port fut le théâtre en 1917 de l’une des plus grandes explosions accidentelles d’origine humaine avant l’ère nucléaire, causée par la collision de deux navires.'),
    city('Saskatoon', 'Canada', 'CA', 52.1332, -106.67, 'Fondée en 1882 par une coopérative prônant la tempérance et l’interdiction de l’alcool, un projet finalement abandonné.'),
    city('Regina', 'Canada', 'CA', 50.4452, -104.6189, 'Devenue capitale de la Saskatchewan en 1906, elle doit son nom à la reine Victoria.'),
    city('Victoria', 'Canada', 'CA', 48.4284, -123.3656, 'Capitale de la Colombie-Britannique, elle doit son nom à la reine Victoria et jouit d’un climat parmi les plus doux du Canada.'),
    city('St. John’s', 'Canada', 'CA', 47.5615, -52.7126, 'L’une des plus anciennes villes fondées par des Européens en Amérique du Nord, avec une présence attestée dès le XVIe siècle.'),
    city('Nashville', 'États-Unis', 'US', 36.1627, -86.7816, 'Surnommée « Music City » pour son rôle historique de capitale de la musique country.'),
    city('Memphis', 'États-Unis', 'US', 35.1495, -90.049, 'Le pasteur Martin Luther King Jr y fut assassiné le 4 avril 1968.'),
    city('Raleigh', 'États-Unis', 'US', 35.7796, -78.6382, 'Nommée en l’honneur de l’explorateur anglais Walter Raleigh, elle fut fondée en 1792 spécifiquement pour devenir la capitale de la Caroline du Nord.'),
    city('Kansas City', 'États-Unis', 'US', 39.0997, -94.5786, 'Traversée par la rivière du même nom, elle est en réalité scindée entre les États du Missouri et du Kansas.'),
    city('Pittsburgh', 'États-Unis', 'US', 40.4406, -79.9959, 'Ancienne capitale mondiale de l’acier, elle a profondément reconverti son économie vers la technologie et la santé après le déclin industriel de la fin du XXe siècle.'),
    city('Cincinnati', 'États-Unis', 'US', 39.1031, -84.512, 'Surnommée « Porkopolis » au XIXe siècle pour son importante industrie d’abattage porcin.'),
    city('Milwaukee', 'États-Unis', 'US', 43.0389, -87.9065, 'Ancien grand centre brassicole des États-Unis, porté par une forte immigration allemande au XIXe siècle.'),
    city('Salt Lake City', 'États-Unis', 'US', 40.7608, -111.891, 'Fondée en 1847 par Brigham Young et ses adeptes mormons venus s’installer près du Grand Lac Salé.'),
    city('Albuquerque', 'États-Unis', 'US', 35.0844, -106.6504, 'Fondée en 1706, elle doit son nom à un vice-roi espagnol de Nouvelle-Espagne, duc d’Alburquerque.'),
    city('Omaha', 'États-Unis', 'US', 41.2565, -95.9345, 'Ancien point de passage de la piste de l’Oregon empruntée par les pionniers au XIXe siècle.'),

    // Océanie
    city('Brisbane', 'Australie', 'AU', -27.4698, 153.0251, 'A accueilli les Jeux du Commonwealth de 1982 et accueillera les Jeux olympiques d’été de 2032.'),
    city('Adelaide', 'Australie', 'AU', -34.9285, 138.6007, 'Fondée en 1836 comme colonie planifiée, seule capitale d’État australienne à n’avoir jamais été un bagne pénitentiaire.'),
    city('Canberra', 'Australie', 'AU', -35.2809, 149.13, 'Choisie comme capitale fédérale de l’Australie en 1908, à mi-chemin entre les rivales Sydney et Melbourne.'),
    city('Hobart', 'Australie', 'AU', -42.8821, 147.3272, 'Fondée en 1804, c’est la deuxième plus ancienne capitale d’État australienne après Sydney.'),
    city('Darwin', 'Australie', 'AU', -12.4634, 130.8456, 'Frappée par un raid aérien japonais le 19 février 1942, le plus meurtrier subi par l’Australie pendant la Seconde Guerre mondiale.'),
    city('Christchurch', 'Nouvelle-Zélande', 'NZ', -43.5321, 172.6362, 'Sévèrement endommagée par un séisme le 22 février 2011, qui a fait 185 morts et détruit une grande partie de son centre-ville.'),
    city('Suva', 'Fidji', 'FJ', -18.1416, 178.4419, 'Capitale des Fidji depuis 1877, elle compte parmi les villes les plus arrosées du Pacifique Sud.'),
    city('Port Moresby', 'Papouasie-Nouvelle-Guinée', 'PG', -9.4438, 147.1803, 'Capitale de la Papouasie-Nouvelle-Guinée, nommée en l’honneur du capitaine britannique John Moresby, qui explora sa baie en 1873.'),
    city('Apia', 'Samoa', 'WS', -13.8506, -171.7513, 'L’écrivain écossais Robert Louis Stevenson y passa les dernières années de sa vie et y est enterré.'),
    city('Nadi', 'Fidji', 'FJ', -17.8033, 177.4148, 'Principale porte d’entrée aérienne des Fidji, bien que ce ne soit pas la capitale du pays.'),
  ]),

  ...master([
    city('Aurillac', 'France', 'FR', 44.9297, 2.4436, 'Ville natale de Gerbert d’Aurillac, devenu en 999 le pape Sylvestre II, premier pape français de l’histoire.'),
    city('Épinal', 'France', 'FR', 48.1667, 6.45, 'A donné son nom aux « images d’Épinal », ces gravures populaires imprimées dès la fin du XVIIIe siècle par la manufacture Pellerin.'),
    city('Minsk', 'Biélorussie', 'BY', 53.9006, 27.559, 'Détruite à environ 80 % pendant la Seconde Guerre mondiale, elle a été presque entièrement reconstruite selon un urbanisme soviétique monumental.'),
    city('Chisinau', 'Moldavie', 'MD', 47.0105, 28.8638, 'Capitale de la Moldavie, largement reconstruite après les destructions subies pendant la Seconde Guerre mondiale.'),
    city('La Valette', 'Malte', 'MT', 35.8989, 14.5146, 'Fondée en 1566 par les chevaliers de l’ordre de Saint-Jean, au lendemain du grand siège ottoman de 1565.'),
    city('Nicosie', 'Chypre', 'CY', 35.1856, 33.3823, 'Seule capitale au monde divisée par une frontière depuis 1974, séparant les parties chypriote grecque et chypriote turque.'),
    city('Andorre-la-Vieille', 'Andorre', 'AD', 42.5063, 1.5218, 'Plus haute capitale d’Europe, à plus de 1 000 mètres d’altitude, dans une principauté co-dirigée par un évêque espagnol et le président français.'),
    city('Vaduz', 'Liechtenstein', 'LI', 47.141, 9.5209, 'Dominée par un château toujours habité par la famille princière régnante du Liechtenstein.'),
    city('Saint-Marin', 'Saint-Marin', 'SM', 43.9424, 12.4578, 'L’une des plus anciennes républiques encore existantes au monde, fondée selon la tradition en 301 par un tailleur de pierre chrétien.'),
    city('Monaco', 'Monaco', 'MC', 43.7384, 7.4246, 'Deuxième plus petit État du monde après le Vatican, dirigé par la famille Grimaldi depuis la fin du XIIIe siècle.'),
    city('Luxembourg-ville', 'Luxembourg', 'LU', 49.6116, 6.1319, 'Sa vieille ville et ses fortifications, surnommées le « Gibraltar du Nord », sont inscrites au patrimoine mondial de l’UNESCO.'),
    city('N’Djamena', 'Tchad', 'TD', 12.1348, 15.0557, 'Fondée en 1900 par les Français sous le nom de Fort-Lamy, elle prend son nom actuel en 1973.'),
    city('Djibouti-ville', 'Djibouti', 'DJ', 11.5721, 43.1456, 'Fondée en 1888 par les Français, elle concentre l’essentiel de la population du petit pays dont elle est la capitale.'),
    city('Asmara', 'Érythrée', 'ER', 15.3229, 38.925, 'Ses nombreux bâtiments Art déco et modernistes construits sous la colonisation italienne des années 1930 sont inscrits au patrimoine mondial de l’UNESCO.'),
    city('Mogadiscio', 'Somalie', 'SO', 2.0469, 45.3182, 'Ancien comptoir swahili fréquenté dès le Moyen Âge par des marchands arabes et persans.'),
    city('Djouba', 'Soudan du Sud', 'SS', 4.8594, 31.5713, 'Devenue capitale du Soudan du Sud à son indépendance en 2011, le plus jeune État reconnu au monde.'),
    city('Bissau', 'Guinée-Bissau', 'GW', 11.8636, -15.5977, 'Capitale de la Guinée-Bissau, son vieux fort colonial portugais domine toujours l’entrée du port.'),
    city('Conakry', 'Guinée', 'GN', 9.6412, -13.5784, 'Bâtie en grande partie sur l’île de Tombo, reliée au continent par une chaussée.'),
    city('Freetown', 'Sierra Leone', 'SL', 8.484, -13.2299, 'Fondée en 1792 par des esclaves affranchis venus de Grande-Bretagne et de Nouvelle-Écosse, d’où son nom qui signifie « ville libre ».'),
    city('Monrovia', 'Liberia', 'LR', 6.3156, -10.8074, 'Fondée en 1822 par des esclaves affranchis américains, elle doit son nom au président américain James Monroe.'),
    city('Lomé', 'Togo', 'TG', 6.1725, 1.2314, 'Capitale du Togo, longtemps surnommée le « petit Paris de l’Afrique de l’Ouest » pour son animation.'),
    city('Cotonou', 'Bénin', 'BJ', 6.3703, 2.3912, 'Plus grande ville du Bénin et son principal port, bien que la capitale officielle du pays soit Porto-Novo.'),
    city('Malabo', 'Guinée équatoriale', 'GQ', 3.75, 8.7833, 'Capitale de la Guinée équatoriale, seul pays d’Afrique où l’espagnol est langue officielle.'),
    city('São Tomé', 'Sao Tomé-et-Principe', 'ST', 0.3365, 6.7273, 'Capitale du petit archipel de Sao Tomé-et-Principe, situé à quelques kilomètres seulement de l’équateur.'),
    city('Praia', 'Cap-Vert', 'CV', 14.933, -23.5133, 'Capitale de l’archipel volcanique du Cap-Vert, colonisé par les Portugais dès le XVe siècle.'),
    city('Moroni', 'Comores', 'KM', -11.7022, 43.2551, 'Capitale des Comores, bâtie au pied d’un volcan actif, le Karthala.'),
    city('Victoria', 'Seychelles', 'SC', -4.6191, 55.4513, 'L’une des plus petites capitales nationales au monde, sur l’île de Mahé.'),
    city('Port-Louis', 'Maurice', 'MU', -20.1609, 57.5012, 'Capitale de l’île Maurice, fondée par les Français au XVIIIe siècle sous le gouverneur Mahé de La Bourdonnais.'),
    city('Mbabane', 'Eswatini', 'SZ', -26.3054, 31.1367, 'Capitale administrative de l’Eswatini, pays rebaptisé en 2018 par le roi Mswati III, qui portait auparavant le nom de Swaziland.'),
    city('Maseru', 'Lesotho', 'LS', -29.31, 27.4833, 'Capitale du Lesotho, seul pays au monde entièrement situé à plus de 1 000 mètres d’altitude.'),
    city('Banjul', 'Gambie', 'GM', 13.4549, -16.579, 'Capitale de la Gambie, bâtie sur une petite île à l’embouchure du fleuve du même nom.'),
    city('Ciudad del Este', 'Paraguay', 'PY', -25.5167, -54.6167, 'Deuxième ville du Paraguay, née dans les années 1950 près du grand barrage hydroélectrique d’Itaipú.'),
    city('Punta del Este', 'Uruguay', 'UY', -34.9667, -54.95, 'Station balnéaire réputée d’Uruguay, souvent présentée comme le Saint-Tropez sud-américain.'),
    city('Basseterre', 'Saint-Kitts-et-Nevis', 'KN', 17.3026, -62.7177, 'Capitale du plus petit État indépendant des Amériques par la population.'),
    city('Castries', 'Sainte-Lucie', 'LC', 14.0101, -60.9875, 'Capitale de Sainte-Lucie, nommée en l’honneur d’un ministre de la Marine français du XVIIIe siècle, le maréchal de Castries.'),
    city('Roseau', 'Dominique', 'DM', 15.3092, -61.379, 'Capitale de la Dominique, île réputée pour ses forêts tropicales préservées et son faible tourisme de masse.'),
    city('Saint-Georges', 'Grenade', 'GD', 12.0561, -61.7488, 'Capitale de la Grenade, île surnommée l’« île aux épices » pour sa production de muscade.'),
    city('Bridgetown', 'Barbade', 'BB', 13.0969, -59.6145, 'Son centre historique et son ancienne garnison militaire sont inscrits au patrimoine mondial de l’UNESCO.'),
    city('Nassau', 'Bahamas', 'BS', 25.0343, -77.3963, 'Ancien repaire de pirates au début du XVIIIe siècle, avant que les autorités britanniques n’y rétablissent l’ordre.'),
    city('Belmopan', 'Belize', 'BZ', 17.251, -88.759, 'Devenue capitale du Belize en 1970, en remplacement de Belize City, dévastée par un ouragan en 1961.'),
    city('Georgetown', 'Guyana', 'GY', 6.8013, -58.1553, 'Capitale du Guyana, ses nombreux canaux de drainage témoignent de son passé de colonie hollandaise.'),
    city('Paramaribo', 'Suriname', 'SR', 5.852, -55.2038, 'Son centre historique aux bâtiments de bois hérités de la colonisation hollandaise est inscrit au patrimoine mondial de l’UNESCO.'),
    city('Cayenne', 'Guyane française', 'GF', 4.9346, -52.3303, 'Chef-lieu de la Guyane française, longtemps associé au bagne pénitentiaire voisin de l’île du Diable.'),
    city('Fort-de-France', 'Martinique', 'MQ', 14.6161, -61.0588, 'Chef-lieu de la Martinique, rebaptisé au XIXe siècle d’après le fort qui protège sa baie.'),
    city('Pointe-à-Pitre', 'Guadeloupe', 'GP', 16.2415, -61.5333, 'Principale ville économique de la Guadeloupe, bien que Basse-Terre en soit le chef-lieu administratif.'),
    city('Willemstad', 'Curaçao', 'CW', 12.1084, -68.9335, 'Ses façades colorées héritées de l’architecture coloniale hollandaise sont inscrites au patrimoine mondial de l’UNESCO.'),
    city('Oranjestad', 'Aruba', 'AW', 12.5246, -70.027, 'Capitale d’Aruba, nommée en l’honneur de la famille royale néerlandaise d’Orange-Nassau.'),
    city('George Town', 'Îles Caïmans', 'KY', 19.2869, -81.3674, 'Capitale des îles Caïmans, territoire britannique devenu un grand centre financier offshore.'),
    city('Nuku’alofa', 'Tonga', 'TO', -21.1394, -175.2049, 'Capitale des Tonga, seule monarchie du Pacifique à n’avoir jamais été formellement colonisée.'),
    city('Port Vila', 'Vanuatu', 'VU', -17.7333, 168.3167, 'Capitale du Vanuatu, archipel administré conjointement par la France et le Royaume-Uni jusqu’à son indépendance en 1980.'),
    city('Honiara', 'Îles Salomon', 'SB', -9.4438, 159.9498, 'Développée par les forces américaines autour de l’aérodrome de Guadalcanal pendant la Seconde Guerre mondiale.'),
    city('Majuro', 'Îles Marshall', 'MH', 7.1164, 171.1858, 'Capitale des îles Marshall, atoll corallien qui ne s’élève que de quelques mètres au-dessus du niveau de la mer.'),
    city('Funafuti', 'Tuvalu', 'TV', -8.5199, 179.1959, 'Capitale de Tuvalu, l’un des pays les plus menacés au monde par la montée du niveau des mers.'),
    city('Tarawa', 'Kiribati', 'KI', 1.3291, 172.9791, 'Cet atoll fut le théâtre d’une bataille meurtrière entre forces américaines et japonaises en novembre 1943.'),
    city('Palikir', 'Micronésie', 'FM', 6.9248, 158.161, 'Capitale des États fédérés de Micronésie, choisie dans les années 1980 en remplacement de Kolonia.'),
    city('Ngerulmud', 'Palaos', 'PW', 7.5, 134.6242, 'Capitale des Palaos depuis 2006, l’une des plus petites capitales du monde par la population, construite pour remplacer Koror.'),
    city('Pago Pago', 'Samoa américaines', 'AS', -14.2781, -170.7025, 'Chef-lieu des Samoa américaines, territoire non incorporé des États-Unis dans le Pacifique Sud.'),
  ]),
];
