import type { Place } from '@/types';

import { placeFactory, tier } from './helpers';

const landmark = placeFactory('landmarks');
const easy = tier('easy');
const intermediate = tier('intermediate');
const hard = tier('hard');
const master = tier('master');

export const LANDMARKS: Place[] = [
  ...easy([
    landmark(
      'Tour Eiffel',
      'FR',
      48.8584,
      2.2945,
      'Elle est restée la plus haute construction du monde pendant 41 ans, jusqu’à l’achèvement du Chrysler Building à New York en 1930.',
      'Tour_Eiffel',
      'Eiffel_Tower',
    ),
    landmark(
      'Arc de Triomphe',
      'FR',
      48.8738,
      2.295,
      'Commandé par Napoléon en 1806 après Austerlitz, il n’a été inauguré qu’en 1836, sous le roi Louis-Philippe.',
      "Arc_de_triomphe_de_l'Étoile",
      'Arc_de_Triomphe',
    ),
    landmark(
      'Musée du Louvre',
      'FR',
      48.8606,
      2.3376,
      'Ouvert au public le 10 août 1793, pendant la Révolution française, pour l’anniversaire de la chute de la monarchie.',
      'Musée_du_Louvre',
      'Louvre',
    ),
    landmark(
      'Notre-Dame de Paris',
      'FR',
      48.853,
      2.3499,
      'Sa flèche et sa charpente ont été détruites par un incendie le 15 avril 2019.',
      'Notre-Dame_de_Paris',
      'Notre-Dame_de_Paris',
    ),
    landmark(
      'Sacré-Cœur',
      'FR',
      48.8867,
      2.3431,
      'Sa cloche, la Savoyarde, coulée à Annecy en 1895, pèse plus de 18 tonnes et reste la plus grosse cloche de France.',
      'Basilique_du_Sacré-Cœur_de_Montmartre',
      'Sacré-Cœur,_Paris',
    ),
    landmark(
      'Château de Versailles',
      'FR',
      48.8049,
      2.1204,
      'La cour et le gouvernement royal y résidèrent en permanence du 6 mai 1682 au 6 octobre 1789.',
      'Château_de_Versailles',
      'Palace_of_Versailles',
    ),
    landmark(
      'Mont-Saint-Michel',
      'FR',
      48.6361,
      -1.5115,
      'Inscrit au patrimoine mondial de l’UNESCO en 1979, c’est le site le plus visité de France en dehors de Paris.',
      'Mont-Saint-Michel',
      'Mont-Saint-Michel',
    ),
    landmark(
      'Pyramides de Gizeh',
      'EG',
      29.9792,
      31.1342,
      'La grande pyramide de Khéops est restée la plus haute construction humaine pendant près de 3 800 ans, jusqu’aux cathédrales gothiques du Moyen Âge.',
      'Pyramides_de_Gizeh',
      'Giza_pyramid_complex',
    ),
    landmark(
      'Colisée',
      'IT',
      41.8902,
      12.4922,
      'Construit entre 72 et 80 apr. J.-C. sous les empereurs Vespasien et Titus, il pouvait accueillir environ 65 000 spectateurs.',
      'Colisée',
      'Colosseum',
    ),
    landmark(
      'Tour de Pise',
      'IT',
      43.723,
      10.3966,
      'Sa construction a débuté en 1173 ; son inclinaison a été réduite lors de travaux de stabilisation entre 1993 et 2001, qui ont retiré 70 tonnes de terre sous le côté surélevé.',
      'Tour_de_Pise',
      'Leaning_Tower_of_Pisa',
    ),
    landmark(
      'Big Ben',
      'GB',
      51.5007,
      -0.1246,
      'La grosse cloche, coulée en 1858 et installée en 1859, s’est fissurée deux mois après sa mise en service, ce qui explique sa sonorité si particulière.',
      'Big_Ben',
      'Big_Ben',
    ),
    landmark(
      'Stonehenge',
      'GB',
      51.1789,
      -1.8262,
      'Ses plus grosses pierres, les sarsens, ont été transportées sur près de 40 km depuis les Marlborough Downs, lors de travaux étalés sur plusieurs siècles autour de 2500 av. J.-C.',
      'Stonehenge',
      'Stonehenge',
    ),
    landmark(
      'Taj Mahal',
      'IN',
      27.1751,
      78.0421,
      'Fait construire par l’empereur moghol Shah Jahan à la mémoire de son épouse Mumtaz Mahal, il fut achevé vers 1648.',
      'Taj_Mahal',
      'Taj_Mahal',
    ),
    landmark(
      'Grande Muraille (Badaling)',
      'CN',
      40.3599,
      116.0204,
      'La Grande Muraille comptait environ 25 000 tours de guet construites au fil des dynasties pour surveiller la frontière nord de la Chine.',
      'Grande_Muraille',
      'Badaling',
    ),
    landmark(
      'Cité interdite',
      'CN',
      39.9163,
      116.3972,
      'Bâtie entre 1406 et 1420 sous l’empereur Yongle, elle a mobilisé plus d’un million d’ouvriers.',
      'Cité_interdite',
      'Forbidden_City',
    ),
    landmark(
      'Machu Picchu',
      'PE',
      -13.1631,
      -72.545,
      'Resté inconnu du monde extérieur, le site a été révélé internationalement en 1911 par l’archéologue américain Hiram Bingham, guidé par des habitants qui en connaissaient déjà l’existence.',
      'Machu_Picchu',
      'Machu_Picchu',
    ),
    landmark(
      'Christ Rédempteur',
      'BR',
      -22.9519,
      -43.2105,
      'Inaugurée le 12 octobre 1931 après cinq ans de travaux, la statue mesure 38 m avec son socle.',
      'Statue_du_Christ_Rédempteur',
      'Christ_the_Redeemer_(statue)',
    ),
    landmark(
      'Statue de la Liberté',
      'US',
      40.6892,
      -74.0445,
      'Inaugurée le 28 octobre 1886 en présence du président Grover Cleveland, un cadeau de la France pour le centenaire de l’indépendance américaine.',
      'Statue_de_la_Liberté',
      'Statue_of_Liberty',
    ),
    landmark(
      'Empire State Building',
      'US',
      40.7484,
      -73.9857,
      'Construit en seulement 410 jours, il a ouvert ses portes le 1er mai 1931.',
      'Empire_State_Building',
      'Empire_State_Building',
    ),
    landmark(
      'Golden Gate Bridge',
      'US',
      37.8199,
      -122.4783,
      'Ouvert à la circulation le 27 mai 1937, il doit sa célèbre couleur orange au choix de l’architecte Irving Morrow, qui a préféré cette teinte au gris acier ou à l’aluminium.',
      'Golden_Gate_Bridge',
      'Golden_Gate_Bridge',
    ),
    landmark(
      'Mont Rushmore',
      'US',
      43.8791,
      -103.4591,
      'Les quatre visages présidentiels, hauts de 18 m chacun, ont été sculptés entre 1927 et 1941 sous la direction de Gutzon Borglum.',
      'Mont_Rushmore',
      'Mount_Rushmore',
    ),
    landmark(
      'Opéra de Sydney',
      'AU',
      -33.8568,
      151.2153,
      'Inauguré le 20 octobre 1973 par la reine Élisabeth II, seize ans après que l’architecte danois Jørn Utzon a remporté le concours international de 1957.',
      'Opéra_de_Sydney',
      'Sydney_Opera_House',
    ),
    landmark(
      'Angkor Vat',
      'KH',
      13.4125,
      103.867,
      'Construit au XIIe siècle sous le roi Suryavarman II, c’est le seul édifice au monde représenté sur le drapeau national d’un pays, le Cambodge.',
      'Angkor_Vat',
      'Angkor_Wat',
    ),
    landmark(
      'Pétra',
      'JO',
      30.3285,
      35.4444,
      'Oubliée du monde occidental, la cité nabatéenne n’a été redécouverte qu’en 1812 par l’explorateur suisse Johann Ludwig Burckhardt, déguisé en voyageur local.',
      'Pétra',
      'Petra',
    ),
    landmark(
      'Chichén Itzá',
      'MX',
      20.6843,
      -88.5678,
      'La pyramide de Kukulcán a été élue le 7 juillet 2007 l’une des sept nouvelles merveilles du monde, à l’issue d’un vote international.',
      'Chichén_Itzá',
      'Chichen_Itza',
    ),
    landmark(
      'Acropole d’Athènes',
      'GR',
      37.9715,
      23.7257,
      'Le Parthénon, utilisé comme poudrière par les Ottomans, a été gravement endommagé le 26 septembre 1687 par un bombardement vénitien.',
      "Acropole_d'Athènes",
      'Acropolis_of_Athens',
    ),
    landmark(
      'Sagrada Família',
      'ES',
      41.4036,
      2.1744,
      'Sa construction, commencée en 1882 sous la direction d’Antoni Gaudí, se poursuit encore aujourd’hui, plus de 140 ans plus tard.',
      'Sagrada_Família',
      'Sagrada_Família',
    ),
    landmark(
      'Alhambra',
      'ES',
      37.1761,
      -3.5881,
      'Sa construction débute en 1238 sous les Nasrides, mais l’essentiel du palais actuel date du XIVe siècle, sous les règnes de Yusuf Ier et Mohammed V.',
      'Alhambra',
      'Alhambra',
    ),
    landmark(
      'Burj Khalifa',
      'AE',
      25.1972,
      55.2744,
      'Son ascenseur le plus rapide atteint 11 m/s, soit 40 km/h, en montée comme en descente.',
      'Burj_Khalifa',
      'Burj_Khalifa',
    ),
    landmark(
      'Place Rouge',
      'RU',
      55.7539,
      37.6208,
      'Son nom ne vient pas du communisme : en vieux russe, « krasny » signifiait à la fois « rouge » et « beau ».',
      'Place_Rouge',
      'Red_Square',
    ),
    landmark(
      'Château de Neuschwanstein',
      'DE',
      47.5576,
      10.7498,
      'Sa construction commence en 1869 pour le roi Louis II de Bavière, mort en 1886 sans avoir habité le château plus de 172 jours au total.',
      'Château_de_Neuschwanstein',
      'Neuschwanstein_Castle',
    ),
    landmark(
      'Porte de Brandebourg',
      'DE',
      52.5163,
      13.3777,
      'Napoléon a emporté le quadrige qui la surmonte à Paris en 1806 après sa victoire sur la Prusse ; il n’a été rendu à Berlin qu’en 1814, après sa propre défaite.',
      'Porte_de_Brandebourg',
      'Brandenburg_Gate',
    ),
    landmark(
      'Sainte-Sophie',
      'TR',
      41.0086,
      28.9802,
      'Construite en seulement 5 ans et 10 mois, elle est inaugurée par l’empereur Justinien le 27 décembre 537.',
      'Sainte-Sophie_de_Constantinople',
      'Hagia_Sophia',
    ),
    landmark(
      'Tour de Londres',
      'GB',
      51.5081,
      -0.0759,
      'Sa Tour Blanche, qui a donné son nom à l’ensemble de la forteresse, a été édifiée à partir de 1078 sur ordre de Guillaume le Conquérant.',
      'Tour_de_Londres',
      'Tower_of_London',
    ),
    landmark(
      'Buckingham Palace',
      'GB',
      51.5014,
      -0.1419,
      'Acheté par le roi George III en 1761, le bâtiment n’est devenu la résidence officielle des souverains britanniques qu’en 1837, à l’avènement de la reine Victoria.',
      'Palais_de_Buckingham',
      'Buckingham_Palace',
    ),
    landmark(
      'Mosquée bleue',
      'TR',
      41.0054,
      28.9768,
      'Construite entre 1609 et 1616 sous le sultan Ahmed Ier, elle est l’une des rares mosquées au monde à compter six minarets.',
      'Mosquée_bleue',
      'Blue_Mosque,_Istanbul',
    ),
    landmark(
      'Alcatraz',
      'US',
      37.8267,
      -122.423,
      'Dans la nuit du 11 juin 1962, trois détenus s’en sont évadés par les bouches d’aération sur un radeau de fortune ; on ne les a jamais retrouvés.',
      'Alcatraz',
      'Alcatraz_Island',
    ),
    landmark(
      'Cathédrale Saint-Basile',
      'RU',
      55.7525,
      37.6231,
      'Construite entre 1555 et 1561 sur ordre d’Ivan le Terrible pour célébrer la prise de Kazan, elle compte neuf bulbes distincts.',
      'Cathédrale_Saint-Basile-le-Bienheureux_de_Moscou',
      "Saint_Basil's_Cathedral",
    ),
    landmark(
      'Petronas Towers',
      'MY',
      3.1579,
      101.7116,
      'Plus haut gratte-ciel du monde de leur achèvement en 1998 jusqu’en 2004, année où le Taipei 101 les a dépassées.',
      'Petronas_Twin_Towers',
      'Petronas_Towers',
    ),
  ]),

  ...intermediate([
    landmark(
      'Pont du Gard',
      'FR',
      43.9475,
      4.5355,
      'Ce pont-aqueduc romain, construit au Ier siècle apr. J.-C., acheminait l’eau sur près de 50 km jusqu’à la ville de Nîmes.',
      'Pont_du_Gard',
      'Pont_du_Gard',
    ),
    landmark(
      'Cité de Carcassonne',
      'FR',
      43.2064,
      2.3639,
      'Restaurée à partir de 1853 par l’architecte Eugène Viollet-le-Duc, c’est la plus grande cité médiévale fortifiée d’Europe.',
      'Cité_de_Carcassonne',
      'Carcassonne',
    ),
    landmark(
      'Château de Chambord',
      'FR',
      47.6161,
      1.517,
      'Sa construction commence en 1519 pour François Ier ; son escalier à double révolution s’inspire des travaux de Léonard de Vinci, mort la même année.',
      'Château_de_Chambord',
      'Château_de_Chambord',
    ),
    landmark(
      'Château de Chenonceau',
      'FR',
      47.3249,
      1.0702,
      'Bâti sur le Cher, il doit son surnom de « château des Dames » à Diane de Poitiers puis Catherine de Médicis, qui se le disputèrent au XVIe siècle.',
      'Château_de_Chenonceau',
      'Château_de_Chenonceau',
    ),
    landmark(
      'Palais des Papes',
      'FR',
      43.9508,
      4.8074,
      'Résidence des papes durant leur exil à Avignon entre 1309 et 1377, c’est le plus grand palais gothique d’Europe.',
      "Palais_des_papes_d'Avignon",
      'Palace_of_the_Popes',
    ),
    landmark(
      'Viaduc de Millau',
      'FR',
      44.0778,
      3.0224,
      'Inauguré en 2004, l’un de ses piliers culmine à 343 m, soit plus haut que la tour Eiffel.',
      'Viaduc_de_Millau',
      'Millau_Viaduct',
    ),
    landmark(
      'Grotte de Lascaux',
      'FR',
      45.0538,
      1.1671,
      'Découverte en 1940 par quatre adolescents partis à la recherche de leur chien, la grotte a été fermée au public dès 1963 pour préserver ses peintures.',
      'Grotte_de_Lascaux',
      'Lascaux',
    ),
    landmark(
      'Puy du Fou',
      'FR',
      46.8896,
      -1.1247,
      'Créé par Philippe de Villiers, le parc a débuté en 1978 avec la Cinéscénie, un spectacle nocturne joué par des milliers de bénévoles.',
      'Puy_du_Fou',
      'Puy_du_Fou',
    ),
    landmark(
      'Sanctuaires de Lourdes',
      'FR',
      43.0979,
      -0.0578,
      'En 1858, une jeune bergère, Bernadette Soubirous, y affirme avoir eu dix-huit apparitions de la Vierge Marie, faisant de Lourdes l’un des plus grands lieux de pèlerinage catholique.',
      'Sanctuaire_Notre-Dame_de_Lourdes',
      'Sanctuary_of_Our_Lady_of_Lourdes',
    ),
    landmark(
      'Cathédrale de Strasbourg',
      'FR',
      48.5819,
      7.7509,
      'Achevée en 1439, sa flèche unique en fit le plus haut édifice du monde de 1647 à 1874.',
      'Cathédrale_Notre-Dame_de_Strasbourg',
      'Strasbourg_Cathedral',
    ),
    landmark(
      'Cathédrale de Chartres',
      'FR',
      48.4476,
      1.4879,
      'Reconstruite en un peu moins de trente ans après l’incendie de 1194, elle est célèbre pour son bleu de vitrail resté inimité.',
      'Cathédrale_Notre-Dame_de_Chartres',
      'Chartres_Cathedral',
    ),
    landmark(
      'Abou Simbel',
      'EG',
      22.3372,
      31.6258,
      'Ses temples ont été découpés en blocs et déplacés 65 m plus haut entre 1964 et 1968 pour échapper à la montée des eaux du lac Nasser.',
      'Abou_Simbel',
      'Abu_Simbel_temples',
    ),
    landmark(
      'Temple d’Or d’Amritsar',
      'IN',
      31.62,
      74.8765,
      'Ce temple sikh, le plus sacré de cette religion, doit son surnom de Temple d’Or à son dôme doré, offert au XIXe siècle par le maharaja Ranjit Singh.',
      'Harmandir_Sahib',
      'Golden_Temple',
    ),
    landmark(
      'Atomium',
      'BE',
      50.8949,
      4.3415,
      'Construit pour l’Exposition universelle de 1958, il représente une maille de fer cristallisé agrandie 165 milliards de fois.',
      'Atomium',
      'Atomium',
    ),
    landmark(
      'Tour CN',
      'CA',
      43.6426,
      -79.3871,
      'Achevée en 1976, elle a été la plus haute tour autoportante du monde jusqu’en 2007, année où le Burj Khalifa l’a dépassée.',
      'Tour_CN',
      'CN_Tower',
    ),
    landmark(
      'Parlement de Budapest',
      'HU',
      47.5071,
      19.0456,
      'Achevé en 1904, il fut conçu pour les célébrations du millénaire de la Hongrie et reste le plus grand bâtiment du pays.',
      'Parlement_de_Budapest',
      'Hungarian_Parliament_Building',
    ),
    landmark(
      'Palais du Potala',
      'CN',
      29.6558,
      91.117,
      'Résidence des dalaï-lamas jusqu’en 1959, il compte plus d’un millier de pièces et fut érigé à partir de 1645 sous le 5e dalaï-lama.',
      'Palais_du_Potala',
      'Potala_Palace',
    ),
    landmark(
      'Château d’Himeji',
      'JP',
      34.8394,
      134.6939,
      'Surnommé « château du héron blanc » pour sa façade éclatante, il compte parmi les rares châteaux japonais jamais détruits par la guerre, le feu ou les séismes.',
      'Château_de_Himeji',
      'Himeji_Castle',
    ),
    landmark(
      'Fushimi Inari-taisha',
      'JP',
      34.9671,
      135.7727,
      'Ses milliers de torii orange, offerts par des entreprises et des particuliers, ont été installés progressivement depuis la fondation du sanctuaire en 711.',
      'Fushimi_Inari-taisha',
      'Fushimi_Inari-taisha',
    ),
    landmark(
      'Palais de Topkapi',
      'TR',
      41.0115,
      28.9834,
      'Résidence principale des sultans ottomans pendant près de 400 ans, de 1465 jusqu’au milieu du XIXe siècle.',
      'Palais_de_Topkapı',
      'Topkapı_Palace',
    ),
    landmark(
      'Wat Arun',
      'TH',
      13.7437,
      100.4889,
      'Son prang central, haut d’environ 70 m, est entièrement décoré de fragments de porcelaine chinoise incrustés.',
      'Wat_Arun',
      'Wat_Arun',
    ),
    landmark(
      'Tikal',
      'GT',
      17.222,
      -89.6237,
      'Sa pyramide la plus haute, le Temple IV, culmine à plus de 70 m, ce qui en fait l’une des plus hautes structures précolombiennes des Amériques.',
      'Tikal',
      'Tikal',
    ),
    landmark(
      'Teotihuacán',
      'MX',
      19.6925,
      -98.8438,
      'Le nom de la cité, qui signifie « lieu où sont nés les dieux », lui a été donné bien plus tard par les Aztèques : l’identité de ses bâtisseurs reste incertaine.',
      'Teotihuacan',
      'Teotihuacan',
    ),
    landmark(
      'Château d’Édimbourg',
      'GB',
      55.9486,
      -3.1999,
      'Bâti sur un ancien volcan éteint, il abrite depuis 1861 le « One O’Clock Gun », un coup de canon tiré chaque jour à 13h précises.',
      "Château_d'Édimbourg",
      'Edinburgh_Castle',
    ),
    landmark(
      'Abbaye de Westminster',
      'GB',
      51.4994,
      -0.1273,
      'Chaque monarque britannique y a été couronné depuis Guillaume le Conquérant en 1066, à deux exceptions près.',
      'Abbaye_de_Westminster',
      'Westminster_Abbey',
    ),
    landmark(
      'Château de Prague',
      'CZ',
      50.0909,
      14.4016,
      'Avec une superficie d’environ 70 000 m², le Guinness des records le considère comme le plus grand complexe castral ancien du monde.',
      'Château_de_Prague',
      'Prague_Castle',
    ),
    landmark(
      'Pont Charles',
      'CZ',
      50.0865,
      14.4114,
      'Sa construction débute en 1357 sous Charles IV, pour remplacer le pont Judith emporté par une crue.',
      'Pont_Charles',
      'Charles_Bridge',
    ),
    landmark(
      'Duomo de Milan',
      'IT',
      45.4642,
      9.1922,
      'Sa construction, débutée en 1386, s’est étalée sur près de six siècles ; c’est Napoléon qui fit accélérer l’achèvement de la façade au début du XIXe siècle.',
      'Duomo_de_Milan',
      'Milan_Cathedral',
    ),
    landmark(
      'Pont du Rialto',
      'IT',
      45.438,
      12.3358,
      'Achevé en 1591, il fut pendant près de trois siècles le seul moyen de traverser le Grand Canal à pied.',
      'Pont_du_Rialto',
      'Rialto_Bridge',
    ),
    landmark(
      'Mosquée Hassan II',
      'MA',
      33.6084,
      -7.6325,
      'Achevée en 1993, elle possède le plus haut minaret du monde religieux, culminant à 210 m, et son sol vitré laisse voir l’océan Atlantique en contrebas.',
      'Mosquée_Hassan_II',
      'Hassan_II_Mosque',
    ),
    landmark(
      'Space Needle',
      'US',
      47.6205,
      -122.3493,
      'Construite en un peu moins d’un an pour l’Exposition universelle de 1962, elle a été conçue pour résister aux vents violents et aux séismes propres à la région.',
      'Space_Needle',
      'Space_Needle',
    ),
    landmark(
      'Barrage Hoover',
      'US',
      36.0161,
      -114.7377,
      'Construit pendant la Grande Dépression et achevé en 1936, il a nécessité le travail d’environ 21 000 ouvriers.',
      'Barrage_Hoover',
      'Hoover_Dam',
    ),
    landmark(
      'Château de Windsor',
      'GB',
      51.4839,
      -0.6044,
      'Fondé par Guillaume le Conquérant vers 1070, c’est le plus grand et le plus ancien château encore habité au monde.',
      'Château_de_Windsor',
      'Windsor_Castle',
    ),
    landmark(
      'Robben Island',
      'ZA',
      -33.807,
      18.3667,
      'Nelson Mandela y a été emprisonné pendant 18 des 27 années qu’il a passées derrière les barreaux.',
      'Robben_Island',
      'Robben_Island',
    ),
    landmark(
      'Grand-Place de Bruxelles',
      'BE',
      50.8467,
      4.3525,
      'Presque entièrement détruite par un bombardement français en 1695, elle a été reconstruite en à peine quatre ans.',
      'Grand-Place_de_Bruxelles',
      'Grand-Place',
    ),
    landmark(
      'Cathédrale de Cologne',
      'DE',
      50.9413,
      6.9583,
      'Sa construction, commencée en 1248, s’est interrompue pendant des siècles avant de reprendre et de s’achever en 1880, soit 632 ans plus tard.',
      'Cathédrale_de_Cologne',
      'Cologne_Cathedral',
    ),
    landmark(
      'Grand Bouddha de Leshan',
      'CN',
      29.5453,
      103.7708,
      'Sculpté dans la falaise à partir de 713 sous la direction du moine Haitong, il mesure 71 m de haut, ce qui en fait la plus grande statue de Bouddha en pierre au monde.',
      'Grand_Bouddha_de_Leshan',
      'Leshan_Giant_Buddha',
    ),
    landmark(
      'Temples de Bagan',
      'MM',
      21.1717,
      94.8585,
      'Plus de 10 000 temples et stupas y furent construits entre le XIe et le XIIIe siècle ; environ 2 000 sont encore debout aujourd’hui.',
      'Bagan',
      'Bagan',
    ),
    landmark(
      'Pagode Shwedagon',
      'MM',
      16.7983,
      96.1496,
      'Selon la légende, elle abriterait des reliques de quatre bouddhas ; son stupa est entièrement recouvert de feuilles d’or et couronné de milliers de diamants et pierres précieuses.',
      'Pagode_Shwedagon',
      'Shwedagon_Pagoda',
    ),
    landmark(
      'Sanctuaire d’Ise',
      'JP',
      34.4553,
      136.7256,
      'Selon la tradition du Shikinen Sengu, le sanctuaire est entièrement reconstruit à l’identique tous les vingt ans depuis le VIIe siècle.',
      "Sanctuaire_d'Ise",
      'Ise_Grand_Shrine',
    ),
    landmark(
      'Grand Palais de Bangkok',
      'TH',
      13.75,
      100.4914,
      'Résidence officielle des rois de Thaïlande depuis 1782, il abrite le temple du Bouddha d’Émeraude, la statue la plus vénérée du pays.',
      'Palais_royal_(Bangkok)',
      'Grand_Palace',
    ),
    landmark(
      'Armée de terre cuite de Xi’an',
      'CN',
      34.3841,
      109.2785,
      'Découverte par hasard en 1974 par des paysans qui creusaient un puits, l’armée compte plus de 8 000 soldats, tous aux visages différents.',
      'Armée_de_terre_cuite',
      'Terracotta_Army',
    ),
    landmark(
      'Cristo de la Concordia',
      'BO',
      -17.4139,
      -66.1236,
      'Achevée en 1994, la statue mesure 34,20 m et fut un temps considérée comme la plus haute statue du Christ au monde, dépassant celle de Rio avec son piédestal.',
      'Cristo_de_la_Concordia',
      'Cristo_de_la_Concordia',
    ),
    landmark(
      'Forteresse de Sacsayhuamán',
      'PE',
      -13.5087,
      -71.9822,
      'Ses murs sont assemblés à partir de blocs de pierre pesant parfois plus de 100 tonnes, taillés et emboîtés avec une précision telle qu’aucun mortier n’était nécessaire.',
      'Saqsaywaman',
      'Sacsayhuamán',
    ),
    landmark(
      'Kremlin de Moscou',
      'RU',
      55.752,
      37.6175,
      'Ses murs et tours actuels ont été édifiés à la fin du XVe siècle par des architectes italiens invités par Ivan III.',
      'Kremlin_de_Moscou',
      'Moscow_Kremlin',
    ),
    landmark(
      'Fort Rouge de Delhi',
      'IN',
      28.6562,
      77.241,
      'Construit par l’empereur moghol Shah Jahan, celui-là même qui fit bâtir le Taj Mahal, c’est de ses remparts que le Premier ministre indien s’adresse chaque année à la nation le jour de l’Indépendance.',
      'Fort_Rouge_(Delhi)',
      'Red_Fort',
    ),
    landmark(
      'Mosquée Cheikh Zayed',
      'AE',
      24.4128,
      54.4747,
      'Sa salle de prière principale abrite l’un des plus grands tapis noués main au monde, tissé par plus de 1 200 artisans.',
      'Mosquée_Cheikh_Zayed',
      'Sheikh_Zayed_Grand_Mosque',
    ),
    landmark(
      'Parlement du Canada',
      'CA',
      45.4236,
      -75.7003,
      'L’édifice central actuel a été reconstruit après l’incendie de 1916 qui détruisit le précédent bâtiment ; sa tour de la Paix fut achevée en 1927.',
      'Colline_du_Parlement',
      'Parliament_Hill',
    ),
    landmark(
      'Alcázar de Ségovie',
      'ES',
      40.9536,
      -4.1305,
      'Sa silhouette en forme de proue de navire aurait inspiré, selon une légende tenace, le château de Cendrillon des studios Disney.',
      'Alcázar_de_Ségovie',
      'Alcázar_of_Segovia',
    ),
    landmark(
      'Parc Güell',
      'ES',
      41.4145,
      2.1527,
      'Conçu par Antoni Gaudí comme un lotissement résidentiel de luxe, le projet fut un échec commercial et ne compta que deux maisons habitées avant de devenir un parc public en 1926.',
      'Parc_Güell',
      'Park_Güell',
    ),
    landmark(
      'Mezquita de Cordoue',
      'ES',
      37.8789,
      -4.7794,
      'Sa salle de prière, commencée en 785, compte plus de 850 colonnes de marbre, granit et jaspe surmontées d’arcs à voussures rouges et blanches caractéristiques.',
      'Mosquée-cathédrale_de_Cordoue',
      'Mosque–Cathedral_of_Córdoba',
    ),
    landmark(
      'Camp d’Auschwitz-Birkenau',
      'PL',
      50.0359,
      19.1783,
      'Libéré par l’Armée rouge le 27 janvier 1945, ce camp nazi a vu périr plus d’un million de personnes, en majorité des Juifs européens.',
      'Auschwitz',
      'Auschwitz_concentration_camp',
    ),
    landmark(
      'Panthéon de Rome',
      'IT',
      41.8986,
      12.4769,
      'Reconstruit sous l’empereur Hadrien vers 126 apr. J.-C., son dôme en béton non armé reste, près de deux mille ans plus tard, le plus grand du monde dans cette catégorie.',
      'Panthéon_(Rome)',
      'Pantheon,_Rome',
    ),
    landmark(
      'Pompéi',
      'IT',
      40.7461,
      14.4989,
      'Ensevelie sous les cendres du Vésuve en 79 apr. J.-C., la ville n’a été redécouverte qu’au XVIIIe siècle, les fouilles systématiques débutant en 1748.',
      'Pompéi',
      'Pompeii',
    ),
  ]),

  ...hard([
    landmark(
      'Futuroscope',
      'FR',
      46.6694,
      0.3684,
      'Ouvert en 1987 près de Poitiers, ce parc est dédié à l’image et aux nouvelles technologies, avec des attractions comme le cinéma Kinémax reconnaissable à son architecture futuriste.',
      'Futuroscope',
      'Futuroscope',
    ),
    landmark(
      'Gouffre de Padirac',
      'FR',
      44.8608,
      1.7517,
      'Exploré pour la première fois en 1889 par le spéléologue Édouard-Alfred Martel, ce gouffre naturel s’ouvre sur une rivière souterraine à plus de 100 m de profondeur.',
      'Gouffre_de_Padirac',
      'Gouffre_de_Padirac',
    ),
    landmark(
      'Plages du Débarquement (Omaha)',
      'FR',
      49.3695,
      -0.8687,
      'Le 6 juin 1944, ce fut la plage du Débarquement où les pertes alliées furent les plus lourdes, ce qui lui valut le surnom de « Bloody Omaha ».',
      'Omaha_Beach',
      'Omaha_Beach',
    ),
    landmark(
      'Arènes de Nîmes',
      'FR',
      43.8367,
      4.3608,
      'Construites à la fin du Ier siècle apr. J.-C., ce sont les arènes romaines les mieux conservées au monde ; elles accueillent encore aujourd’hui corridas et concerts.',
      'Arènes_de_Nîmes',
      'Arena_of_Nîmes',
    ),
    landmark(
      'Château de Fontainebleau',
      'FR',
      48.4021,
      2.7014,
      'Habité sans interruption par les souverains français pendant huit siècles, c’est dans sa cour que Napoléon fit ses adieux à la Garde impériale en 1814.',
      'Château_de_Fontainebleau',
      'Château_de_Fontainebleau',
    ),
    landmark(
      'Basilique de Vézelay',
      'FR',
      47.4642,
      3.7472,
      'C’est depuis son parvis que saint Bernard de Clairvaux prêcha la deuxième croisade en 1146, devant le roi de France Louis VII.',
      'Basilique_Sainte-Marie-Madeleine_de_Vézelay',
      'Vézelay_Abbey',
    ),
    landmark(
      'Palais Garnier',
      'FR',
      48.872,
      2.3316,
      'Sa construction, achevée en 1875 par l’architecte Charles Garnier, a nécessité l’aménagement d’un réservoir d’eau souterrain qui inspira le lac du Fantôme de l’Opéra.',
      'Palais_Garnier',
      'Palais_Garnier',
    ),
    landmark(
      'Château d’If',
      'FR',
      43.2801,
      5.3253,
      'Construite au XVIe siècle, cette forteresse servit de prison d’État et doit surtout sa célébrité au roman Le Comte de Monte-Cristo d’Alexandre Dumas.',
      "Château_d'If",
      "Château_d'If",
    ),
    landmark(
      'Cathédrale de Reims',
      'FR',
      49.2533,
      4.0347,
      'Vingt-cinq rois de France y ont été sacrés, de Clovis en 496 à Charles X en 1825 ; elle fut gravement endommagée par les bombardements de la Première Guerre mondiale.',
      'Cathédrale_Notre-Dame_de_Reims',
      'Reims_Cathedral',
    ),
    landmark(
      'Château de Chantilly',
      'FR',
      49.1936,
      2.4869,
      'Rebâti au XIXe siècle par le duc d’Aumale, il abrite le musée Condé, qui conserve la deuxième plus riche collection de peintures anciennes de France après le Louvre.',
      'Château_de_Chantilly',
      'Château_de_Chantilly',
    ),
    landmark(
      'Cité radieuse de Marseille',
      'FR',
      43.2601,
      5.3958,
      'Conçue par Le Corbusier et achevée en 1952, cette unité d’habitation en béton brut a marqué la naissance du mouvement brutaliste en architecture.',
      'Cité_radieuse_de_Marseille',
      "Unité_d'Habitation",
    ),
    landmark(
      'Château de Pierrefonds',
      'FR',
      49.3467,
      2.9814,
      'Ruine médiévale entièrement restaurée par Eugène Viollet-le-Duc à partir de 1857 sur ordre de Napoléon III, il a servi de décor à de nombreux films et séries.',
      'Château_de_Pierrefonds',
      'Château_de_Pierrefonds',
    ),
    landmark(
      'Pyramide du Louvre',
      'FR',
      48.8611,
      2.3358,
      'Inaugurée en 1989, cette pyramide de verre conçue par l’architecte sino-américain I. M. Pei suscita une vive polémique avant de devenir un symbole de Paris.',
      'Pyramide_du_Louvre',
      'Louvre_Pyramid',
    ),
    landmark(
      'Temple du Ciel',
      'CN',
      39.8822,
      116.4066,
      'Construit en 1420 sous l’empereur Yongle, c’est ici que les empereurs venaient prier chaque année pour obtenir de bonnes récoltes.',
      'Temple_du_Ciel',
      'Temple_of_Heaven',
    ),
    landmark(
      'Grande Mosquée de Djenné',
      'ML',
      13.9058,
      -4.5556,
      'Plus grand édifice en terre crue du monde, elle nécessite un ravalement collectif annuel de sa façade en banco, lors d’une fête organisée par tous les habitants de la ville.',
      'Grande_Mosquée_de_Djenné',
      'Great_Mosque_of_Djenné',
    ),
    landmark(
      'Great Zimbabwe',
      'ZW',
      -20.2675,
      30.9333,
      'Bâtie entre le XIe et le XVe siècle par le peuple shona sans aucun mortier, cette cité de pierre a donné son nom au Zimbabwe moderne.',
      'Grand_Zimbabwe',
      'Great_Zimbabwe',
    ),
    landmark(
      'Château de Bran',
      'RO',
      45.5149,
      25.3672,
      'Bien que Bram Stoker n’ait jamais visité la Roumanie, ce château est devenu, par légende touristique, le « château de Dracula », malgré un lien historique ténu avec Vlad l’Empaleur.',
      'Château_de_Bran',
      'Bran_Castle',
    ),
    landmark(
      'Château de Peleș',
      'RO',
      45.3597,
      25.5389,
      'Achevé en 1883 pour le roi Carol Ier, ce fut le premier château d’Europe entièrement équipé d’électricité, produite par sa propre centrale.',
      'Château_de_Peleș',
      'Peleș_Castle',
    ),
    landmark(
      'Mur d’Hadrien',
      'GB',
      55.0,
      -2.5,
      'Construit à partir de 122 apr. J.-C. sur ordre de l’empereur Hadrien, ce mur de 117 km marquait la frontière nord de l’Empire romain.',
      "Mur_d'Hadrien",
      "Hadrian's_Wall",
    ),
    landmark(
      'Moaï de Rano Raraku',
      'CL',
      -27.1258,
      -109.287,
      'Ce cratère volcanique fut la carrière principale des moaï : près de 400 statues y restent inachevées, encore taillées à même la roche.',
      'Rano_Raraku',
      'Rano_Raraku',
    ),
    landmark(
      'Char Minar',
      'IN',
      17.3616,
      78.4747,
      'Édifié en 1591 par le sultan Muhammad Quli Qutb Shah, il aurait été construit pour marquer la fin d’une épidémie de peste.',
      'Charminar',
      'Charminar',
    ),
    landmark(
      'Hawa Mahal',
      'IN',
      26.9239,
      75.8267,
      'Construit en 1799, son immense façade en nid d’abeille compte 953 petites fenêtres ajourées, qui permettaient aux femmes du harem d’observer la rue sans être vues.',
      'Hawa_Mahal',
      'Hawa_Mahal',
    ),
    landmark(
      'Mausolée de Hô Chi Minh',
      'VN',
      21.0369,
      105.834,
      'Le corps embaumé du dirigeant y est exposé depuis 1975, bien qu’il eût lui-même demandé, dans son testament, à être incinéré.',
      'Mausolée_Hô_Chi_Minh',
      'Ho_Chi_Minh_Mausoleum',
    ),
    landmark(
      'Angkor Thom',
      'KH',
      13.4412,
      103.8589,
      'Dernière capitale de l’empire khmer, fondée à la fin du XIIe siècle par Jayavarman VII, elle abrite le temple du Bayon et ses tours ornées de visages géants.',
      'Angkor_Thom',
      'Angkor_Thom',
    ),
    landmark(
      'Ayutthaya',
      'TH',
      14.3532,
      100.5684,
      'Capitale du royaume de Siam pendant plus de 400 ans, elle fut presque entièrement détruite par l’armée birmane en 1767.',
      "Parc_historique_d'Ayutthaya",
      'Ayutthaya_Historical_Park',
    ),
    landmark(
      'Prambanan',
      'ID',
      -7.752,
      110.4914,
      'Édifié au IXe siècle, c’est le plus grand ensemble de temples hindous d’Indonésie, dédié à la trinité Brahma, Vishnu et Shiva.',
      'Prambanan',
      'Prambanan',
    ),
    landmark(
      'Persépolis',
      'IR',
      29.9351,
      52.8916,
      'Fondée vers 518 av. J.-C. par Darius Ier comme capitale cérémonielle de l’Empire perse, elle fut incendiée par Alexandre le Grand en 330 av. J.-C.',
      'Persépolis',
      'Persepolis',
    ),
    landmark(
      'Pyramide de Djoser (Saqqarah)',
      'EG',
      29.8714,
      31.2164,
      'Conçue par l’architecte Imhotep pour le pharaon Djoser vers 2650 av. J.-C., c’est le plus ancien grand édifice de pierre taillée connu au monde.',
      'Pyramide_de_Djéser',
      'Pyramid_of_Djoser',
    ),
    landmark(
      'Karnak',
      'EG',
      25.7188,
      32.6573,
      'Agrandi par des générations de pharaons sur près de deux mille ans, c’est le plus vaste complexe religieux jamais construit ; sa salle hypostyle compte 134 colonnes géantes.',
      'Temple_de_Karnak',
      'Karnak',
    ),
    landmark(
      'Vallée des Rois',
      'EG',
      25.7402,
      32.6014,
      'Howard Carter y a découvert en 1922 le tombeau presque intact de Toutânkhamon, l’une des plus grandes découvertes archéologiques du XXe siècle.',
      'Vallée_des_Rois',
      'Valley_of_the_Kings',
    ),
    landmark(
      'Amphithéâtre d’El Jem',
      'TN',
      35.2967,
      10.7075,
      'Construit vers 238 apr. J.-C., c’est le troisième plus grand amphithéâtre romain au monde, capable d’accueillir environ 35 000 spectateurs.',
      "Amphithéâtre_d'El_Jem",
      'Amphitheatre_of_El_Jem',
    ),
    landmark(
      'Lignes de Nazca',
      'PE',
      -14.7,
      -75.13,
      'Tracées entre 500 av. J.-C. et 500 apr. J.-C. par la culture nazca, ces gigantesques figures ne sont pleinement visibles que depuis les airs ; leur fonction exacte reste débattue.',
      'Lignes_de_Nazca',
      'Nazca_Lines',
    ),
    landmark(
      'Independence Hall',
      'US',
      39.9489,
      -75.15,
      'C’est dans ce bâtiment que la Déclaration d’indépendance fut adoptée en 1776, puis que la Constitution des États-Unis fut rédigée en 1787.',
      'Independence_Hall',
      'Independence_Hall',
    ),
    landmark(
      'Mount Vernon',
      'US',
      38.7292,
      -77.1086,
      'Résidence de George Washington pendant plus de 45 ans, c’est également là qu’il est enterré, aux côtés de son épouse Martha.',
      undefined,
      'Mount_Vernon',
    ),
    landmark(
      'Château Frontenac',
      'CA',
      46.8117,
      -71.2047,
      'Ouvert en 1893 par la Canadian Pacific Railway pour attirer une clientèle huppée, il serait aujourd’hui l’un des hôtels les plus photographiés au monde.',
      'Château_Frontenac',
      'Château_Frontenac',
    ),
    landmark(
      'Hobbiton Movie Set',
      'NZ',
      -37.8722,
      175.6816,
      'Construit sur une ferme d’élevage de moutons à Matamata pour les films Le Seigneur des anneaux, le décor a été rendu permanent à la demande du réalisateur Peter Jackson.',
      'Hobbiton',
      'Hobbiton_Movie_Set',
    ),
    landmark(
      'Château d’Urquhart',
      'GB',
      57.3241,
      -4.4407,
      'Ses ruines dominent le loch Ness, où de nombreux témoignages du monstre légendaire ont été rapportés ; le château fut partiellement détruit en 1692 pour empêcher son usage par les jacobites.',
      "Château_d'Urquhart",
      'Urquhart_Castle',
    ),
    landmark(
      'Cathédrale de Rouen',
      'FR',
      49.4402,
      1.0944,
      'Sa façade a été peinte plus de trente fois par Claude Monet entre 1892 et 1894, sous différentes lumières et à différentes heures du jour.',
      'Cathédrale_Notre-Dame_de_Rouen',
      'Rouen_Cathedral',
    ),
    landmark(
      'Château du Haut-Kœnigsbourg',
      'FR',
      48.2496,
      7.3444,
      'Restauré à partir de 1900 sur ordre de l’empereur allemand Guillaume II, qui voulait en faire un symbole de la puissance impériale en Alsace.',
      'Château_du_Haut-Kœnigsbourg',
      'Haut-Kœnigsbourg_Castle',
    ),
    landmark(
      'Arènes d’Arles',
      'FR',
      43.6772,
      4.6308,
      'Construites vers 90 apr. J.-C., elles pouvaient accueillir plus de 20 000 spectateurs et servent encore aujourd’hui de cadre à des courses camarguaises.',
      "Arènes_d'Arles",
      'Arles_Amphitheatre',
    ),
    landmark(
      'Escurial',
      'ES',
      40.5897,
      -4.148,
      'Édifié par Philippe II d’Espagne pour commémorer sa victoire à la bataille de Saint-Quentin en 1557, ce monastère-palais fut achevé en 1584.',
      'Escurial',
      'El_Escorial',
    ),
    landmark(
      'Château de Wawel',
      'PL',
      50.0544,
      19.9356,
      'Ancienne résidence des rois de Pologne, la colline sur laquelle il se dresse est associée à la légende du dragon du Wawel, vaincu par la ruse d’un jeune cordonnier.',
      'Château_du_Wawel',
      'Wawel_Castle',
    ),
    landmark(
      'Château de Hohenzollern',
      'DE',
      48.3236,
      8.9678,
      'Berceau de la dynastie des Hohenzollern, rois de Prusse puis empereurs allemands, le château actuel, le troisième sur ce site, a été rebâti au milieu du XIXe siècle après la destruction du précédent lors d’un siège.',
      'Château_de_Hohenzollern',
      'Hohenzollern_Castle',
    ),
    landmark(
      'Château Saint-Ange',
      'IT',
      41.9031,
      12.4663,
      'Édifié à l’origine comme mausolée pour l’empereur Hadrien au IIe siècle, il fut ensuite transformé en forteresse papale, reliée au Vatican par un passage secret, le Passetto di Borgo.',
      'Château_Saint-Ange',
      "Castel_Sant'Angelo",
    ),
  ]),

  ...master([
    landmark(
      'Mosquées de Tombouctou',
      'ML',
      16.7666,
      -3.0026,
      'Bâties en terre crue à partir du XIVe siècle, ces mosquées étaient associées à une prestigieuse université islamique qui attirait chercheurs et manuscrits de tout le monde musulman.',
      undefined,
      undefined,
    ),
    landmark(
      'Grottes d’Ellora',
      'IN',
      20.026,
      75.1789,
      'Le temple de Kailasa, le plus impressionnant des 34 grottes du site, a été entièrement taillé de haut en bas dans un seul bloc de roche, au VIIIe siècle.',
      "Grottes_d'Ellora",
      'Ellora_Caves',
    ),
    landmark(
      'Grottes d’Ajanta',
      'IN',
      20.5519,
      75.7033,
      'Abandonnées et recouvertes par la végétation pendant des siècles, ces grottes bouddhiques n’ont été redécouvertes qu’en 1819, par un officier britannique parti chasser le tigre.',
      "Grottes_d'Ajanta",
      'Ajanta_Caves',
    ),
    landmark(
      'Temple de Meenakshi',
      'IN',
      9.9195,
      78.1193,
      'Ses gopuram, les tours-portails du temple, sont couverts de milliers de sculptures peintes représentant dieux, déesses et créatures mythologiques.',
      'Temple_de_Mînâkshî',
      'Meenakshi_Temple',
    ),
    landmark(
      'Temple de Jokhang',
      'CN',
      29.6525,
      91.1319,
      'Considéré comme le temple le plus sacré du bouddhisme tibétain, il fut fondé au VIIe siècle par le roi Songtsen Gampo.',
      'Jokhang',
      'Jokhang',
    ),
    landmark(
      'Tunnels de Cu Chi',
      'VN',
      11.1417,
      106.4544,
      'Ce réseau de tunnels souterrains, creusé à la main sur plus de 200 km, a permis au Viêt-Cong de résister aux forces américaines à proximité de Saïgon pendant la guerre du Viêtnam.',
      'Tunnels_de_Củ_Chi',
      'Củ_Chi_tunnels',
    ),
    landmark(
      'Preah Vihear',
      'KH',
      14.3911,
      104.6802,
      'Perché à plus de 500 m d’altitude sur la frontière entre le Cambodge et la Thaïlande, ce temple khmer fait l’objet d’un différend territorial tranché en 1962 par la Cour internationale de justice en faveur du Cambodge.',
      'Prasat_Preah_Vihéar',
      'Preah_Vihear_Temple',
    ),
    landmark(
      'Jerash',
      'JO',
      32.2725,
      35.8916,
      'L’une des villes les mieux conservées de l’ancienne Décapole romaine, ses colonnades et son hippodrome sont restés pratiquement intacts sous le sable pendant des siècles.',
      'Jerash',
      'Jerash',
    ),
    landmark(
      'Palmyre',
      'SY',
      34.55,
      38.2688,
      'Capitale du royaume de la reine Zénobie au IIIe siècle, cette cité caravanière du désert syrien a vu plusieurs de ses monuments emblématiques détruits par le groupe État islamique en 2015.',
      'Palmyre',
      'Palmyra',
    ),
    landmark(
      'Baalbek',
      'LB',
      34.0059,
      36.2039,
      'Son podium repose sur trois blocs de pierre, le Trilithon, pesant chacun environ 800 tonnes — parmi les plus grosses pierres jamais taillées par l’homme.',
      'Baalbek',
      'Baalbek',
    ),
    landmark(
      'Krak des Chevaliers',
      'SY',
      34.7562,
      36.2931,
      'T. E. Lawrence, le futur « Lawrence d’Arabie », le qualifia en 1909 de plus beau château du monde ; cette forteresse croisée n’a quasiment jamais été prise d’assaut.',
      'Krak_des_Chevaliers',
      'Krak_des_Chevaliers',
    ),
    landmark(
      'Aït Benhaddou',
      'MA',
      31.0472,
      -7.1319,
      'Ce ksar fortifié en pisé, ancienne étape sur la route caravanière entre le Sahara et Marrakech, a servi de décor à de nombreux films et séries, dont Gladiator et Game of Thrones.',
      'Aït_Benhaddou',
      'Ait_Benhaddou',
    ),
    landmark(
      'Pyramides de Méroé',
      'SD',
      16.9333,
      33.75,
      'Plus de 200 pyramides royales, plus petites et bien plus pentues que celles d’Égypte, y furent édifiées par les souverains du royaume de Koush.',
      'Pyramides_de_Méroé',
      'Pyramids_of_Meroë',
    ),
    landmark(
      'Lalibela',
      'ET',
      12.0316,
      39.0473,
      'Ses onze églises ont été entièrement taillées de haut en bas dans la roche volcanique aux XIIe et XIIIe siècles, sur ordre du roi Gebre Mesqel Lalibela, qui voulait bâtir une « nouvelle Jérusalem ».',
      'Lalibela',
      'Lalibela',
    ),
    landmark(
      'Aksoum',
      'ET',
      14.1211,
      38.7167,
      'L’une de ses immenses stèles de granit fut emportée à Rome par les troupes de Mussolini en 1937 ; elle n’a été restituée à l’Éthiopie qu’en 2005.',
      'Aksoum',
      'Axum',
    ),
    landmark(
      'Timgad',
      'DZ',
      35.4842,
      6.4675,
      'Fondée par l’empereur Trajan vers 100 apr. J.-C. selon un plan en damier caractéristique des villes romaines, elle est restée ensevelie sous le sable pendant des siècles avant sa redécouverte.',
      'Timgad',
      'Timgad',
    ),
    landmark(
      'Djémila',
      'DZ',
      36.3214,
      5.7361,
      'Perchée à plus de 900 m d’altitude, cette ancienne cité romaine conserve l’un des ensembles de vestiges les mieux préservés d’Afrique du Nord.',
      'Djémila',
      'Djémila',
    ),
    landmark(
      'Leptis Magna',
      'LY',
      32.6383,
      14.2919,
      'Ville natale de l’empereur romain Septime Sévère, qui l’embellit considérablement au tournant du IIIe siècle pour en faire l’une des plus belles cités de l’Empire.',
      'Leptis_Magna',
      'Leptis_Magna',
    ),
    landmark(
      'Grande Mosquée de Kairouan',
      'TN',
      35.6828,
      10.1017,
      'Fondée en 670 par le général arabe Uqba ibn Nafi, c’est la plus ancienne mosquée du Maghreb ; la tradition veut que sept pèlerinages ici équivaillent à un pèlerinage à La Mecque.',
      'Grande_Mosquée_de_Kairouan',
      'Great_Mosque_of_Kairouan',
    ),
    landmark(
      'Palenque',
      'MX',
      17.4842,
      -92.0453,
      'En 1952, l’archéologue Alberto Ruz Lhuillier y a découvert la tombe intacte du roi Pakal, au terme de quatre années de fouilles dans le Temple des Inscriptions.',
      'Palenque_(Mexique)',
      'Palenque',
    ),
    landmark(
      'Uxmal',
      'MX',
      20.3597,
      -89.7692,
      'Selon la légende maya, la Pyramide du Devin qui domine le site aurait été construite en une seule nuit par un nain magicien ; en réalité, sa construction s’est étalée sur plusieurs siècles.',
      'Uxmal',
      'Uxmal',
    ),
    landmark(
      'Copán',
      'HN',
      14.8342,
      -89.1425,
      'Surnommée l’« Athènes du monde maya » pour la finesse de ses sculptures, la cité conserve le plus long texte hiéroglyphique précolombien connu, gravé sur son escalier monumental.',
      'Copán',
      'Copán',
    ),
    landmark(
      'Tiwanaku',
      'BO',
      -16.5544,
      -68.6733,
      'Cette civilisation antérieure aux Incas, installée près du lac Titicaca, a laissé la Porte du Soleil, un monolithe sculpté taillé dans un seul bloc de pierre.',
      'Tiwanaku',
      'Tiwanaku',
    ),
    landmark(
      'Ciudad Perdida',
      'CO',
      11.0378,
      -73.9256,
      'Fondée vers 800 apr. J.-C. par le peuple tairona, elle précède Machu Picchu de près de 650 ans ; elle n’a été redécouverte qu’en 1972, par des pilleurs de tombes.',
      'Ciudad_Perdida',
      'Ciudad_Perdida',
    ),
    landmark(
      'Ouro Preto',
      'BR',
      -20.3856,
      -43.5039,
      'Ancienne capitale de la ruée vers l’or au Brésil, la ville doit une grande partie de ses églises baroques au sculpteur Aleijadinho, atteint d’une maladie qui déformait ses mains.',
      'Ouro_Preto',
      'Ouro_Preto',
    ),
    landmark(
      'San Agustín',
      'CO',
      1.8836,
      -76.2789,
      'Le site rassemble la plus grande collection de statues funéraires monumentales précolombiennes d’Amérique du Sud, laissées par une culture dont l’identité reste largement mystérieuse.',
      'Parc_archéologique_de_San_Agustín',
      'San_Agustín_Archaeological_Park',
    ),
    landmark(
      'Parliament House',
      'AU',
      -35.3081,
      149.1244,
      'Inauguré en 1988, l’édifice a été construit à l’intérieur même d’une colline, que l’on peut gravir à pied jusqu’au sommet surmonté d’un immense mât porte-drapeau.',
      undefined,
      'Parliament_House,_Canberra',
    ),
    landmark(
      'Château de Blarney',
      'IE',
      51.9285,
      -8.5711,
      'Selon la légende, embrasser la pierre de Blarney, encastrée tout en haut du donjon, confère le don d’éloquence à celui qui s’y risque.',
      'Château_de_Blarney',
      'Blarney_Castle',
    ),
    landmark(
      'Newgrange',
      'IE',
      53.6947,
      -6.4753,
      'Construit vers 3200 av. J.-C., ce tumulus est plus ancien que Stonehenge et que les pyramides d’Égypte ; sa chambre intérieure s’illumine chaque année au lever du soleil du solstice d’hiver.',
      'Newgrange',
      'Newgrange',
    ),
    landmark(
      'Théâtre antique d’Orange',
      'FR',
      44.1372,
      4.8078,
      'Son mur de scène, haut de 37 m, est l’un des mieux conservés du monde romain ; Louis XIV l’aurait qualifié de plus belle muraille de son royaume.',
      "Théâtre_antique_d'Orange",
      'Theatre_of_Orange',
    ),
    landmark(
      'Mont Sainte-Odile',
      'FR',
      48.4256,
      7.4128,
      'Fondé selon la légende par sainte Odile, devenue aveugle à la naissance puis miraculeusement guérie, le couvent est aujourd’hui le lieu de pèlerinage le plus fréquenté d’Alsace.',
      'Mont_Sainte-Odile',
      'Mont_Sainte-Odile',
    ),
    landmark(
      'Château de Josselin',
      'FR',
      47.9556,
      -2.5439,
      'Propriété de la famille de Rohan depuis le XIVe siècle, le château leur appartient encore aujourd’hui, ce qui en fait l’un des plus anciens fiefs familiaux de France.',
      'Château_de_Josselin',
      undefined,
    ),
    landmark(
      'Château de Malbork',
      'PL',
      54.0397,
      19.0275,
      'Édifié par les chevaliers Teutoniques à partir de 1274, c’est le plus grand château du monde par la superficie et le plus vaste édifice de brique jamais construit.',
      'Château_de_Malbork',
      'Malbork_Castle',
    ),
    landmark(
      'Château de Bojnice',
      'SK',
      48.7822,
      18.5764,
      'Le comte János Ferenc Pálffy l’a fait entièrement remodeler à la fin du XIXe siècle, en s’inspirant des châteaux de la Loire qu’il admirait lors de ses voyages en France.',
      'Château_de_Bojnice',
      'Bojnice_Castle',
    ),
    landmark(
      'Château de Vianden',
      'LU',
      49.9347,
      6.2072,
      'L’écrivain Victor Hugo y séjourna à plusieurs reprises pendant son exil et en fit des dessins qui contribuèrent à sauver le château de la ruine.',
      'Château_de_Vianden',
      'Vianden_Castle',
    ),
  ]),
];
