import type { Place } from '@/types';

import { placeFactory, tier } from './helpers';

const mountain = placeFactory('mountains');
const easy = tier('easy');
const intermediate = tier('intermediate');
const hard = tier('hard');
const master = tier('master');

export const MOUNTAINS: Place[] = [
  ...easy([
    mountain(
      'Mont Blanc',
      'FR',
      45.8326,
      6.8652,
      'Sa première ascension, le 8 août 1786 par Jacques Balmat et Michel Paccard, est considérée comme l’acte de naissance de l’alpinisme moderne.',
      'Mont_Blanc',
      'Mont_Blanc',
    ),
    mountain(
      'Everest',
      'NP',
      27.9881,
      86.925,
      'Son sommet a été atteint pour la première fois le 29 mai 1953 par Edmund Hillary et Tensing Norgay.',
      'Everest',
      'Mount_Everest',
    ),
    mountain(
      'K2',
      'PK',
      35.8825,
      76.5133,
      'Surnommée la « montagne sauvage » pour la difficulté et le danger de son ascension, elle n’a été gravie pour la première fois qu’en 1954, par les Italiens Lacedelli et Compagnoni.',
      'K2',
      'K2',
    ),
    mountain(
      'Kilimandjaro',
      'TZ',
      -3.0674,
      37.3556,
      'Son Uhuru Peak, atteint pour la première fois en 1889 par Hans Meyer et Ludwig Purtscheller, culmine à environ 5 892 m, faisant du Kilimandjaro la plus haute montagne libre du monde.',
      'Kilimandjaro',
      'Mount_Kilimanjaro',
    ),
    mountain(
      'Mont Fuji',
      'JP',
      35.3606,
      138.7274,
      'Sa dernière éruption, dite de l’ère Hōei, s’est produite entre décembre 1707 et janvier 1708.',
      'Mont_Fuji',
      'Mount_Fuji',
    ),
    mountain(
      'Cervin',
      'CH',
      45.9763,
      7.6586,
      'Sa première ascension, le 14 juillet 1865 par l’équipe d’Edward Whymper, a viré au drame : quatre des sept alpinistes sont morts à la descente.',
      'Cervin',
      'Matterhorn',
    ),
    mountain(
      'Denali',
      'US',
      63.0692,
      -151.007,
      'Point culminant de l’Amérique du Nord à 6 190 m, il a porté le nom de mont McKinley avant d’être officiellement renommé Denali en 2015.',
      'Denali',
      'Denali',
    ),
    mountain(
      'Aconcagua',
      'AR',
      -32.6532,
      -70.0109,
      'Le guide suisse Matthias Zurbriggen en a atteint le sommet, à 6 962 m, le 14 janvier 1897, réalisant la première ascension connue du plus haut sommet d’Amérique du Sud.',
      'Aconcagua',
      'Aconcagua',
    ),
    mountain(
      'Vésuve',
      'IT',
      40.8224,
      14.4289,
      'Son éruption de l’an 79 a enseveli les villes romaines de Pompéi et d’Herculanum sous les cendres et les coulées pyroclastiques.',
      'Vésuve',
      'Mount_Vesuvius',
    ),
    mountain(
      'Etna',
      'IT',
      37.751,
      14.9934,
      'L’un des volcans les plus actifs au monde : il a connu près de 80 éruptions au cours du seul XXe siècle.',
      'Etna',
      'Mount_Etna',
    ),
    mountain(
      'Ben Nevis',
      'GB',
      56.7969,
      -5.0036,
      'Point culminant des îles Britanniques à 1 345 m, il a porté un observatoire météorologique à son sommet de 1883 à 1904.',
      'Ben_Nevis',
      'Ben_Nevis',
    ),
    mountain(
      'Olympe',
      'GR',
      40.0859,
      22.3583,
      'Son point culminant, le Mytikas (2 918 m), n’a été atteint pour la première fois qu’en 1913, par le photographe suisse Frédéric Boissonnas et le guide grec Christos Kakkalos.',
      'Mont_Olympe',
      'Mount_Olympus',
    ),
    mountain(
      'Mont Rainier',
      'US',
      46.8523,
      -121.7603,
      'Sa station de Paradise a enregistré 28,5 m de neige lors de l’hiver 1971-1972, un record nord-américain d’enneigement annuel.',
      'Mont_Rainier',
      'Mount_Rainier',
    ),
    mountain(
      'Annapurna',
      'NP',
      28.5961,
      83.8203,
      'Gravi le 3 juin 1950 par Maurice Herzog et Louis Lachenal, il fut le tout premier sommet de plus de 8 000 m vaincu par l’homme.',
      'Annapurna',
      'Annapurna',
    ),
    mountain(
      'Table Mountain (Montagne de la Table)',
      'ZA',
      -33.9628,
      18.4098,
      'Le navigateur portugais António de Saldanha en a fait la première ascension européenne connue en 1503, alors que sa flotte cherchait refuge dans la baie de la Table.',
      'Montagne_de_la_Table',
      'Table_Mountain',
    ),
    mountain(
      'Mont St. Helens',
      'US',
      46.1912,
      -122.1944,
      'Son éruption du 18 mai 1980, précédée d’un effondrement massif du flanc nord, a fait 57 morts.',
      'Mont_Saint_Helens',
      'Mount_St._Helens',
    ),
  ]),

  ...intermediate([
    mountain(
      'Puy de Dôme',
      'FR',
      45.7722,
      2.964,
      'En 1648, Blaise Pascal y fit mener par son beau-frère Florin Périer une expérience barométrique prouvant que la pression atmosphérique diminue avec l’altitude.',
      'Puy_de_Dôme',
      'Puy_de_Dôme',
    ),
    mountain(
      'Mont Ventoux',
      'FR',
      44.174,
      5.2789,
      'Surnommé le « Géant de Provence », il a vu le cycliste britannique Tom Simpson s’effondrer et mourir près de son sommet lors du Tour de France 1967.',
      'Mont_Ventoux',
      'Mont_Ventoux',
    ),
    mountain(
      'Aiguille du Midi',
      'FR',
      45.8787,
      6.8875,
      'Son téléphérique, inauguré en 1955, hisse les visiteurs à 3 842 m et fut longtemps le plus haut du monde.',
      'Aiguille_du_Midi',
      'Aiguille_du_Midi',
    ),
    mountain(
      'Kangchenjunga',
      'NP',
      27.7025,
      88.1475,
      'Troisième sommet du monde à 8 586 m, il a été gravi pour la première fois le 25 mai 1955 par Joe Brown et George Band, qui se sont arrêtés quelques mètres sous le point culminant par respect pour les croyances locales.',
      'Kangchenjunga',
      'Kangchenjunga',
    ),
    mountain(
      'Mont Kenya',
      'KE',
      -0.1521,
      37.3084,
      'Deuxième plus haut sommet d’Afrique, à 5 199 m, il a été gravi pour la première fois en 1899 par le géographe britannique Halford Mackinder.',
      'Mont_Kenya',
      'Mount_Kenya',
    ),
    mountain(
      'Elbrouz',
      'RU',
      43.3499,
      42.4453,
      'Volcan éteint culminant à 5 642 m, c’est le point le plus élevé d’Europe, devant le Mont Blanc.',
      'Elbrouz',
      'Mount_Elbrus',
    ),
    mountain(
      'Jungfrau',
      'CH',
      46.5368,
      7.9626,
      'Gravie pour la première fois en 1811 par les frères Rudolf et Hieronymus Meyer, elle abrite la gare ferroviaire la plus haute d’Europe, le Jungfraujoch, ouverte en 1912.',
      'Jungfrau',
      'Jungfrau',
    ),
    mountain(
      'Monte Rosa',
      'IT',
      45.9369,
      7.8668,
      'Son point culminant, la Pointe Dufour (4 634 m), doit son nom au général suisse Guillaume-Henri Dufour ; c’est le deuxième plus haut sommet des Alpes après le Mont Blanc.',
      'Monte_Rosa',
      'Monte_Rosa',
    ),
    mountain(
      'Grossglockner',
      'AT',
      47.0742,
      12.6939,
      'Point culminant de l’Autriche, à 3 798 m, il a été gravi pour la première fois en 1800 lors d’une expédition organisée par l’évêque de Gurk.',
      'Grossglockner',
      'Grossglockner',
    ),
    mountain(
      'Zugspitze',
      'DE',
      47.4211,
      10.9853,
      'Point culminant de l’Allemagne à 2 962 m, son sommet est partagé avec l’Autriche.',
      'Zugspitze',
      'Zugspitze',
    ),
    mountain(
      'Galdhøpiggen',
      'NO',
      61.6365,
      8.3125,
      'Point culminant de la Norvège et de toute la Scandinavie, à 2 469 m.',
      'Galdhøpiggen',
      'Galdhøpiggen',
    ),
    mountain(
      'Mulhacén',
      'ES',
      37.0535,
      -3.3116,
      'Point culminant de l’Espagne continentale, à 3 479 m, il doit son nom à Muley Hacén, dernier sultan de Grenade, qui y aurait été enterré selon la légende.',
      'Mulhacén',
      'Mulhacén',
    ),
    mountain(
      'Mont Cook',
      'NZ',
      -43.595,
      170.1418,
      'Point culminant de la Nouvelle-Zélande, aussi appelé Aoraki, où Edmund Hillary s’entraînait avant de gravir l’Everest.',
      'Aoraki/Mont_Cook',
      'Aoraki_/_Mount_Cook',
    ),
    mountain(
      'Mont Kosciuszko',
      'AU',
      -36.4559,
      148.2636,
      'Point culminant de l’Australie continentale, il fut nommé en 1840 par l’explorateur polonais Paul Strzelecki en hommage au héros national polonais Tadeusz Kościuszko.',
      'Mont_Kosciuszko',
      'Mount_Kosciuszko',
    ),
    mountain(
      'Mauna Kea',
      'US',
      19.8207,
      -155.4681,
      'Mesuré depuis sa base océanique, c’est la plus haute montagne du monde avec plus de 10 000 m, dont la majeure partie reste immergée.',
      'Mauna_Kea',
      'Mauna_Kea',
    ),
    mountain(
      'Popocatépetl',
      'MX',
      19.0225,
      -98.6278,
      'Son nom signifie « montagne qui fume » en nahuatl ; ce volcan actif est régulièrement surveillé pour ses émissions de cendres.',
      'Popocatépetl',
      'Popocatépetl',
    ),
    mountain(
      'Teide',
      'ES',
      28.2717,
      -16.6423,
      'Point culminant de l’Espagne à 3 715 m, c’est aussi le troisième plus haut volcan du monde mesuré depuis sa base.',
      'Teide',
      'Teide',
    ),
    mountain(
      'Toubkal',
      'MA',
      31.0595,
      -7.9151,
      'Point culminant de l’Afrique du Nord, à 4 167 m, il domine le massif du Haut Atlas.',
      'Toubkal',
      'Toubkal',
    ),
    mountain(
      'Mont Ararat',
      'TR',
      39.7019,
      44.2983,
      'Selon la tradition biblique, c’est sur ses flancs que l’arche de Noé se serait échouée après le déluge.',
      'Mont_Ararat',
      'Mount_Ararat',
    ),
    mountain(
      'Snowdon',
      'GB',
      53.0685,
      -4.0765,
      'Point culminant du pays de Galles, à 1 085 m, il est connu en gallois sous le nom d’Yr Wyddfa.',
      'Snowdon',
      'Snowdon',
    ),
    mountain(
      'Krakatoa',
      'ID',
      -6.102,
      105.423,
      'L’explosion de son éruption de 1883 a été entendue jusqu’à près de 4 800 km de distance, sur l’île Rodrigues dans l’océan Indien.',
      'Krakatoa',
      'Krakatoa',
    ),
    mountain(
      'Hallasan',
      'KR',
      33.3617,
      126.5292,
      'Point culminant de la Corée du Sud, à 1 947 m, ce volcan bouclier de l’île de Jeju abrite un lac de cratère à son sommet.',
      'Hallasan',
      'Hallasan',
    ),
    mountain(
      'Mont Elbert',
      'US',
      39.1178,
      -106.4454,
      'Point culminant des montagnes Rocheuses et de l’État du Colorado, à 4 401 m.',
      'Mont_Elbert',
      'Mount_Elbert',
    ),
    mountain(
      'Mont Hood',
      'US',
      45.3736,
      -121.696,
      'Point culminant de l’Oregon, ce stratovolcan encore actif est visible depuis Portland par temps clair.',
      'Mont_Hood',
      'Mount_Hood',
    ),
    mountain(
      'Mont Shasta',
      'US',
      41.4092,
      -122.1949,
      'Ce stratovolcan de la chaîne des Cascades, en Californie, est l’un des plus volumineux des États-Unis.',
      'Mont_Shasta',
      'Mount_Shasta',
    ),
    mountain(
      'Mauna Loa',
      'US',
      19.4721,
      -155.6026,
      'C’est le plus grand volcan actif du monde en volume, couvrant à lui seul la moitié de l’île d’Hawaï.',
      'Mauna_Loa',
      'Mauna_Loa',
    ),
    mountain(
      'Mont Taranaki',
      'NZ',
      -39.2969,
      174.0642,
      'Son cône volcanique presque parfait lui a valu de doubler le mont Fuji dans plusieurs films, dont Le Dernier Samouraï.',
      'Taranaki_Maunga',
      'Mount_Taranaki',
    ),
    mountain(
      'Feldberg',
      'DE',
      47.8744,
      8.0044,
      'Point culminant de la Forêt-Noire, à 1 493 m.',
      'Feldberg_(Forêt-Noire)',
      'Feldberg_(Black_Forest)',
    ),
    mountain(
      'Brocken',
      'DE',
      51.7991,
      10.6156,
      'Point culminant du massif du Harz, il est associé aux légendes de sorcières de la nuit de Walpurgis et au phénomène optique du « spectre de Brocken ».',
      'Brocken',
      'Brocken',
    ),
  ]),

  ...hard([
    mountain(
      'Puy de Sancy',
      'FR',
      45.5286,
      2.8143,
      'Point culminant du Massif central et de la chaîne des Puys, à 1 885 m.',
      'Puy_de_Sancy',
      'Puy_de_Sancy',
    ),
    mountain(
      'Pic du Midi de Bigorre',
      'FR',
      42.9369,
      0.1425,
      'Son observatoire astronomique, fondé en 1878, en fait l’un des plus hauts observatoires de montagne d’Europe.',
      'Pic_du_Midi_de_Bigorre',
      'Pic_du_Midi_de_Bigorre',
    ),
    mountain(
      'Vignemale',
      'FR',
      42.7719,
      -0.1447,
      'Point culminant des Pyrénées françaises, à 3 298 m.',
      'Vignemale',
      'Vignemale',
    ),
    mountain(
      'La Meije',
      'FR',
      45.0044,
      6.3061,
      'Dernier grand sommet des Alpes à être vaincu, le 16 août 1877, par Emmanuel Boileau de Castelnau accompagné du guide Pierre Gaspard et de son fils.',
      'La_Meije',
      'Meije',
    ),
    mountain(
      'Canigou',
      'FR',
      42.5187,
      2.4569,
      'Montagne sacrée des Catalans, son sommet accueille chaque 23 juin les feux de la Saint-Jean, dont les flammes redescendent ensuite embraser villages et villes.',
      'Canigou',
      'Canigou',
    ),
    mountain(
      'Monte Cinto',
      'FR',
      42.3803,
      8.9486,
      'Point culminant de la Corse, à 2 706 m.',
      'Monte_Cinto',
      'Monte_Cinto',
    ),
    mountain(
      'Barre des Écrins',
      'FR',
      44.9219,
      6.3597,
      'À 4 102 m, c’est le seul sommet de plus de 4 000 m des Alpes françaises situé hors du massif du Mont-Blanc.',
      'Barre_des_Écrins',
      'Barre_des_Écrins',
    ),
    mountain(
      'Grand Ballon',
      'FR',
      47.9006,
      7.1017,
      'Point culminant des Vosges, à 1 424 m.',
      'Grand_Ballon',
      'Grand_Ballon',
    ),
    mountain(
      'Mont Aigoual',
      'FR',
      44.1214,
      3.5811,
      'Sa station météorologique, en service depuis 1894, est réputée pour être l’une des plus arrosées et venteuses de France.',
      'Mont_Aigoual',
      'Mont_Aigoual',
    ),
    mountain(
      'Ballon d’Alsace',
      'FR',
      47.8203,
      6.8412,
      'Il fut en 1905 le tout premier col de montagne franchi par le Tour de France.',
      "Ballon_d'Alsace",
      "Ballon_d'Alsace",
    ),
    mountain(
      'Lhotse',
      'NP',
      27.9617,
      86.9333,
      'Quatrième sommet du monde à 8 516 m, il est relié à l’Everest par la face sud et le col Sud.',
      'Lhotse',
      'Lhotse',
    ),
    mountain(
      'Makalu',
      'NP',
      27.8897,
      87.0889,
      'Cinquième sommet du monde, sa silhouette pyramidale à quatre arêtes en fait l’un des 8 000 les plus techniques à gravir.',
      'Makalu',
      'Makalu',
    ),
    mountain(
      'Manaslu',
      'NP',
      28.55,
      84.5597,
      'Son nom signifie « montagne de l’esprit » en sanskrit ; c’est le huitième plus haut sommet du monde.',
      'Manaslu',
      'Manaslu',
    ),
    mountain(
      'Dhaulagiri',
      'NP',
      28.6967,
      83.4917,
      'Septième sommet du monde, son nom signifie « montagne blanche » en sanskrit.',
      'Dhaulagiri',
      'Dhaulagiri',
    ),
    mountain(
      'Nanga Parbat',
      'PK',
      35.2428,
      74.5892,
      'Surnommée la « montagne tueuse » pour le nombre d’alpinistes morts lors des premières tentatives, elle a finalement été vaincue en 1953 par l’Autrichien Hermann Buhl, seul et sans oxygène.',
      'Nanga_Parbat',
      'Nanga_Parbat',
    ),
    mountain(
      'Mont Logan',
      'CA',
      60.5672,
      -140.4055,
      'Point culminant du Canada, à 5 959 m, il posséderait la plus grande base de toutes les montagnes non volcaniques du monde.',
      'Mont_Logan',
      'Mount_Logan',
    ),
    mountain(
      'Pico de Orizaba',
      'MX',
      19.0304,
      -97.2683,
      'Point culminant du Mexique et troisième d’Amérique du Nord, ce volcan culmine à 5 636 m.',
      'Pico_de_Orizaba',
      'Pico_de_Orizaba',
    ),
    mountain(
      'Chimborazo',
      'EC',
      -1.4692,
      -78.8175,
      'En raison du renflement équatorial de la Terre, son sommet est le point du globe le plus éloigné du centre de la planète, devant l’Everest.',
      'Chimborazo',
      'Chimborazo',
    ),
    mountain(
      'Ojos del Salado',
      'CL',
      -27.1085,
      -68.5411,
      'C’est le plus haut volcan du monde, culminant à 6 893 m à la frontière entre le Chili et l’Argentine.',
      'Ojos_del_Salado',
      'Ojos_del_Salado',
    ),
    mountain('Aneto', 'ES', 42.6289, 0.6597, 'Point culminant des Pyrénées, à 3 404 m.', 'Aneto', 'Aneto'),
    mountain(
      'Triglav',
      'SI',
      46.3781,
      13.8378,
      'Point culminant de la Slovénie, sa silhouette à trois sommets figure sur le drapeau et les armoiries du pays.',
      'Triglav',
      'Triglav',
    ),
    mountain(
      'Puncak Jaya',
      'ID',
      -4.0784,
      137.1587,
      'Point culminant de l’Océanie, il porte l’un des rares glaciers tropicaux permanents au monde malgré sa proximité avec l’équateur.',
      'Puncak_Jaya',
      'Puncak_Jaya',
    ),
    mountain(
      'Half Dome',
      'US',
      37.7459,
      -119.5332,
      'Ce dôme de granite de la vallée de Yosemite, taillé par les glaciers, se termine par une face verticale gravie à l’aide de câbles fixes sur sa voie normale.',
      'Half_Dome',
      'Half_Dome',
    ),
    mountain(
      'Grand Teton',
      'US',
      43.741,
      -110.8023,
      'Point culminant de la chaîne des Teton, au Wyoming, il domine de près de 2 100 m la vallée de Jackson Hole.',
      'Grand_Teton',
      'Grand_Teton',
    ),
    mountain(
      'Mont Whitney',
      'US',
      36.5786,
      -118.2923,
      'Point culminant des États-Unis contigus à 4 421 m, il se trouve à moins de 150 km de la Vallée de la Mort, point le plus bas du pays.',
      'Mont_Whitney',
      'Mount_Whitney',
    ),
    mountain(
      'Damavand',
      'IR',
      35.9558,
      52.1099,
      'Point culminant de l’Iran et du Moyen-Orient, ce volcan est une figure centrale de la mythologie perse.',
      'Damavand',
      'Damavand',
    ),
    mountain(
      'Kinabalu',
      'MY',
      6.0754,
      116.5583,
      'Point culminant de Bornéo et de la Malaisie, il abrite une biodiversité exceptionnelle classée au patrimoine mondial de l’UNESCO.',
      'Mont_Kinabalu',
      'Mount_Kinabalu',
    ),
    mountain(
      'Ortler',
      'IT',
      46.5081,
      10.5453,
      'Point culminant du Tyrol du Sud, il a longtemps marqué la frontière entre l’Autriche-Hongrie et l’Italie.',
      'Ortler',
      'Ortler',
    ),
    mountain(
      'Marmolada',
      'IT',
      46.4342,
      11.8578,
      'Surnommée la « Reine des Dolomites », elle abrite le plus grand glacier du massif, aujourd’hui en fort recul.',
      'Marmolada',
      'Marmolada',
    ),
    mountain(
      'Gran Paradiso',
      'IT',
      45.5169,
      7.2653,
      'Ancienne réserve de chasse du roi Victor-Emmanuel II, il est devenu en 1922 le premier parc national d’Italie.',
      'Gran_Paradiso',
      'Gran_Paradiso',
    ),
    mountain(
      'Watzmann',
      'DE',
      47.5567,
      12.9214,
      'La légende bavaroise raconte qu’un roi cruel et sa famille y furent pétrifiés en punition de leurs crimes.',
      'Watzmann',
      'Watzmann',
    ),
    mountain(
      'Wildspitze',
      'AT',
      46.8833,
      10.8672,
      'Deuxième plus haut sommet d’Autriche, après le Grossglockner.',
      'Wildspitze',
      'Wildspitze',
    ),
    mountain(
      'Dachstein',
      'AT',
      47.4747,
      13.6058,
      'Ce massif calcaire abrite un vaste réseau de grottes de glace ouvertes au public.',
      'Dachstein',
      'Dachstein',
    ),
    mountain(
      'Monte Perdido',
      'ES',
      42.6814,
      -0.0367,
      'Ce sommet calcaire du parc national d’Ordesa abrite l’un des glaciers les plus méridionaux d’Europe.',
      'Monte_Perdido',
      'Monte_Perdido',
    ),
    mountain(
      'Scafell Pike',
      'GB',
      54.4542,
      -3.2103,
      'Point culminant de l’Angleterre, à 978 m seulement.',
      'Scafell_Pike',
      'Scafell_Pike',
    ),
    mountain(
      'Carrauntoohil',
      'IE',
      52.0,
      -9.7461,
      'Point culminant de l’Irlande, à 1 038 m.',
      'Carrauntoohil',
      'Carrauntoohil',
    ),
    mountain(
      'Kebnekaise',
      'SE',
      67.9008,
      18.5444,
      'Point culminant de la Suède ; son sommet glaciaire, qui fond chaque année, a cédé sa place de plus haut sommet à un pic voisin resté rocheux.',
      'Kebnekaise',
      'Kebnekaise',
    ),
    mountain(
      'Kazbek',
      'GE',
      42.6975,
      44.5183,
      'Ce volcan endormi du Caucase serait, selon la mythologie grecque, le lieu où Prométhée fut enchaîné pour avoir offert le feu aux hommes.',
      'Kazbek',
      'Kazbek',
    ),
    mountain(
      'Nanda Devi',
      'IN',
      30.3831,
      79.9707,
      'Plus haut sommet situé entièrement en Inde, il est entouré d’un sanctuaire naturel longtemps interdit d’accès aux alpinistes.',
      'Nanda_Devi',
      'Nanda_Devi',
    ),
    mountain(
      'Gongga',
      'CN',
      29.5964,
      101.8794,
      'Point culminant de la province chinoise du Sichuan, surnommé le « roi des montagnes du Sichuan ».',
      'Minya_Konka',
      'Mount_Gongga',
    ),
    mountain(
      'Yu Shan',
      'TW',
      23.4707,
      120.9576,
      'Point culminant de Taïwan, il dépasse le mont Fuji de plusieurs centaines de mètres.',
      'Yu_Shan',
      'Yushan_(mountain)',
    ),
    mountain(
      'Fansipan',
      'VN',
      22.3033,
      103.7749,
      'Point culminant du Viêt Nam et de toute la péninsule indochinoise.',
      'Fansipan',
      'Fansipan',
    ),
    mountain(
      'Doi Inthanon',
      'TH',
      18.5883,
      98.4867,
      'Point culminant de la Thaïlande, il est surnommé le « toit du Siam ».',
      'Doi_Inthanon',
      'Doi_Inthanon',
    ),
    mountain(
      'Gunung Agung',
      'ID',
      -8.3425,
      115.5075,
      'Ce volcan sacré de Bali est considéré par les Balinais comme la demeure des dieux.',
      'Agung',
      'Mount_Agung',
    ),
    mountain(
      'Semeru',
      'ID',
      -8.1077,
      112.922,
      'Point culminant de Java, c’est l’un des volcans les plus actifs d’Indonésie, avec des explosions quasi quotidiennes.',
      'Semeru',
      'Semeru',
    ),
    mountain(
      'Merapi',
      'ID',
      -7.5407,
      110.4457,
      'L’un des volcans les plus actifs d’Indonésie, il domine directement la ville de Yogyakarta et ses millions d’habitants.',
      'Merapi',
      'Merapi',
    ),
    mountain(
      'Mayon',
      'PH',
      13.2572,
      123.6856,
      'Ce volcan est réputé pour son cône presque parfaitement symétrique.',
      'Mayon',
      'Mayon',
    ),
    mountain(
      'Mont Cameroun',
      'CM',
      4.2036,
      9.1706,
      'Point culminant d’Afrique de l’Ouest, ce volcan actif domine directement le golfe de Guinée.',
      'Mont_Cameroun',
      'Mount_Cameroon',
    ),
    mountain(
      'Ras Dashen',
      'ET',
      13.2603,
      38.4172,
      'Point culminant de l’Éthiopie, dans le massif du Simien.',
      'Ras_Dashan',
      'Ras_Dashen',
    ),
    mountain(
      'Mont Kailash',
      'CN',
      31.0672,
      81.3119,
      'Sacré pour quatre religions (hindouisme, bouddhisme, jaïnisme et bön), il n’a jamais été officiellement gravi par respect pour sa signification spirituelle.',
      'Mont_Kailash',
      'Mount_Kailash',
    ),
    mountain(
      'Huangshan',
      'CN',
      30.1306,
      118.1667,
      'Célèbre pour ses pitons de granite, ses pins tordus et ses mers de nuages, il a inspiré des siècles de peinture et de poésie chinoises.',
      'Huangshan',
      'Huangshan',
    ),
    mountain(
      'Mont Paektu',
      'KP',
      42.0057,
      128.0558,
      'Son cratère abrite le lac Chon, l’un des lacs de cratère les plus profonds du monde ; la propagande nord-coréenne en a fait le lieu de naissance de Kim Jong-il.',
      'Mont_Paektu',
      'Mount_Paektu',
    ),
    mountain(
      'Longs Peak',
      'US',
      40.2549,
      -105.6151,
      'Point culminant du parc national des Rocheuses, dans le Colorado.',
      'Longs_Peak',
      'Longs_Peak',
    ),
    mountain(
      'Pikes Peak',
      'US',
      38.8409,
      -105.0423,
      'La vue depuis son sommet a inspiré à Katharine Lee Bates le poème devenu en musique la chanson patriotique America the Beautiful, en 1893.',
      'Pikes_Peak',
      'Pikes_Peak',
    ),
    mountain(
      'Mont Robson',
      'CA',
      53.1217,
      -119.1553,
      'Point culminant des Rocheuses canadiennes.',
      'Mont_Robson',
      'Mount_Robson',
    ),
    mountain(
      'Villarrica',
      'CL',
      -39.42,
      -71.93,
      'L’un des volcans les plus actifs d’Amérique du Sud, il abrite un lac de lave visible depuis son sommet.',
      undefined,
      'Villarrica_(volcano)',
    ),
    mountain(
      'Pichincha',
      'EC',
      -0.1707,
      -78.5983,
      'Ce volcan actif surplombe directement Quito, la capitale équatorienne.',
      'Guagua_Pichincha',
      'Pichincha_(volcano)',
    ),
    mountain(
      'Roraima',
      'VE',
      5.1433,
      -60.7625,
      'Ce tepui aux parois verticales, isolé au sommet plat, a inspiré à Arthur Conan Doyle son roman Le Monde perdu.',
      'Mont_Roraima',
      'Mount_Roraima',
    ),
    mountain(
      'Pico Duarte',
      'DO',
      19.0225,
      -71.0803,
      'Point culminant des Caraïbes, à 3 098 m.',
      'Pico_Duarte',
      'Pico_Duarte',
    ),
    mountain(
      'Mont Meru',
      'TZ',
      -3.2411,
      36.7508,
      'Ce volcan voisin du Kilimandjaro offre l’un des meilleurs points de vue sur son célèbre voisin.',
      undefined,
      'Mount_Meru_(Tanzania)',
    ),
    mountain(
      'Nevado del Ruiz',
      'CO',
      4.8955,
      -75.3217,
      'Son éruption du 13 novembre 1985 a provoqué des coulées de boue qui ont enseveli la ville d’Armero, faisant environ 25 000 morts.',
      'Nevado_del_Ruiz',
      'Nevado_del_Ruiz',
    ),
    mountain(
      'Illimani',
      'BO',
      -16.6547,
      -67.7864,
      'Ce sommet enneigé domine La Paz, la capitale administrative bolivienne.',
      'Illimani',
      'Illimani',
    ),
    mountain(
      'Fitz Roy',
      'AR',
      -49.271,
      -73.0417,
      'Sa silhouette acérée, prisée des grimpeurs pour la difficulté de ses voies, a inspiré le logo de la marque de vêtements Patagonia.',
      'Mont_Fitz_Roy',
      'Fitz_Roy',
    ),
    mountain(
      'Mont Ruapehu',
      'NZ',
      -39.2807,
      175.5678,
      'Ce volcan actif a servi de décor extérieur au Mordor et à la Montagne du Destin dans la trilogie cinématographique Le Seigneur des Anneaux.',
      'Ruapehu',
      'Mount_Ruapehu',
    ),
    mountain(
      'Gasherbrum I',
      'PK',
      35.7245,
      76.6963,
      'Onzième plus haut sommet du monde, il est aussi appelé « Hidden Peak » car il reste invisible depuis les vallées environnantes.',
      'Gasherbrum_I',
      'Gasherbrum_I',
    ),
    mountain(
      'Broad Peak',
      'PK',
      35.8113,
      76.5658,
      'Douzième sommet du monde, il doit son nom à sa large arête sommitale.',
      'Broad_Peak',
      'Broad_Peak',
    ),
  ]),

  ...master([
    mountain(
      'Puy Mary',
      'FR',
      45.1167,
      2.6833,
      'Ce piton volcanique du Cantal est un vestige érodé de l’un des plus grands stratovolcans jamais actifs en Europe.',
      'Puy_Mary',
      'Puy_Mary',
    ),
    mountain(
      'Mont Gerbier de Jonc',
      'FR',
      44.8347,
      4.2181,
      'À son pied jaillit l’une des sources traditionnellement retenues pour celle de la Loire, le plus long fleuve de France.',
      'Mont_Gerbier_de_Jonc',
      'Mont_Gerbier_de_Jonc',
    ),
    mountain(
      'Pic de Bugarach',
      'FR',
      42.8503,
      2.4067,
      'Ce sommet des Corbières est devenu tristement célèbre en 2012, certains le croyant refuge providentiel pour la fin du monde annoncée par le calendrier maya.',
      'Pic_de_Bugarach',
      'Pic_de_Bugarach',
    ),
    mountain(
      'Mont Pelvoux',
      'FR',
      44.9236,
      6.4064,
      'Situé dans le massif des Écrins, il fut longtemps considéré comme le point culminant du massif avant que la Barre des Écrins ne le détrône.',
      'Mont_Pelvoux',
      'Mont_Pelvoux',
    ),
    mountain(
      'Pic d’Anie',
      'FR',
      42.9539,
      -0.7422,
      'Ce sommet calcaire des Pyrénées béarnaises est réputé pour son relief karstique et son lapiaz sommital.',
      "Pic_d'Anie",
      "Pic_d'Anie",
    ),
    mountain(
      'Piz Bernina',
      'CH',
      46.3806,
      9.9089,
      'Seul sommet de plus de 4 000 m des Alpes orientales.',
      'Piz_Bernina',
      'Piz_Bernina',
    ),
    mountain(
      'Musala',
      'BG',
      42.1811,
      23.5867,
      'Point culminant de la Bulgarie et de toute la péninsule balkanique, à 2 925 m.',
      'Musala',
      'Musala',
    ),
    mountain(
      'Moldoveanu',
      'RO',
      45.6039,
      24.7369,
      'Point culminant de la Roumanie, dans les Carpates méridionales.',
      'Moldoveanu',
      'Moldoveanu_Peak',
    ),
    mountain(
      'Gerlachovský štít',
      'SK',
      49.1697,
      20.1381,
      'Point culminant de la Slovaquie et de toute la chaîne des Carpates.',
      'Gerlachovský_štít',
      'Gerlachovský_štít',
    ),
    mountain(
      'Śnieżka',
      'PL',
      50.7361,
      15.74,
      'Point culminant des monts des Géants, à la frontière entre Pologne et République tchèque, associé dans le folklore local à l’esprit de la montagne Rübezahl.',
      'Sniejka',
      'Sněžka',
    ),
    mountain(
      'Pico do Fogo',
      'CV',
      14.9481,
      -24.3592,
      'Ce volcan actif, point culminant du Cap-Vert, a détruit une partie de son propre village lors de son éruption de 2014.',
      'Pico_do_Fogo',
      'Pico_do_Fogo',
    ),
    mountain(
      'Rinjani',
      'ID',
      -8.4109,
      116.4573,
      'Ce volcan de l’île de Lombok abrite dans sa caldeira un lac en forme de croissant et un cône volcanique plus jeune, encore actif.',
      undefined,
      'Mount_Rinjani',
    ),
    mountain('Mont Apo', 'PH', 6.9875, 125.2725, 'Point culminant des Philippines.', 'Mont_Apo', 'Mount_Apo'),
    mountain(
      'Mont Maudit',
      'FR',
      45.8467,
      6.8842,
      'Ce sommet du massif du Mont-Blanc doit son nom à la réputation dangereuse de ses pentes, longtemps évitées par les premiers alpinistes.',
      'Mont_Maudit',
      'Mont_Maudit',
    ),
    mountain(
      'Grande Casse',
      'FR',
      45.4131,
      6.7647,
      'Point culminant du massif de la Vanoise, premier parc national créé en France, en 1963.',
      'Grande_Casse',
      'Grande_Casse',
    ),
    mountain(
      'Aiguille Verte',
      'FR',
      45.9298,
      6.9903,
      'Ce sommet du massif du Mont-Blanc fut gravi pour la première fois en 1865 par l’Anglais Edward Whymper, la même année que sa célèbre ascension du Cervin.',
      'Aiguille_Verte',
      'Aiguille_Verte',
    ),
    mountain(
      'Piz Palü',
      'CH',
      46.3908,
      9.9497,
      'Ce sommet des Alpes grisonnes est réputé pour ses trois pointes glaciaires bien distinctes.',
      'Piz_Palü',
      'Piz_Palü',
    ),
    mountain(
      'Piz Buin',
      'AT',
      46.8494,
      10.1128,
      'Ce sommet à cheval entre l’Autriche et la Suisse a donné son nom à une célèbre marque de crème solaire, créée après une expédition sur ses pentes dans les années 1930.',
      'Piz_Buin',
      'Piz_Buin',
    ),
    mountain(
      'Posets',
      'ES',
      42.6497,
      0.4275,
      'Deuxième plus haut sommet des Pyrénées après l’Aneto.',
      'Posets',
      'Posets',
    ),
    mountain(
      'Pico Almanzor',
      'ES',
      40.2308,
      -5.3639,
      'Point culminant de la Sierra de Gredos, en Espagne centrale.',
      undefined,
      'Pico_Almanzor',
    ),
    mountain(
      'Veleta',
      'ES',
      37.0561,
      -3.3661,
      'Ce sommet de la Sierra Nevada abrite l’une des stations de ski les plus méridionales d’Europe.',
      undefined,
      'Veleta_(Sierra_Nevada)',
    ),
    mountain(
      'Halti',
      'FI',
      69.3167,
      21.3167,
      'Point culminant de la Finlande, tout en haut du « bras » qui s’avance dans le nord de la Scandinavie.',
      'Halti',
      'Halti',
    ),
    mountain(
      'Hvannadalshnúkur',
      'IS',
      64.0158,
      -16.6847,
      'Point culminant de l’Islande, ce pic se dresse au sommet du volcan Öræfajökull, sous la calotte glaciaire du Vatnajökull.',
      'Hvannadalshnúkur',
      'Hvannadalshnúkur',
    ),
    mountain(
      'Vihren',
      'BG',
      41.7675,
      23.4,
      'Deuxième plus haut sommet de Bulgarie, dans le massif du Pirin.',
      'Vihren',
      'Vihren',
    ),
    mountain(
      'Maja Jezercë',
      'AL',
      42.4522,
      19.7908,
      'Point culminant de l’Albanie, dans les Alpes albanaises surnommées les « Alpes maudites ».',
      'Maja_Jezercë',
      'Maja_Jezercë',
    ),
    mountain(
      'Shkhara',
      'GE',
      42.9908,
      43.1119,
      'L’un des plus hauts sommets du Caucase, à la frontière entre la Géorgie et la Russie.',
      'Chkhara',
      'Shkhara',
    ),
    mountain(
      'Trisul',
      'IN',
      30.3167,
      79.7667,
      'Ce sommet himalayen doit son nom au trident de Shiva, qu’évoquent ses trois pics.',
      'Trisul',
      'Trisul',
    ),
    mountain(
      'Namcha Barwa',
      'CN',
      29.6306,
      95.0561,
      'Avec 7 782 m, c’est le point culminant de l’extrémité orientale de l’Himalaya, là où le fleuve Yarlung Tsangpo effectue un coude spectaculaire.',
      'Namcha_Barwa',
      'Namcha_Barwa',
    ),
    mountain(
      'Gangkhar Puensum',
      'BT',
      28.0453,
      90.4633,
      'Avec 7 570 m, c’est la plus haute montagne du monde encore jamais gravie : le Bhoutan interdit depuis 1994 toute ascension au-dessus de 6 000 m par respect des croyances locales.',
      'Gangkhar_Puensum',
      'Gangkhar_Puensum',
    ),
    mountain(
      'Mont Elgon',
      'UG',
      1.1361,
      34.5597,
      'Ce volcan éteint abrite l’une des plus grandes calderas du monde.',
      'Mont_Elgon',
      'Mount_Elgon',
    ),
    mountain(
      'Pic Marguerite (Mont Stanley)',
      'CD',
      0.3789,
      29.8703,
      'Avec 5 109 m, c’est le troisième plus haut sommet d’Afrique après le Kilimandjaro et le mont Kenya, malgré sa position presque exactement sur l’équateur.',
      'Pic_Marguerite',
      'Margherita_Peak',
    ),
    mountain(
      'Mont Mulanje',
      'MW',
      -15.9578,
      35.6014,
      'Point culminant du Malawi, ce massif granitique isolé émerge abruptement des plaines environnantes.',
      undefined,
      'Mulanje_Massif',
    ),
    mountain(
      'Nyiragongo',
      'CD',
      -1.52,
      29.25,
      'Son cratère abrite l’un des plus grands lacs de lave permanents du monde.',
      'Nyiragongo',
      'Mount_Nyiragongo',
    ),
    mountain(
      'Emi Koussi',
      'TD',
      19.7925,
      18.5514,
      'Point culminant du Sahara, ce volcan bouclier du massif du Tibesti s’élève à plus de 3 000 m au-dessus des plaines désertiques environnantes.',
      'Emi_Koussi',
      'Emi_Koussi',
    ),
    mountain(
      'Pico Bolívar',
      'VE',
      8.5453,
      -71.0342,
      'Point culminant du Venezuela, dans la cordillère de Mérida.',
      'Pico_Bolívar',
      'Pico_Bolívar',
    ),
    mountain(
      'Cayambe',
      'EC',
      0.0294,
      -77.9861,
      'C’est le seul endroit au monde où l’équateur terrestre traverse un point couvert de neiges permanentes.',
      'Cayambe_(volcan)',
      'Cayambe_(volcano)',
    ),
    mountain(
      'Sajama',
      'BO',
      -18.1097,
      -68.8814,
      'Point culminant de la Bolivie, ce volcan isolé se dresse au milieu de l’Altiplano.',
      'Sajama',
      'Sajama',
    ),
    mountain(
      'Cerro Torre',
      'AR',
      -49.3319,
      -73.1042,
      'L’ascension revendiquée en 1959 par Cesare Maestri a longtemps été considérée comme la première, avant d’être largement remise en cause ; la première ascension incontestée date de 1974.',
      'Cerro_Torre',
      'Cerro_Torre',
    ),
    mountain(
      'Mont Waddington',
      'CA',
      51.3733,
      -125.2644,
      'Point culminant de la chaîne Côtière, en Colombie-Britannique.',
      'Mont_Waddington',
      'Mount_Waddington',
    ),
    mountain(
      'Gunnbjørn Fjeld',
      'GL',
      68.9202,
      -29.8964,
      'Point culminant du Groenland et de tout l’Arctique, à 3 694 m.',
      undefined,
      'Gunnbjørn_Fjeld',
    ),
    mountain(
      'Mont Wilhelm',
      'PG',
      -5.7789,
      145.0294,
      'Point culminant de la Papouasie-Nouvelle-Guinée.',
      'Mont_Wilhelm',
      'Mount_Wilhelm',
    ),
    mountain(
      'Mont Bartle Frere',
      'AU',
      -17.3833,
      145.8167,
      'Point culminant du Queensland, dans la forêt tropicale australienne.',
      'Mont_Bartle_Frere',
      'Mount_Bartle_Frere',
    ),
    mountain(
      'Mont Meharry',
      'AU',
      -22.9833,
      118.8333,
      'Point culminant de l’Australie-Occidentale, dans la chaîne Hamersley.',
      undefined,
      'Mount_Meharry',
    ),
  ]),
];
