import type { Place } from '@/types';

import { placeFactory, tier } from './helpers';

const nature = placeFactory('nature');
const easy = tier('easy');
const intermediate = tier('intermediate');
const hard = tier('hard');
const master = tier('master');

export const NATURE: Place[] = [
  ...easy([
    nature(
      'Dune du Pilat',
      'France',
      'FR',
      44.5895,
      -1.213,
      'Plus haute dune d’Europe, elle culmine autour de 105 m et continue de progresser vers l’intérieur des terres au fil des ans.',
    ),
    nature(
      'Gorges du Verdon',
      'France',
      'FR',
      43.7369,
      6.3268,
      'Longues d’environ 25 km, elles atteignent jusqu’à 700 m de profondeur.',
    ),
    nature(
      'Falaises d’Étretat',
      'France',
      'FR',
      49.7073,
      0.205,
      'Ses falaises et son aiguille ont inspiré Claude Monet, Guy de Maupassant et Maurice Leblanc, qui y a caché le trésor d’Arsène Lupin dans « L’Aiguille creuse » (1909).',
    ),
    nature(
      'Camargue',
      'France',
      'FR',
      43.4528,
      4.4283,
      'Zone humide d’importance internationale classée site Ramsar depuis 1986, elle abrite l’une des rares populations européennes de flamants roses.',
    ),
    nature(
      'Grand Canyon',
      'États-Unis',
      'US',
      36.1069,
      -112.1129,
      'Protégé comme monument national dès 1908 à l’initiative de Theodore Roosevelt, il n’est devenu parc national qu’en 1919.',
    ),
    nature(
      'Yellowstone',
      'États-Unis',
      'US',
      44.428,
      -110.5885,
      'Créé le 1er mars 1872, c’est le plus ancien parc national du monde.',
    ),
    nature(
      'Chutes du Niagara',
      'Canada',
      'CA',
      43.0962,
      -79.0377,
      'En 1901, Annie Edson Taylor est devenue la première personne à descendre les chutes dans un tonneau et à en réchapper.',
    ),
    nature(
      'Chutes Victoria',
      'Zimbabwe',
      'ZW',
      -17.9243,
      25.8572,
      'L’explorateur David Livingstone en a été le premier Européen témoin le 16 novembre 1855, les nommant en l’honneur de la reine Victoria alors qu’elles étaient connues localement sous le nom de « fumée qui tonne ».',
    ),
    nature(
      'Chutes d’Iguazú',
      'Argentine',
      'AR',
      -25.6953,
      -54.4367,
      'Cet ensemble d’environ 275 chutes, inscrit au patrimoine mondial de l’UNESCO en 1984, s’étend sur près de trois kilomètres.',
    ),
    nature(
      'Uluru',
      'Australie',
      'AU',
      -25.3444,
      131.0369,
      'Restitué aux Aborigènes Pitjantjatjara en 1985, son ascension a été définitivement interdite le 26 octobre 2019.',
    ),
    nature(
      'Grande Barrière de corail',
      'Australie',
      'AU',
      -18.2871,
      147.6992,
      'S’étendant sur plus de 2 300 km, elle rassemble près de 2 900 récifs distincts au large du Queensland.',
    ),
    nature(
      'Lac Baïkal',
      'Russie',
      'RU',
      53.5587,
      108.165,
      'Avec 1 642 m de profondeur, c’est le lac le plus profond du monde ; il est aussi, avec environ 25 millions d’années, l’un des plus anciens.',
    ),
    nature(
      'Mer Morte',
      'Jordanie',
      'JO',
      31.559,
      35.4732,
      'À environ 440 m sous le niveau de la mer, c’est le point le plus bas de la surface terrestre ; sa salinité, près de dix fois supérieure à celle des océans, permet d’y flotter sans effort.',
    ),
    nature(
      'Désert d’Atacama',
      'Chili',
      'CL',
      -24.5,
      -69.25,
      'C’est le désert non polaire le plus aride du monde : certaines stations n’y ont mesuré que des traces de pluie en plusieurs siècles.',
    ),
    nature(
      'Îles Galápagos',
      'Équateur',
      'EC',
      -0.9538,
      -90.9656,
      'Charles Darwin y a séjourné en 1835, et ses observations sur les espèces de l’archipel ont nourri sa théorie de l’évolution publiée en 1859.',
    ),
    nature(
      'Île de Pâques',
      'Chili',
      'CL',
      -27.1127,
      -109.3497,
      'Découverte par les Européens un dimanche de Pâques 1722, elle compte près d’un millier de statues moaï.',
    ),
    nature(
      'Bora Bora',
      'Polynésie française',
      'PF',
      -16.5004,
      -151.7415,
      'Durant la Seconde Guerre mondiale, l’opération Bobcat y a débarqué près de 7 000 soldats américains en 1942, qui y construisent la première piste d’aviation de Polynésie française.',
    ),
    nature(
      'Maldives',
      'Maldives',
      'MV',
      4.1755,
      73.5093,
      'Avec un point culminant à seulement 2,3 m d’altitude, c’est l’un des pays les plus plats et les plus bas du monde.',
    ),
    nature(
      'Santorin',
      'Grèce',
      'GR',
      36.3932,
      25.4615,
      'Sa forme en croissant résulte de l’explosion volcanique minoenne, l’une des plus puissantes de l’histoire, survenue il y a environ 3 600 ans.',
    ),
    nature(
      'Cap Nord',
      'Norvège',
      'NO',
      71.1725,
      25.784,
      'Le navigateur anglais Steven Borough en a fait le tour et lui a donné son nom en 1553, alors qu’il cherchait un passage vers le nord-est.',
    ),
    nature(
      'Baie d’Halong',
      'Viêt Nam',
      'VN',
      20.9101,
      107.1839,
      'Inscrite au patrimoine mondial de l’UNESCO en 1994, elle rassemble près de 1 600 îlots karstiques.',
    ),
    nature(
      'Lac Léman',
      'Suisse',
      'CH',
      46.45,
      6.55,
      'Son niveau, autour de 372 m d’altitude, est régulé artificiellement, notamment par le barrage du Seujet à Genève.',
    ),
    nature(
      'Serengeti',
      'Tanzanie',
      'TZ',
      -2.3333,
      34.8333,
      'Chaque année, environ 1,6 million de gnous migrent à travers son écosystème, l’une des plus grandes migrations d’animaux terrestres au monde.',
    ),
    nature(
      'Cappadoce',
      'Turquie',
      'TR',
      38.6431,
      34.8286,
      'Plusieurs de ses sites, dont le parc national de Göreme, sont inscrits au patrimoine mondial de l’UNESCO depuis 1985.',
    ),
    nature(
      'Yosemite',
      'États-Unis',
      'US',
      37.8651,
      -119.5383,
      'En 1864, le président Abraham Lincoln en a décrété la protection, créant de fait le tout premier parc régional des États-Unis.',
    ),
  ]),

  ...intermediate([
    nature(
      'Calanques de Marseille',
      'France',
      'FR',
      43.211,
      5.44,
      'Créé en 2012, le parc national des Calanques est le premier parc national périurbain d’Europe, aux portes de Marseille.',
    ),
    nature(
      'Lac d’Annecy',
      'France',
      'FR',
      45.864,
      6.173,
      'Considéré comme l’un des lacs les plus purs d’Europe, il doit cette qualité à un vaste réseau de collecteurs construit à partir des années 1960 pour intercepter les eaux usées avant qu’elles ne l’atteignent.',
    ),
    nature(
      'Cirque de Gavarnie',
      'France',
      'FR',
      42.7275,
      -0.0083,
      'Sa Grande Cascade, haute d’environ 420 m, est l’une des plus hautes chutes d’eau d’Europe.',
    ),
    nature(
      'Pointe du Raz',
      'France',
      'FR',
      48.0358,
      -4.7367,
      'Classée Grand Site de France, elle fait face au Raz de Sein, un passage maritime réputé pour ses courants parmi les plus forts d’Europe.',
    ),
    nature(
      'Île de Ré',
      'France',
      'FR',
      46.19,
      -1.43,
      'Reliée au continent depuis 1988 par un pont de près de 3 km, longtemps l’un des plus longs de France.',
    ),
    nature(
      'Gorges de l’Ardèche',
      'France',
      'FR',
      44.38,
      4.5,
      'Le Pont d’Arc, arche naturelle sculptée par la rivière, culmine à une trentaine de mètres au-dessus de l’eau ; à proximité, la grotte Chauvet, découverte en 1994, abrite des peintures rupestres vieilles de 36 000 ans.',
    ),
    nature(
      'Lac Titicaca',
      'Pérou',
      'PE',
      -15.9254,
      -69.3354,
      'Situé à environ 3 812 m d’altitude, c’est le plus haut lac navigable au monde.',
    ),
    nature(
      'Lac Victoria',
      'Tanzanie',
      'TZ',
      -1.0,
      33.0,
      'Avec une superficie d’environ 68 000 km², c’est le plus grand lac d’Afrique et le deuxième plus grand lac d’eau douce du monde par sa surface.',
    ),
    nature(
      'Madère',
      'Portugal',
      'PT',
      32.7607,
      -16.9595,
      'Son réseau de levadas, canaux d’irrigation creusés dès le XVe siècle, s’étend sur plus de 2 000 km à travers l’île.',
    ),
    nature(
      'Cap Horn',
      'Chili',
      'CL',
      -55.9833,
      -67.2667,
      'Doubler ce cap redouté des marins, à la jonction des océans Atlantique et Pacifique, reste considéré comme l’un des passages maritimes les plus dangereux au monde.',
    ),
    nature(
      'Cap de Bonne-Espérance',
      'Afrique du Sud',
      'ZA',
      -34.3568,
      18.474,
      'Contrairement à une idée reçue, ce n’est pas le point le plus au sud du continent africain : ce titre revient au cap des Aiguilles, environ 150 km plus loin.',
    ),
    nature(
      'Geysir',
      'Islande',
      'IS',
      64.3104,
      -20.3024,
      'C’est de ce site que vient le mot « geyser » ; le grand Geysir est aujourd’hui peu actif, mais son voisin Strokkur entre en éruption toutes les 5 à 10 minutes.',
    ),
    nature(
      'Zhangjiajie',
      'Chine',
      'CN',
      29.317,
      110.434,
      'Ses pitons de grès, culminant à plus de 1 000 m, ont inspiré les montagnes flottantes du film Avatar (2009).',
    ),
    nature(
      'Fjord de Geiranger',
      'Norvège',
      'NO',
      62.1049,
      7.2058,
      'Inscrit au patrimoine mondial de l’UNESCO, il est bordé par la cascade des Sept Sœurs, dont les sept bras dévalent la paroi rocheuse.',
    ),
    nature(
      'Île Maurice',
      'Maurice',
      'MU',
      -20.3484,
      57.5522,
      'C’est sur cette île qu’a vécu le dodo, oiseau incapable de voler disparu à la fin du XVIIe siècle faute de défense face aux prédateurs introduits par l’homme.',
    ),
    nature(
      'Delta de l’Okavango',
      'Botswana',
      'BW',
      -19.2833,
      22.9,
      'Contrairement à la plupart des deltas, celui-ci ne rejoint jamais la mer : ses eaux se perdent par évaporation et infiltration dans le sable du Kalahari.',
    ),
    nature(
      'Dunes de Sossusvlei',
      'Namibie',
      'NA',
      -24.7275,
      15.3405,
      'Certaines de ses dunes, comme la « Big Daddy », dépassent 300 m de hauteur, parmi les plus hautes du monde.',
    ),
    nature(
      'Salar de Uyuni',
      'Bolivie',
      'BO',
      -20.1338,
      -67.4891,
      'Avec environ 10 000 km², c’est le plus grand désert de sel du monde.',
    ),
    nature(
      'Pantanal',
      'Brésil',
      'BR',
      -17.6,
      -57.0,
      'C’est la plus grande zone humide tropicale du monde, s’étendant sur près de 150 000 km² entre le Brésil, la Bolivie et le Paraguay.',
    ),
    nature(
      'Forêt amazonienne (Manaus)',
      'Brésil',
      'BR',
      -3.119,
      -60.0217,
      'Près de la ville, la « rencontre des eaux » voit le Rio Negro, sombre, et le Rio Solimões, clair, couler côte à côte sans se mélanger sur plusieurs kilomètres.',
    ),
    nature(
      'Milford Sound',
      'Nouvelle-Zélande',
      'NZ',
      -44.6414,
      167.9256,
      'Rudyard Kipling l’a qualifié de « huitième merveille du monde » ; malgré son nom, c’est en réalité un fjord et non un sound.',
    ),
    nature(
      'Douze Apôtres',
      'Australie',
      'AU',
      -38.6662,
      143.1044,
      'Le nom laisse penser qu’il y en a douze, mais il n’y en a jamais eu autant : l’érosion en a déjà fait s’effondrer plusieurs, dont un pan entier en 2005.',
    ),
    nature(
      'Grottes de Waitomo',
      'Nouvelle-Zélande',
      'NZ',
      -38.261,
      175.1039,
      'Ses plafonds sont constellés de vers luisants Arachnocampa luminosa, une espèce bioluminescente que l’on ne trouve qu’en Nouvelle-Zélande.',
    ),
    nature(
      'Antelope Canyon',
      'États-Unis',
      'US',
      36.8619,
      -111.3743,
      'Ce canyon en fente, sculpté par les crues éclair depuis des millénaires, se visite uniquement accompagné d’un guide navajo, sur les terres duquel il se trouve.',
    ),
    nature(
      'Monument Valley',
      'États-Unis',
      'US',
      36.998,
      -110.098,
      'Ses buttes de grès, hautes de plusieurs centaines de mètres, doivent leur couleur rouge à l’oxyde de fer ; le site a servi de décor à de nombreux westerns de John Ford.',
    ),
    nature(
      'Everglades',
      'États-Unis',
      'US',
      25.2866,
      -80.8987,
      'Souvent décrit comme une « rivière d’herbe », ce marais s’écoule en réalité très lentement du lac Okeechobee vers le golfe du Mexique.',
    ),
    nature(
      'Parc national de Banff',
      'Canada',
      'CA',
      51.4968,
      -115.9281,
      'Créé en 1885, c’est le plus ancien parc national du Canada.',
    ),
    nature(
      'Cratère du Ngorongoro',
      'Tanzanie',
      'TZ',
      -3.2,
      35.5,
      'Sa caldeira, intacte et non comblée, est la plus grande du monde ; elle abrite l’une des plus fortes densités de prédateurs d’Afrique.',
    ),
    nature(
      'Désert du Namib',
      'Namibie',
      'NA',
      -24.7333,
      15.2,
      'Considéré comme le plus vieux désert du monde, il existerait sous une forme aride depuis au moins 55 millions d’années.',
    ),
    nature(
      'Lacs de Plitvice',
      'Croatie',
      'HR',
      44.8654,
      15.582,
      'Ses seize lacs en cascade sont séparés par des barrières naturelles de travertin, une roche calcaire qui continue de se former aujourd’hui.',
    ),
    nature(
      'Pamukkale',
      'Turquie',
      'TR',
      37.9142,
      29.1189,
      'Ses terrasses de calcaire blanc, dont le nom signifie « château de coton », se sont formées par le dépôt de carbonate de calcium des sources chaudes au fil des millénaires.',
    ),
    nature(
      'Désert de Gobi',
      'Mongolie',
      'MN',
      43.0,
      105.0,
      'C’est dans ce désert qu’ont été découverts, en 1923, les premiers œufs de dinosaures jamais identifiés par la science.',
    ),
    nature(
      'Lac Powell',
      'États-Unis',
      'US',
      37.0642,
      -111.2378,
      'Ce lac artificiel, créé par le barrage de Glen Canyon achevé en 1966, est l’une des plus grandes retenues d’eau des États-Unis.',
    ),
    nature(
      'Parc national de Zion',
      'États-Unis',
      'US',
      37.2982,
      -113.0263,
      'La rivière Virgin y a creusé The Narrows, un canyon si étroit qu’il se parcourt en marchant dans le lit de la rivière elle-même.',
    ),
    nature(
      'Bryce Canyon',
      'États-Unis',
      'US',
      37.593,
      -112.1871,
      'Malgré son nom, ce n’est pas un canyon mais un amphithéâtre naturel qui abrite la plus grande concentration de hoodoos (cheminées de fée) au monde.',
    ),
    nature(
      'Île de Komodo',
      'Indonésie',
      'ID',
      -8.5445,
      119.489,
      'C’est l’habitat naturel du dragon de Komodo, le plus grand lézard vivant au monde, qui peut dépasser 3 m de long.',
    ),
    nature(
      'Lagon Bleu',
      'Islande',
      'IS',
      63.8804,
      -22.4495,
      'Ses eaux riches en silice et en minéraux proviennent en réalité de l’eau de refroidissement rejetée par une centrale géothermique voisine.',
    ),
    nature(
      'Jökulsárlón',
      'Islande',
      'IS',
      64.0784,
      -16.23,
      'Ce lac glaciaire, apparu dans les années 1930 avec le recul du glacier Breiðamerkurjökull, ne cesse de s’agrandir depuis lors.',
    ),
    nature(
      'Massif du Drakensberg',
      'Afrique du Sud',
      'ZA',
      -29.0,
      29.4167,
      'Ses chutes du Tugela, hautes d’environ 948 m, comptent parmi les plus hautes chutes d’eau du monde.',
    ),
    nature(
      'Lac Malawi',
      'Malawi',
      'MW',
      -12.3,
      34.5,
      'Il abrite plus d’espèces de poissons, en majorité des cichlidés, qu’aucun autre lac au monde.',
    ),
    nature(
      'Parc national des Montagnes Rocheuses',
      'États-Unis',
      'US',
      40.3428,
      -105.6836,
      'La Trail Ridge Road qui le traverse est la route continue goudronnée la plus haute des États-Unis, culminant à plus de 3 700 m d’altitude.',
    ),
    nature(
      'Wadi Rum',
      'Jordanie',
      'JO',
      29.5764,
      35.4206,
      'Surnommé la « vallée de la Lune », ce désert de grès et de granit a servi de décor à des films comme Lawrence d’Arabie et Seul sur Mars.',
    ),
    nature(
      'Météores',
      'Grèce',
      'GR',
      39.7217,
      21.6306,
      'Ses monastères, construits dès le XIVe siècle au sommet de pitons rocheux, n’étaient accessibles qu’au moyen d’échelles amovibles ou de filets hissés à la corde.',
    ),
    nature(
      'Réserve du Masai Mara',
      'Kenya',
      'KE',
      -1.5,
      35.0,
      'C’est ici que s’achève la Grande Migration, lorsque plus d’un million de gnous traversent la rivière Mara infestée de crocodiles.',
    ),
    nature(
      'Vallée de la Mort',
      'États-Unis',
      'US',
      36.5054,
      -117.0794,
      'Furnace Creek y a enregistré en 1913 la température de l’air la plus élevée jamais mesurée sur Terre, 56,7 °C.',
    ),
    nature(
      'Isle of Skye',
      'Royaume-Uni',
      'GB',
      57.3,
      -6.2,
      'Ses formations rocheuses, comme le Old Man of Storr, résultent d’anciens glissements de terrain survenus après la dernière glaciation.',
    ),
    nature(
      'Giant’s Causeway',
      'Royaume-Uni',
      'GB',
      55.2408,
      -6.5116,
      'Ses quelque 40 000 colonnes de basalte hexagonales, vieilles d’environ 60 millions d’années, seraient selon la légende les vestiges d’une chaussée construite par le géant Finn McCool.',
    ),
    nature(
      'Falaises de Moher',
      'Irlande',
      'IE',
      52.9715,
      -9.4309,
      'Hautes de 214 m à leur point culminant, elles ont servi de décor à la grotte de Poudlard dans Harry Potter et le Prince de sang-mêlé.',
    ),
    nature(
      'Parc national Kruger',
      'Afrique du Sud',
      'ZA',
      -23.9884,
      31.5547,
      'Avec près de 20 000 km², c’est l’une des plus grandes réserves animalières d’Afrique, qui abrite les « Big Five ».',
    ),
    nature(
      'Arches National Park',
      'États-Unis',
      'US',
      38.7331,
      -109.5925,
      'Il rassemble plus de 2 000 arches naturelles de grès, dont la célèbre Delicate Arch, visible sur les plaques d’immatriculation de l’Utah.',
    ),
    nature(
      'Big Sur',
      'États-Unis',
      'US',
      36.2704,
      -121.8081,
      'La Highway 1 qui longe cette côte escarpée franchit le pont Bixby Creek, achevé en 1932 et longtemps l’un des plus hauts ponts en arc simple du monde.',
    ),
  ]),

  ...hard([
    nature(
      'Île de Porquerolles',
      'France',
      'FR',
      43.0004,
      6.2064,
      'L’État en a acquis la majeure partie en 1971, ce qui a permis de préserver près de 80 % de l’île de toute urbanisation.',
    ),
    nature(
      'Belle-Île-en-Mer',
      'France',
      'FR',
      47.34,
      -3.16,
      'L’actrice Sarah Bernhardt y possédait un fort, à la pointe des Poulains, qu’elle a habité chaque été de 1894 à 1922.',
    ),
    nature(
      'Baie de Somme',
      'France',
      'FR',
      50.23,
      1.58,
      'Elle abrite la plus grande colonie de phoques veaux-marins de France, avec plusieurs centaines d’individus.',
    ),
    nature(
      'Lac du Bourget',
      'France',
      'FR',
      45.73,
      5.86,
      'C’est le plus grand lac naturel entièrement français ; le poète Alphonse de Lamartine s’en est inspiré pour son poème « Le Lac » (1820).',
    ),
    nature(
      'Forêt de Fontainebleau',
      'France',
      'FR',
      48.4037,
      2.6994,
      'Ses blocs de grès en ont fait, dès la fin du XIXe siècle, le berceau de l’escalade de bloc moderne.',
    ),
    nature(
      'Marais poitevin',
      'France',
      'FR',
      46.3167,
      -0.75,
      'Surnommé la « Venise verte », il doit ce nom à son réseau de canaux bordés de frênes têtards, traditionnellement parcourus en barque à fond plat.',
    ),
    nature(
      'Salines de Guérande',
      'France',
      'FR',
      47.3,
      -2.4667,
      'Le sel y est récolté à la main depuis le Moyen Âge selon des méthodes inchangées, dont la précieuse fleur de sel, cueillie à la surface des bassins.',
    ),
    nature(
      'Cirque de Navacelles',
      'France',
      'FR',
      43.887,
      3.5972,
      'Ce cirque résulte d’un ancien méandre de la rivière Vis, abandonné lorsqu’elle a fini par se frayer un passage plus direct.',
    ),
    nature(
      'Cirque de Salazie',
      'France',
      'FR',
      -21.0333,
      55.5333,
      'L’un des trois cirques de l’île de La Réunion, c’est aussi le plus arrosé, avec plus de 3 000 mm de pluie par an par endroits.',
    ),
    nature(
      'Chutes Angel',
      'Venezuela',
      'VE',
      5.9701,
      -62.5362,
      'Avec une chute ininterrompue d’environ 979 m, ce sont les plus hautes chutes d’eau du monde ; elles doivent leur nom à l’aviateur américain Jimmie Angel, qui s’y est posé en 1937.',
    ),
    nature(
      'Delta du Nil',
      'Égypte',
      'EG',
      30.5,
      31.0,
      'Ce delta, l’un des plus fertiles du monde, concentre à lui seul plus de 40 % de la population égyptienne sur une infime partie du territoire.',
    ),
    nature(
      'Skeleton Coast',
      'Namibie',
      'NA',
      -20.0,
      13.0,
      'Son nom vient des ossements de baleines et des épaves de navires échoués sur ses plages, victimes des brouillards fréquents et des courants violents.',
    ),
    nature(
      'Chutes Kaieteur',
      'Guyana',
      'GY',
      5.1706,
      -59.4863,
      'Sa chute d’un seul jet, haute d’environ 226 m, en fait la plus haute chute à fort débit du monde, avec plus de quatre fois la hauteur des chutes du Niagara.',
    ),
    nature(
      'Péninsule du Kamtchatka',
      'Russie',
      'RU',
      56.0,
      160.0,
      'Cette péninsule volcanique compte plus de 300 volcans, dont près de 30 encore actifs, inscrits au patrimoine mondial de l’UNESCO.',
    ),
    nature(
      'Nærøyfjord',
      'Norvège',
      'NO',
      60.9,
      6.85,
      'Large de seulement 250 m par endroits, c’est l’un des fjords les plus étroits du monde.',
    ),
    nature(
      'Îles Lofoten',
      'Norvège',
      'NO',
      68.15,
      13.6,
      'Les sommets qui plongent directement dans la mer y côtoient d’immenses claies de séchage de morue, une tradition de pêche vieille de plus de mille ans.',
    ),
    nature(
      'Parc national de Denali',
      'États-Unis',
      'US',
      63.1148,
      -151.1926,
      'Il abrite le mont Denali, point culminant de l’Amérique du Nord avec environ 6 190 m d’altitude.',
    ),
    nature(
      'Raja Ampat',
      'Indonésie',
      'ID',
      -0.5,
      130.5,
      'Cet archipel concentre l’une des plus grandes biodiversités marines connues sur Terre, avec plus de 1 500 espèces de poissons recensées.',
    ),
    nature(
      'Chutes de Gullfoss',
      'Islande',
      'IS',
      64.3271,
      -20.1199,
      'Au début du XXe siècle, la fermière islandaise Sigríður Tómasdóttir a mené une longue bataille pour empêcher la construction d’un barrage qui aurait englouti la cascade.',
    ),
    nature(
      'Dead Vlei',
      'Namibie',
      'NA',
      -24.759,
      15.2913,
      'Ses arbres morts, des acacias camelthorn vieux de plusieurs siècles, ne se décomposent pas : le climat trop sec empêche toute pourriture.',
    ),
    nature(
      'Cenote Ik Kil',
      'Mexique',
      'MX',
      20.6764,
      -88.5626,
      'Ce puits naturel s’est formé par l’effondrement du plafond d’une cavité calcaire, typique du sous-sol karstique du Yucatán.',
    ),
    nature(
      'Îles Similan',
      'Thaïlande',
      'TH',
      8.65,
      97.65,
      'Cet archipel de granit, classé parc national marin, figure régulièrement parmi les plus beaux spots de plongée au monde.',
    ),
    nature(
      'Fjord du Saguenay',
      'Canada',
      'CA',
      48.3667,
      -70.0,
      'À son embouchure, près de Tadoussac, ses eaux froides et riches en nutriments attirent l’une des rares populations de bélugas vivant aussi loin au sud.',
    ),
    nature(
      'Grotte de Benagil',
      'Portugal',
      'PT',
      37.0888,
      -8.4265,
      'Sa grotte, percée d’une ouverture au sommet qui laisse entrer la lumière du jour, ne s’atteint que par la mer, en bateau, en kayak ou à la nage.',
    ),
    nature(
      'Bouches de Kotor',
      'Monténégro',
      'ME',
      42.4247,
      18.7712,
      'Souvent présentée comme le fjord le plus au sud d’Europe, elle est en réalité un canyon fluvial englouti par la mer, et non un véritable fjord glaciaire.',
    ),
    nature(
      'Delta du Danube',
      'Roumanie',
      'RO',
      45.2,
      29.3,
      'C’est le delta fluvial le mieux conservé d’Europe, classé réserve de biosphère par l’UNESCO depuis 1990.',
    ),
    nature(
      'Torres del Paine',
      'Chili',
      'CL',
      -50.9423,
      -73.4068,
      'Ses trois tours de granit, sculptées par les glaciers, culminent à plus de 2 800 m au-dessus des steppes patagonnes.',
    ),
    nature(
      'Perito Moreno',
      'Argentine',
      'AR',
      -50.4967,
      -73.1387,
      'C’est l’un des rares glaciers au monde encore en expansion ; sa langue avance suffisamment pour former par intermittence un barrage de glace qui finit par s’effondrer spectaculairement.',
    ),
    nature(
      'Cañón del Colca',
      'Pérou',
      'PE',
      -15.6,
      -71.9,
      'Profond de plus de 3 000 m par endroits, soit environ le double du Grand Canyon, il abrite l’une des plus importantes populations de condors des Andes.',
    ),
    nature(
      'Redwood National Park',
      'États-Unis',
      'US',
      41.2132,
      -124.0046,
      'Il protège les arbres les plus hauts du monde, des séquoias côtiers pouvant dépasser 115 m, soit près de deux fois la hauteur de la statue de la Liberté.',
    ),
    nature(
      'Tongariro',
      'Nouvelle-Zélande',
      'NZ',
      -39.1,
      175.6417,
      'Créé en 1887 grâce au don des terres sacrées par le chef māori Te Heuheu Tukino IV, c’est le plus ancien parc national de Nouvelle-Zélande.',
    ),
    nature(
      'Plage de Navagio',
      'Grèce',
      'GR',
      37.8592,
      20.6242,
      'Elle doit son surnom de « plage du naufrage » à l’épave du Panagiotis, un cargo échoué sur son sable en 1980 et toujours visible aujourd’hui.',
    ),
    nature(
      'Lysefjord',
      'Norvège',
      'NO',
      58.9866,
      6.19,
      'La falaise du Preikestolen, qui le surplombe à environ 600 m de hauteur, est devenue l’un des sites de randonnée les plus prisés de Norvège.',
    ),
    nature(
      'Vatnajökull',
      'Islande',
      'IS',
      64.4,
      -16.9,
      'C’est le plus grand glacier d’Europe par son volume ; il recouvre plusieurs volcans actifs, dont le Grímsvötn, qui provoquent régulièrement des crues glaciaires soudaines.',
    ),
    nature(
      'Lençóis Maranhenses',
      'Brésil',
      'BR',
      -2.4967,
      -43.0,
      'Ses dunes de sable blanc se remplissent chaque année, pendant la saison des pluies, de lagons d’eau douce turquoise qui s’assèchent ensuite peu à peu.',
    ),
    nature(
      'Copper Canyon',
      'Mexique',
      'MX',
      27.5333,
      -107.6667,
      'Ce réseau de canyons est, par endroits, plus profond et plus vaste que le Grand Canyon américain.',
    ),
    nature(
      'Désert du Kalahari',
      'Botswana',
      'BW',
      -23.0,
      21.5,
      'Malgré son nom, ce n’est pas un désert au sens strict : il reçoit assez de précipitations pour soutenir une végétation éparse et la faune qui en dépend.',
    ),
    nature(
      'Montagnes du Simien',
      'Éthiopie',
      'ET',
      13.25,
      38.25,
      'Elles abritent le Ras Dashen, point culminant de l’Éthiopie avec environ 4 550 m, ainsi que le gélada, un primate endémique du pays.',
    ),
    nature(
      'Erg Chigaga',
      'Maroc',
      'MA',
      29.9,
      -5.9,
      'L’un des plus grands ergs du Maroc, il ne s’atteint qu’après plusieurs heures de piste en 4x4 ou plusieurs jours à dos de dromadaire depuis M’Hamid.',
    ),
    nature(
      'Phong Nha-Kẻ Bàng',
      'Viêt Nam',
      'VN',
      17.5953,
      106.2836,
      'Il abrite la grotte de Sơn Đoòng, explorée pour la première fois en 2009, la plus grande galerie souterraine connue au monde.',
    ),
    nature(
      'Sundarbans',
      'Bangladesh',
      'BD',
      21.9497,
      89.1833,
      'C’est la plus grande mangrove du monde ; elle abrite une population de tigres du Bengale capables de nager entre les îles.',
    ),
    nature(
      'Lac Tonlé Sap',
      'Cambodge',
      'KH',
      12.8,
      104.1,
      'Chaque année, la mousson inverse le cours de la rivière Tonlé Sap, ce qui fait gonfler la surface du lac jusqu’à plusieurs fois sa taille de saison sèche.',
    ),
    nature(
      'Cañón del Sumidero',
      'Mexique',
      'MX',
      16.85,
      -93.1,
      'Selon la légende, des habitants chiapanèques se seraient jetés du haut de ses parois, hautes de près de 1 000 m, plutôt que de se soumettre aux conquistadors espagnols au XVIe siècle.',
    ),
    nature(
      'Sognefjord',
      'Norvège',
      'NO',
      61.0,
      7.0,
      'Long d’environ 205 km et profond de plus de 1 300 m par endroits, c’est le plus long et le plus profond fjord de Norvège.',
    ),
    nature(
      'Grottes de Carlsbad',
      'États-Unis',
      'US',
      32.1479,
      -104.5567,
      'Des centaines de milliers de chauves-souris nichent dans ses galeries et en sortent chaque soir en un impressionnant nuage.',
    ),
  ]),

  ...master([
    nature(
      'Chott el Djerid',
      'Tunisie',
      'TN',
      33.7,
      8.4,
      'Ce lac salé, le plus grand du Sahara avec plusieurs milliers de km², est à sec la majeure partie de l’année ; ses abords ont servi de décor à la planète Tatooine dans Star Wars.',
    ),
    nature(
      'Dépression du Danakil',
      'Éthiopie',
      'ET',
      14.24,
      40.3,
      'Avec des points situés jusqu’à environ 125 m sous le niveau de la mer, c’est l’un des endroits habités les plus chauds de la planète ; son site de Dallol doit ses couleurs vives à des sources hydrothermales chargées de soufre et de sels minéraux.',
    ),
    nature(
      'Doubtful Sound',
      'Nouvelle-Zélande',
      'NZ',
      -45.28,
      167.05,
      'Le capitaine James Cook, qui l’a découvert et nommé en 1770, a jugé « douteuse » (doubtful) sa capacité à en ressortir à la voile et a préféré ne pas s’y aventurer.',
    ),
    nature(
      'Great Blue Hole',
      'Belize',
      'BZ',
      17.3162,
      -87.535,
      'Ce gouffre marin, large d’environ 300 m et profond de plus de 120 m, est un ancien réseau de grottes karstiques effondré et englouti à la fin de la dernière glaciation.',
    ),
    nature(
      'Îles Marquises',
      'Polynésie française',
      'PF',
      -9.0,
      -139.5,
      'Paul Gauguin et Jacques Brel ont tous deux vécu leurs dernières années sur l’île de Hiva Oa, où ils sont enterrés à quelques mètres l’un de l’autre.',
    ),
    nature(
      'Grotte de Škocjan',
      'Slovénie',
      'SI',
      45.6667,
      13.9833,
      'La rivière Reka y disparaît sous terre pour creuser l’un des plus grands canyons souterrains connus au monde, avec une galerie principale haute par endroits de plus de 100 m.',
    ),
    nature(
      'Lac Assal',
      'Djibouti',
      'DJ',
      11.6603,
      42.4108,
      'À environ 155 m sous le niveau de la mer, c’est le point le plus bas d’Afrique ; sa salinité, parmi les plus élevées au monde, dépasse même par endroits celle de la mer Morte.',
    ),
    nature(
      'Lac Natron',
      'Tanzanie',
      'TZ',
      -2.42,
      36.0,
      'Ses eaux, très alcalines et pouvant atteindre 60 °C, calcifient parfois les animaux qui s’y noient ; c’est pourtant le principal site de reproduction des flamants nains d’Afrique de l’Est.',
    ),
    nature(
      'Tsingy de Bemaraha',
      'Madagascar',
      'MG',
      -18.9,
      44.7333,
      'Le mot malgache « tsingy » évoque l’idée de marcher sur la pointe des pieds, en référence aux arêtes calcaires acérées comme des lames qui composent ce massif karstique.',
    ),
    nature(
      'Allée des Baobabs',
      'Madagascar',
      'MG',
      -20.2333,
      44.4167,
      'Les baobabs Adansonia grandidieri qui la bordent, âgés parfois de plusieurs siècles, sont les derniers vestiges d’une forêt dense défrichée au fil du temps pour l’agriculture.',
    ),
    nature(
      'Ningaloo Reef',
      'Australie',
      'AU',
      -22.6667,
      113.6667,
      'Contrairement à la Grande Barrière de corail, ce récif frangeant est accessible directement depuis la plage ; il attire chaque année des requins-baleines venus se nourrir du plancton libéré par le corail.',
    ),
    nature(
      'Kimberley',
      'Australie',
      'AU',
      -17.0,
      127.0,
      'Cette région isolée abrite des peintures rupestres aborigènes, les Gwion Gwion, dont certaines pourraient compter parmi les plus anciennes œuvres d’art connues au monde.',
    ),
    nature(
      'Désert des Pinacles',
      'Australie',
      'AU',
      -30.5975,
      115.1611,
      'Ses milliers de piliers calcaires, hauts parfois de plus de 3 m, se seraient formés à partir de coquillages marins accumulés puis cimentés au fil de millénaires — leur origine exacte reste débattue par les géologues.',
    ),
    nature(
      'Lac Van',
      'Turquie',
      'TR',
      38.6,
      42.9,
      'Ses eaux très alcalines n’abritent qu’une seule espèce de poisson capable d’y survivre, qui doit migrer vers l’embouchure des rivières d’eau douce pour se reproduire.',
    ),
    nature(
      'Vallée des Geysers',
      'Russie',
      'RU',
      54.43,
      160.14,
      'Découverte seulement en 1941, c’est la deuxième concentration de geysers au monde après celle de Yellowstone ; une coulée de boue en a détruit une partie en 2007.',
    ),
    nature(
      'Péninsule de Yamal',
      'Russie',
      'RU',
      70.0,
      70.0,
      'Depuis 2014, d’étranges cratères y apparaissent brutalement, provoqués par des explosions de méthane libéré par le dégel du permafrost.',
    ),
    nature(
      'Trolltunga',
      'Norvège',
      'NO',
      60.1242,
      6.7398,
      'Ce rocher, qui surplombe un lac à plus de 700 m de hauteur, est resté quasiment inconnu des randonneurs jusqu’au début des années 2010, avant de devenir un site prisé grâce aux réseaux sociaux.',
    ),
    nature(
      'Landmannalaugar',
      'Islande',
      'IS',
      63.9938,
      -19.0578,
      'Ses montagnes de rhyolite doivent leurs teintes multicolores à la composition chimique variée de cette roche volcanique riche en silice.',
    ),
    nature(
      'Grotte de Fingal',
      'Royaume-Uni',
      'GB',
      56.4335,
      -6.3406,
      'Ses colonnes de basalte hexagonales, semblables à celles de la Chaussée des Géants, ont inspiré au compositeur Felix Mendelssohn son ouverture Les Hébrides après sa visite en 1829.',
    ),
    nature(
      'Chapada Diamantina',
      'Brésil',
      'BR',
      -12.5833,
      -41.5,
      'Son nom rappelle la ruée vers les diamants qui a attiré des milliers de chercheurs dans la région au XIXe siècle.',
    ),
    nature(
      'Fernando de Noronha',
      'Brésil',
      'BR',
      -3.85,
      -32.4167,
      'Pour protéger son écosystème, le nombre de visiteurs y est limité chaque jour et une taxe environnementale est perçue ; Charles Darwin y a fait escale en 1832 à bord du Beagle.',
    ),
    nature(
      'Réserve de Chobe',
      'Botswana',
      'BW',
      -18.6,
      24.7,
      'Elle abrite l’une des plus fortes concentrations d’éléphants d’Afrique, avec une population estimée à plusieurs dizaines de milliers d’individus.',
    ),
    nature(
      'Hierve el Agua',
      'Mexique',
      'MX',
      16.8667,
      -96.2667,
      'Ses « cascades pétrifiées » ne sont pas de la glace mais du carbonate de calcium déposé par des sources d’eau minérale au fil de milliers d’années.',
    ),
    nature(
      'Lac Turkana',
      'Kenya',
      'KE',
      3.5,
      36.0,
      'Surnommé la « mer de Jade » pour la couleur turquoise de ses eaux alcalines, c’est le plus grand lac permanent en zone désertique du monde ; ses rives ont livré d’importants fossiles d’hominidés.',
    ),
    nature(
      'Glacier Bay',
      'États-Unis',
      'US',
      58.6658,
      -136.9002,
      'Entièrement recouverte de glace il y a environ 250 ans, la baie s’est libérée grâce à l’un des retraits glaciaires les plus rapides jamais enregistrés, sur près de 100 km.',
    ),
  ]),
];
