import type { Language } from '@/i18n';
import type { ContourDataRow, ClueFlagColorRow } from '@/types';

import countriesData from './countries.json';
import countryBordersData from './countryBorders.json';
import countryContoursData from './countryContours.json';
import countryCurrenciesData from './countryCurrencies.json';
import countryFlagsData from './countryFlags.json';
import countryPhoneCodesData from './countryPhoneCodes.json';

/**
 * Per-country data (ISO 3166-1 alpha-2 code, every file's own key — already short and globally
 * unique, no key-generation scheme needed, unlike `places.json`'s split) spread across 6 small
 * files, all sparse except `countries.json` itself:
 * - `countries.json`: `{ code: [fr, en] }` — every country has one.
 * - `countryFlags.json` (`ClueFlagColorRow[]`), `countryCurrencies.json`
 *   (`[currency, currencySymbol]`), `countryPhoneCodes.json` (`phoneCode`): present only once
 *   filled in (a country can exist without any place using it yet in Clues).
 * - `countryContours.json` (`ContourDataRow`): present only for a country with Contour/Silhouette
 *   data (`data/contours/codec.ts` reads this file directly).
 * - `countryBorders.json` (`readonly string[]`): the sorted ISO codes of every country sharing a
 *   land border with this one, symmetric (A lists B <=> B lists A), present only for a country
 *   with at least one (an island has none). Unrelated to `contour.neighbors` (the few neighbors
 *   POSITIONED on the board for the Silhouette hints). Both are generated by
 *   `scripts/generateContours.mjs` — the only one of these 6 files it ever writes to (identity/
 *   flag/currency/phone code are hand-edited, like the rest of the app's data).
 *
 * Places only store `code`: everything else is derived from here, avoiding repeating it (and
 * desyncing it) per place — currency/phone code never vary within a given country, unlike
 * difficulty or the trivia, which are specific to each place.
 */
export type CountryRow = readonly [fr: string, en: string];

export type CountryEntry = {
  fr: string;
  en: string;
  flag: ClueFlagColorRow[] | null;
  currency: string | null;
  currencySymbol: string | null;
  phoneCode: string | null;
  /** Absent for the many countries with no Contour/Silhouette data. */
  contour?: ContourDataRow;
  /** ISO codes of the countries sharing a land border with this one — empty for an island. */
  neighbors: readonly string[];
};

const COUNTRIES = countriesData as unknown as Record<string, CountryRow>;
const COUNTRY_FLAGS = countryFlagsData as unknown as Record<string, ClueFlagColorRow[]>;
const COUNTRY_CURRENCIES = countryCurrenciesData as unknown as Record<string, readonly [string, string]>;
const COUNTRY_PHONE_CODES = countryPhoneCodesData as unknown as Record<string, string>;
const COUNTRY_CONTOURS = countryContoursData as unknown as Record<string, ContourDataRow>;
const COUNTRY_BORDERS = countryBordersData as unknown as Record<string, readonly string[]>;

/** `code`'s full entry, joined from the 6 files above — `null` for a code not in `countries.json`
 * at all. */
export const decodeCountry = (code: string): CountryEntry | null => {
  const row = COUNTRIES[code];
  if (!row) return null;
  const [fr, en] = row;
  const currency = COUNTRY_CURRENCIES[code];
  return {
    fr,
    en,
    flag: COUNTRY_FLAGS[code] ?? null,
    currency: currency?.[0] ?? null,
    currencySymbol: currency?.[1] ?? null,
    phoneCode: COUNTRY_PHONE_CODES[code] ?? null,
    contour: COUNTRY_CONTOURS[code],
    neighbors: COUNTRY_BORDERS[code] ?? [],
  };
};

/** Every country, joined — for the admin's own listing (`api/countries.ts`). */
export const decodeAllCountries = (): (CountryEntry & { code: string })[] =>
  Object.keys(COUNTRIES).map((code) => ({ code, ...decodeCountry(code)! }));

/** ISO codes of the countries sharing a land border with `code` (sorted, symmetric; empty for an
 * island or an unknown code). */
export const countryNeighbors = (code: string): readonly string[] => COUNTRY_BORDERS[code] ?? [];

export const countryName = (code: string, language: Language): string => {
  const row = COUNTRIES[code];
  if (!row) return code;
  return language === 'fr' ? row[0] : row[1];
};

/** Field indexes of a `flag` row (positional tuple, see `ClueFlagColorRow`). */
export const FLAG_COLOR_FIELD = {
  COLOR_ID: 0,
  HEX: 1,
  PERCENT: 2,
} as const;

export const countryFlagColors = (code: string): ClueFlagColorRow[] | undefined => COUNTRY_FLAGS[code];

/** Generic currency name (never the nationality adjective: "Dollar", not "Zimbabwean
 * Dollar" or "American Dollar" — that would amount to giving away the country). */
export const countryCurrencyName = (code: string): string | undefined => COUNTRY_CURRENCIES[code]?.[0];

/** Currency symbol/code (e.g. "€", "AED"): several countries can legitimately share
 * one (euro zone...). */
export const countryCurrencySymbol = (code: string): string | undefined => COUNTRY_CURRENCIES[code]?.[1];

/** International phone code (e.g. "+33"). */
export const countryPhoneCode = (code: string): string | undefined => COUNTRY_PHONE_CODES[code];

export { flagEmoji } from '@/helpers/flagEmoji';
